### ISSUE TITLE
Error compiling Schema when validations are run

### ISSUE THREAD

**Issue by gaganmeet** [rjsf-team/react-jsonschema-form#2895] opened 2022-06-25 09:53 UTC
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

chakra-ui

### Version

4.2.0

### Current Behavior

I have added a form on my react app which has rather simple schema for testing and it's throwing an error mentioned on submitting. After it submit functions runs without checking for validations.
![rjfserror](https://user-images.githubusercontent.com/14325940/175768324-c3d05265-3e6d-411d-8dbe-128fd1a3ed68.png)

### Expected Behavior

Add a form with simple schema:
```
{
  "title": "A registration form",
  "description": "A simple form example.",
  "type": "object",
  "required": [
    "firstName",
    "lastName"
  ],
  "properties": {
    "firstName": {
      "type": "string",
      "title": "First name",
      "default": "Chuck",
      "minLength": 3
    }
  }
}
```

### Environment

```markdown
- OS: Windows 11
- Node: 16.14.2
- npm: 8.5.0
```

**Comment by epicfaace** [comment] 2022-06-26 15:33
Please provide a playground link.

**Comment by JohnRosner** [comment] 2022-07-05 14:36
The error message here is the same as the one here: https://github.com/rjsf-team/react-jsonschema-form/issues/2020

I've also run into this error message but only on a production build. When I get the error, and copy the schema I'm using to the playground, the error does not appear and therefore I'm unable to reproduce the error in the playground making it difficult to track down this bug.

**Comment by gaganmeet** [comment] 2022-07-05 14:42
I am not able to reproduce same error on playground as I am using it to build a chrome extension. I tried using ajv explicitly to check for errors and got same error.

**Comment by heath-freenome** [comment] 2022-07-05 17:11
It maybe a symptom of this [issue](https://github.com/ajv-validator/ajv/issues/406) in AJV6... we are actively working on a v5 version (with breaking changes) that will support using AJV8 where that issue is fixed

**Comment by JohnRosner** [comment] 2022-07-05 17:43
Out of curiosity, what is the estimate on when v5 will be released?

**Comment by heath-freenome** [comment] 2022-07-06 00:00
we are shooting for an alpha by august... beta by september, release before october... That's the best guess right now

**Comment by skysantoroa** [comment] 2022-09-05 11:17
Any version not affected by this?

**Comment by heath-freenome** [comment] 2022-12-09 16:50
Duplicate of #2020

**Closed by heath-freenome** 2022-12-09 16:50 UTC
Labels: bug, needs triage
