### ISSUE TITLE
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended 

### ISSUE THREAD

**Issue by yudao** [rjsf-team/react-jsonschema-form#1794] opened 2020-06-03 17:37 UTC
Hi!

I have an old bug [see here](https://github.com/rjsf-team/react-jsonschema-form/issues/1436) but i'm with the last version.

I know that the warning is not raised in production but normally this bug was fixed in the 2.0 version, isn't it ?

I'm only reusing one Form component and only change data and uischema for each schema I have in my multistep form.

### Description

index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: Form

### Version
react: 16.13.1
@rjsf/core: 2.0.1

Cheers,
Yu.

**Comment by epicfaace** [comment] 2020-06-15 13:29
Yes, we still use UNSAFE_componentWillReceiveProps in 2.0 -- the only thing that was fixed was removing a few instances of this method, and mostly just renaming componentWillReceiveProps -> UNSAFE_ componentWillReceiveProps. If you'd like to help with refactoring to remove it, that would be very much appreciated!

**Comment by ievgennaida** [comment] 2020-12-07 12:56
I have the same warning.
What should be done to avoid that?

**Comment by mrjuan1** [comment] 2021-01-18 10:20
Is there a PR for this yet?

**Comment by caseyjhol** [comment] 2021-01-18 16:52
It doesn't look like it yet. More info on a fix:

https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops
https://itnext.io/react17-or-how-to-get-rid-of-componentwillreceiveprops-c91f9a6f6f03

**Comment by Link631** [comment] 2021-03-08 02:21
Hi, I found the same warning. 

When can the checkin be expected in a release and will it fix this Issue so that the warning disappears?

**Comment by dedenbangkit** [comment] 2021-03-17 07:15
Still no fix for this issue?

**Comment by rocknatt** [comment] 2021-04-01 12:47
I think issue is still there. Is there a way to fix it?

**Comment by germanelnica** [comment] 2021-04-08 23:06
this is the commit with the fix 
https://github.com/mrjuan1/react-jsonschema-form/commit/0dd427d5368db4ca9458c77fca79887d48a0d748

**Comment by samuelcotterall** [comment] 2021-07-18 08:26
> this is the commit with the fix
> [mrjuan1@0dd427d](https://github.com/mrjuan1/react-jsonschema-form/commit/0dd427d5368db4ca9458c77fca79887d48a0d748)

Maybe I’m being dumb, but I can’t see a PR for this (neither open nor closed)?

**Comment by epicfaace** [comment] 2021-07-18 15:09
@jimmycallin has a slightly more complex PR https://github.com/rjsf-team/react-jsonschema-form/pull/2010 that does this, though maybe https://github.com/mrjuan1/react-jsonschema-form/commit/0dd427d5368db4ca9458c77fca79887d48a0d748 would just work as a simpler solution instead? What do you think @jimmycallin ?

**Comment by jimmycallin** [comment] 2021-07-18 18:46
"slightly more complex" is surely an understatement. If it works, I'm happy! I'll see if I can figure out why I thought the refactorings were necessary.

**Comment by jimmycallin** [comment] 2021-07-21 22:32
Ok, I just looked into the commit and it won't work unfortunately, for the reasons that caused me to introduce the necessary refactorings.

![image](https://user-images.githubusercontent.com/2225828/126568135-13b0ae40-8073-4b62-822b-b83b6c3fc268.png)

On line 45 you can see that it calls a class method using `this.getStateFromProps`. Since it's a static method, this is not allowed. Once you start to break out all logic related to this.getStateFromProps, you will probably end up with a PR similar to my #2010.

**Comment by skysantoroa** [comment] 2022-06-28 08:26
Any update on this?

**Comment by rmannibucau** [comment] 2022-08-25 10:30
up? We now have react 18 out and this issue popped up in a previous major release so it would be neat to fix it.

**Comment by hickscorp** [comment] 2023-05-25 23:26
Is there any status update on this issue?

**Comment by the-blue-coder** [comment] 2023-05-28 17:01
The issue is still present

**Comment by modellking** [comment] 2023-10-05 10:41
Is this on the roadmap? Do you require external contribution?

**Closed** 2023-10-28 00:14 UTC
Labels: react 18 issue

**Comment by iwan-uschka** [comment] 2023-11-12 21:09
Fixed. Thanks!
