### ISSUE TITLE
Nested object with additionalProperties not working when using omitExtraData and liveOmit

### ISSUE THREAD

**Issue by ValYouW** [rjsf-team/react-jsonschema-form#1741] opened 2020-05-04 11:04 UTC
### Description
Having a nested object with `additionalProperties` is not working properly, clicking on the "+" button to add a new key/value does nothing.

### Steps to Reproduce

Demo [jsFiddle](https://jsfiddle.net/1borwt9m/5/)

Just in case:
```js
const Form = JSONSchemaForm.default;
const schema = {
  title: "liveOmit nested object bug demo",
  type: "object",
  properties: {
    name: {type: "string"},
    nested: {
      type: "object",
      additionalProperties: {type: "string"}
    }
  }
};

ReactDOM.render(<Form
  schema={schema}
  omitExtraData={true}
  liveOmit={true}
  formData={{name: 'tap on "+" below', nested: {a: 123}}}
/>,
document.getElementById("main"));
```

#### Expected behavior

Should add/remove properties freely

#### Actual behavior

Clicking "+" button does nothing, if the nested object contains some initial values they are all removed.

### Version
1.8.1

**Comment by achendrick** [comment] 2020-05-13 17:13
This looks like a duplicate of #1497

**Comment by epicfaace** [comment] 2020-05-13 18:09
Yeah, it's a duplicate of #1497.

**Closed by epicfaace** 2020-05-13 18:09 UTC

**Comment by ValYouW** [comment] 2020-05-13 19:00
@achendrick No, I just converted the "additional properties" property to a "json text field"...
@epicfaace tx

**Comment by achendrick** [comment] 2020-05-13 20:08
@ValYouW oh, not a bad temporary solution. thanks for sharing!
