### ISSUE TITLE
Incorrect implementation of json-schema default keyword

### ISSUE THREAD

**Issue by SorinGFS** [rjsf-team/react-jsonschema-form#3433] opened 2023-02-04 14:52 UTC
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

When a schema has `default` defined `react-json-schema-form` fills the corresponding field with the `default` value.

### Expected Behavior

The functionality of `default` keyword is crystal clear in `json-schema` [specifications](https://json-schema.org/understanding-json-schema/reference/generic.html?highlight=default#id2):

> The default keyword specifies a default value. This value **is not used to fill in missing values** during the validation process. Non-validation tools such as documentation generators or **form generators may use this value to give hints** to users about how to use a value. However, default is typically used to express that if a value is missing, then the value is semantically the same as if the value was present with the default value. The value of default should validate against the schema in which it resides, but that isn’t required.

Therefore, expected behaviour is to fill form field with a **placeholder** like: `default: <value from default>`

### Steps To Reproduce

[playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJmaXJzdE5hbWUiLCJsYXN0TmFtZSJdLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaXJzdCBuYW1lIiwiZGVmYXVsdCI6IkNodWNrIn0sImxhc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ikxhc3QgbmFtZSJ9LCJhZ2UiOnsidHlwZSI6ImludGVnZXIiLCJ0aXRsZSI6IkFnZSJ9LCJiaW8iOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiQmlvIn0sInBhc3N3b3JkIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlBhc3N3b3JkIiwibWluTGVuZ3RoIjozfSwidGVsZXBob25lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRlbGVwaG9uZSIsIm1pbkxlbmd0aCI6MTB9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGggeWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlLCJzaG93RXJyb3JMaXN0IjoidG9wIn19)

**Comment by nickgros** [comment] 2023-02-06 23:55
Duplicate of #2980. We would be happy to review and accept a pull request that adds a feature to fix this behavior (in an opt-out fashion) in v5.

**Closed by nickgros** 2023-02-06 23:55 UTC
Labels: bug, needs triage
