### ISSUE TITLE
schema constants are not populated

### ISSUE THREAD

**Issue by Saulzi** [rjsf-team/react-jsonschema-form#1627] opened 2020-03-03 13:49 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Constants in schema are not pre populated

### Steps to Reproduce

create schema with property like below
                            "@type": {
                                "const": "Property"
                            }

#### Expected behavior

get read only value with value pre-populated

#### Actual behavior

I get a text box

### Version

master

**Comment by Saulzi** [comment] 2020-03-05 10:29
Please see my bigger PR for this

**Comment by epicfaace** [comment] 2020-03-16 14:10
This is a duplicate of #1241, but yes, would be good to have

**Closed by epicfaace** 2020-03-16 14:10 UTC
