### ISSUE TITLE
Use react-is for widget type check

### ISSUE THREAD

**Issue by anlesk** [rjsf-team/react-jsonschema-form#1209] opened 2019-03-06 16:58 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

Starting from **React 16.3.0** the component is not always a function, but could be an object if it was wrapped with `React.forwardRef`.

According to the guidelines, `react-is` should be used for type validation.
The proper way of doing that is simply call - `ReactIs.isValidElementType(Widget);`

The possible place to fix: [utils.js#L96](https://github.com/mozilla-services/react-jsonschema-form/blob/f9d4c63cac24146e522528d33eb04f465464e052/src/utils.js#L96)

### Steps to Reproduce

1. Define `DescriptionField` and wrap it with `React.forwardRef`
```
const DescriptionField = React.forwardRef((props, ref) => (
    <YourComponent {...props} ref={ref} />)
)
```
2. Define custom fields
```
const fields = { DescriptionField }
```
2. Pass fields to SchemaForm
```
<SchemaForm
   ...
   fields={fields}
   ...
/>
```
3. Observe in the console

> Uncaught Error: Unsupported widget definition: object

#### Expected behavior

Validation successfully passed.

#### Actual behavior

Validation is not passed, error is thrown.

### Version

    "react-jsonschema-form": "^1.0.3"

**Comment by epicfaace** [comment] 2019-03-16 21:12
@anlesk sounds good, can you make a PR?

**Comment by anlesk** [comment] 2019-03-19 11:10
Well, the proper fix would require dependencies to be switched to react>=16.3.

Until that happen - the proposed solution will cover ForwardedRef needs.

**Comment by epicfaace** [comment] 2019-03-28 12:55
@anlesk Sorry, I haven't really used React.ForwardedRef before. Do you mind linking to a jsfiddle in which you try to use React.ForwardedRef with react-jsonschema-form, so I can see what error is coming up and what exactly PR #1227 is fixing? Would appreciate it!

**Comment by epicfaace** [comment] 2019-05-24 01:19
@anlesk I've tried reproducing this in a jsfiddle but I don't get any issue: https://jsfiddle.net/f0dxpot9/3/

Am I missing something in the code?

**Comment by anlesk** [comment] 2019-05-28 13:13
@epicfaace aw, yeah. Seems that I've provided an incorrect input. This is only reproducible with widgets.

Check this one: https://jsfiddle.net/a4rqpj1d/9/

**Comment by lyleunderwood** [comment] 2020-01-29 04:09
I'm trying to use custom widgets with rjsf and I have a HOC that wraps my components with `React.forwardRef`. I seem to be getting the same error in the most recent version of rjsf.

I have updated the fiddle above to use the newest version of rjsf with this fix included. [It still produces the same error.](https://jsfiddle.net/anh5wfst/4/).

As far as I can tell, `ReactIs.isForwardRef` will check for _elements_ of `ForwardRef`s, it doesn't check for a component, which is the direct result of `React.forwardRef`.

**Comment by snirp** [comment] 2020-04-30 11:54
Same issue here for a custom widget wrapped in a (react-redux connect) HOC.

**Comment by epicfaace** [comment] 2020-04-30 13:13
> As far as I can tell, `ReactIs.isForwardRef` will check for _elements_ of `ForwardRef`s, it doesn't check for a component, which is the direct result of `React.forwardRef`.

Do you know if there is another utility within ReactIs that checks for the component?

**Comment by lyleunderwood** [comment] 2020-04-30 20:41
Well, that depends on what we're actually trying to do here. There is `ReactIs.isValidElementType`, which basically determines whether or not the given thing looks like it can be passed into `React.createElement`. That seems like it would be an improvement all around over the current solution, as far as I can tell.

**Comment by jonathanhawleypeters** [comment] 2020-04-30 22:06
After the previous fix was merged, @epicfaace asked:
> ...would you mind doing the same with getFieldComponent as well? thanks! mozilla-services/react-jsonschema-form:src/components/fields/SchemaField.js@98952b7#L34

[source](https://github.com/rjsf-team/react-jsonschema-form/pull/1227#issuecomment-497996840)

I opened a draft PR that replaces two checks with `ReactIs.isValidElementType`: [one in](https://github.com/rjsf-team/react-jsonschema-form/pull/1737/files#diff-db970a241b7e429a111e08ecff45d4bdR34) `getFieldComponent`, and [the other in](https://github.com/rjsf-team/react-jsonschema-form/pull/1737/files#diff-de7268713c4a06145c186712ff82211cR111) `getWidget`.

**Closed** 2022-05-15 02:10 UTC
Labels: bug, help wanted, wontfix
