### ISSUE TITLE
Crash when update to v5.17.0: util could not be found within the project or in these directories

### ISSUE THREAD

**Issue by thanhcuong1990** [rjsf-team/react-jsonschema-form#4080] opened 2024-02-05 04:36 UTC
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.17.0

### Current Behavior

Error: Unable to resolve module util from `app/node_modules/@rjsf/utils/dist/index.js`: util could not be found within the project or in these directories:
  `node_modules/@rjsf/utils/node_modules`

### Steps To Reproduce

update `@rjsf/core` and `@rjsf/utils` from version `5.16.1` to `5.17.0`. 

### Environment

```markdown
- OS: MacOS 14.3 
- Node: 18.19.0
- npm: 10.2.4
```

**Comment by areski** [comment] 2024-02-05 10:21
I'm getting the same issue as @thanhcuong1990 :
```
ERROR in ./node_modules/@rjsf/utils/lib/base64.js 17:40-55
Module not found: Error: Can't resolve 'util' in '/xxx/node_modules/@rjsf/utils/lib'
```
`util` is coming from node, not sure why this is failing [https://nodejs.org/docs/latest-v20.x/api/util.html#util]

**Comment by fcollonval** [comment] 2024-02-16 14:14
We are getting the same error in [JupyterLab](https://github.com/jupyterlab/jupyterlab/issues/15764). The issue is because we built a browser application and our bundler (webpack) does not know what to do with the NodeJS library import.

**Comment by fcollonval** [comment] 2024-02-16 14:14
Related PR: https://github.com/rjsf-team/react-jsonschema-form/pull/4034

**Comment by heath-freenome** [comment] 2024-02-16 20:29
@areski Oh wow, since this capability was really only added for the playground, we will be moving it out of `@rjsf/utils` in `5.17.1` sorry for the inconvenience. We should have this fix up within the week.

**Closed** 2024-02-19 13:47 UTC
Labels: bug, playground, p1, utils

**Comment by areski** [comment] 2024-02-19 14:11
Thanks a million @nickgros & @heath-freenome
