### ISSUE TITLE
populate default on UI but do not save them if untouched.

### ISSUE THREAD

**Issue by rjain-eightfold** [rjsf-team/react-jsonschema-form#3157] opened 2022-09-29 07:41 UTC
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

bootstrap-4

### Is your feature request related to a problem? Please describe.

the library is amazing. there is only one of my requirement which I am not able to achieve.

I understand that all the default are auto populated on the form by propagating from parent to child.
What I want to achieve is that I wan to only show the default values on the UI but do not want to save them.

USE CASE: I am using the same schema for multiple tenants.  and default specified in schema can also change (sometime).
So when the schema default change I do not want to edit the json for all the tenants if they have never touched those fields.

### Describe the solution you'd like

I am looking for an easier way to show defaults but not save default if the field is not manually touched.

if there is any best way to override this behaviour. or a code pointer which can refer, it will be a big help.

https://github.com/rjsf-team/react-jsonschema-form/blob/6e6c558a2bc4719c16ce644bc53e3feb4ce4e697/packages/utils/src/schema/getDefaultFormState.ts

### Describe alternatives you've considered

1. I tried removing all the defaults from schema before sending it to ui but that results in not knowing the defaults at all.
2. tried removing 'default' and add them to 'description' (which works fine for most cases but boolean and integer fields still look confusing and also propagation logic from parent to child will not work.)

**Comment by vsoni-eightfold** [comment] 2022-09-29 08:03
Yes, this will great to have.

**Comment by heath-freenome** [comment] 2022-12-23 16:37
@rjain-eightfold This is a duplicate of a requested feature in #2980

**Closed by heath-freenome** 2022-12-23 16:37 UTC
Labels: needs triage, feature
