### ISSUE TITLE
Issue is relate to #3769 regarding the array fields.

### ISSUE THREAD

**Issue by dilipsingh076** [rjsf-team/react-jsonschema-form#3776] opened 2023-07-19 11:08 UTC
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

material-ui

### What is your question?

Hello @heath-freenome sorry for delay but i think i am unable to tell you my problem here i am adding some screen shots please go through these screen shots. please re-open the https://github.com/rjsf-team/react-jsonschema-form/issues/3769.

Questions 
<img width="1389" alt="Screenshot 2023-07-17 at 12 01 07 PM" src="https
<img width="1390" alt="Screenshot 2023-07-17 at 12 00 40 PM" src="https://github.com/rjsf-team/react-jsonschema-form/assets/101004823/d5e4fc07-e0a3-48fa-b40e-4773ce1d2515">
://github.com/rjsf-team/react-jsonschema-form/assets/101004823/6b4bec9a-4c64-46e0-906a-47fc4a932e5b">

1.you can see in that screen shot there is a list of string json-schema is create so when i click on add icon you can see the another screen shots there items got added in ui but the label name of that item is listofstring-0* and after that when we add it's goes like that 1,2,3..... so on so i want that the label name start with 1 not from 0 so could you please help me in this? how i can do this?

**Comment by heath-freenome** [comment] 2023-07-20 18:20
Closing as duplicate of #3769

**Closed by heath-freenome** 2023-07-20 18:20 UTC
Labels: question
