### ISSUE TITLE
Editing widget type breaks the app

### ISSUE THREAD

**Issue by ForumT** [rjsf-team/react-jsonschema-form#1002] opened 2018-08-10 07:09 UTC
### Editing widget type breaks the app

I cloned the playground app and it works fine. However when i use the same with the latest react version, then the app breaks while you are editing the schema widget type.

### Steps to Reproduce

1. Clone the playground app..
2. Select any category like say simple and modify a widget from the UI schema like say age:
                  It is "ui:widget": "updown",
I delete updown and before I can type anything, the app breaks with the error:

      Uncaught Error: No widget "" for type "integer"

#### Expected behavior

The json should show invalid schema and not break the app.

#### Actual behavior

The app breaks with the error: Uncaught Error: No widget "" for type "integer"

### Version
React version 16.3 or higher.
React-json-schema-form: 1.0.4

 (Modifying just these did not break the app. Still mentioning just in case)
codemirror: ^5.39.2
react-codemirror2: ^5.1.0

**Comment by loganvolkers** [comment] 2018-08-28 19:11
I put together a SSCCE with these versions:

 - react@16.3.0
 - react-json-schema-form@1.0.4

It seems to work fine: https://codesandbox.io/s/93kmwl7n7p

I believe this is probably a problem in your environment. If there is another issue, feel free to bring it up.

Otherwise I suggest closing this issue.

**Comment by TomKrcmar** [comment] 2019-10-26 22:31
Can we reopen this? I'm having this issue in one of my projects.

I don't know what the codesandbox was trying to reproduce, as the original issue was with `ui:widget`. I've modified the codesandbox here:
https://codesandbox.io/s/charming-cannon-d29tk

Is this not supposed to be handled gracefully by `onError`?

**Comment by epicfaace** [comment] 2019-10-27 19:55
Sure. @TomKrcmar what behavior do you think should happen instead when a widget is invalid?

**Comment by TomKrcmar** [comment] 2019-10-28 03:36
@epicfaace I may not be familiar enough with React internals, but I did some debugging, it looks like `StringField` throws inside its render function due to `utils.getWidget` - The render function can be called synchronously by a change in state to some higher component, but placed in a call stack that skips my error boundary or even a manual call to `ReactDOM.render('Form', ...)` inside a try/catch.

Imagine components `A -> Boundary -> Form -> StringField` - When I call `A.setState`, StringField throws an error inside its call stack, which does not include Form or Boundary. From what I can tell, It skips my error handling because React queued it previously and rendered it in a beginWork loop triggered by the higher component A. It also doesn't come back in `Form.onError`.  I'm finding it nearly impossible to catch the error without registering a global error handler in index.html that calls `e.stopImmediatePropagation` and `e.preventDefault`.

I think this may be related:
https://stackoverflow.com/questions/46589819/disable-error-overlay-in-development-mode/47398520#47398520

React in development mode adds global error handlers that seem to ignore catching & handling, which may explain why the live playground demos don't throw?

**Comment by epicfaace** [comment] 2019-12-09 05:28
@TomKrcmar a more graceful way to handle it would be to do a similar thing to what we do when a schema has an unrecognized type -- see [this playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsidGl0bGUiOiJBIHJlZ2lzdHJhdGlvbiBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIGV4YW1wbGUuIiwidHlwZSI6ImFzZGFza2xkanNha2xkIiwicmVxdWlyZWQiOlsiZmlyc3ROYW1lIiwibGFzdE5hbWUiXSwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSIsImRlZmF1bHQiOiJDaHVjayJ9LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifSwiYWdlIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJBZ2UifSwiYmlvIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkJpbyJ9LCJwYXNzd29yZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJQYXNzd29yZCIsIm1pbkxlbmd0aCI6M30sInRlbGVwaG9uZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJUZWxlcGhvbmUiLCJtaW5MZW5ndGgiOjEwfX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==):

![image](https://user-images.githubusercontent.com/1689183/70409737-b14b1a00-1a01-11ea-908f-33fc1d11f795.png)

Might you be able to make a pull request that fixes this?

**Comment by grantzvolsky** [comment] 2021-08-09 01:53
@epicfaace The playground crashes upon typing `{"title": {}}` into the JSONSchema field.

**Comment by samj1912** [comment] 2022-08-26 20:05
For those facing an issue, this is what I ended up doing - 

create an error boundary like so - 


```js
import { Alert } from 'antd';
import * as React from 'react';

interface ErrorProps {
  data?: any;
}

interface ErrorState {
  error: Error | null;
  data: any;
}

export class ErrorBoundary extends React.Component<ErrorProps, ErrorState> {
  constructor(props) {
    super(props);
    this.state = { error: null, data: null };
  }

  static getDerivedStateFromError(error: Error) {
    // Update state so the next render will show the fallback UI.
    return { error: error };
  }

  static getDerivedStateFromProps(props: ErrorProps, state: ErrorState) {
    // We use this data field to ensure that the error state is reset whenever the input data changes.
    // This allows us to have "live updates" to the underlying child components instead of always being
    // stuck in the error state.
    if (props?.data !== state?.data) {
      return { error: null, errorInfo: null, data: props?.data };
    }
    return null;
  }

  render() {
    if (this.state.error) {
      return (
        <Alert
          message={`${this.state.error && this.state.error.toString()}`}
          type='error'
        />
      );
    }
    return this.props.children;
  }
}
```

You can then use the error boundary like so - 

```js
// using ui schema and schema as the data field so that the error boundary is "reset" every time these two are changed
<ErrorBoundary data={JSON.stringify({ uiSchema, schema })}><JSONSchemaForm .../></ErrorBoundary>
```

**Closed** 2022-10-03 16:25 UTC
Labels: bug, playground
