### ISSUE TITLE
Custom title styling does not work for string field titles.

### ISSUE THREAD

**Issue by hrvojebusic** [rjsf-team/react-jsonschema-form#1687] opened 2020-04-05 11:38 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Custom titles](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#custom-titles) does not work for titles/labels on string fields. Moreover, it seems to only work on titles/labels for object fields.

### Steps to Reproduce

1. Copy the `CustomTitleField` example as provided by the documentation.
2. Adjust the `CustomTitleField` to make changes more apparent (e.g. change the color of the text).
3. Copy the `Simple` example in the [playground](https://rjsf-team.github.io/react-jsonschema-form/).
4. Observe that changes are only applied to titles for `Object` fields.

#### Expected behavior

`CustomTitleField` should apply changes to titles of all types of fields.

### Version

1.8.1

**Comment by timkindberg** [comment] 2020-09-14 17:04
Yeah we wanted to add a custom TitleWithTooltipField and I was surprised how there is a consistent DescriptionField but not a TitleField...

**Comment by snirotem** [comment] 2021-01-13 12:37
Hi, any workarounds for this issue ?
i'm using only string fields (since Object types do not allow custom widgets) and cannot customize the titles...

**Comment by timkindberg** [comment] 2021-01-15 23:52
Object types do allow custom "widgets" but instead they are called "fields". https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/#custom-field-components

**Comment by newt10** [comment] 2021-09-03 22:44
@hrvojebusic I believe you can play around with the title field styling if you provide a field template, array field template and object field template independently. You can create these by looking at the field template implementations.

https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/bootstrap-4/src/ObjectFieldTemplate/ObjectFieldTemplate.tsx

Which theme are you trying with?

**Comment by ksbrar** [comment] 2021-12-02 00:28
Ran into this issue as well, quite annoying. I see the PR to address this is stale; in the meantime I think the current behavior (or lackthereof) should at least be documented.

**Comment by heath-freenome** [comment] 2023-03-05 03:25
I am very sure that this issue was fixed in the 5.x release. If not, please reopen with a reproducible test case

**Closed by heath-freenome** 2023-03-05 03:25 UTC
Labels: bug, labelOrDescription
