### ISSUE TITLE
Multi-select breaks validations

### ISSUE THREAD

**Issue by jkarjala** [rjsf-team/react-jsonschema-form#2565] opened 2021-09-25 15:21 UTC
### Description

Selecting an item in a multi-select JSON schema breaks validation of the form.

### Steps to Reproduce

1. Paste the following schema to playground, or use the [playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsiJGlkIjoiaHR0cDovL3NjaGVtYS5qcGt3YXJlLmNvbS9waXBlbGluZS5zY2hlbWEuanNvbiIsIiRzY2hlbWEiOiJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA3L3NjaGVtYSMiLCJkZWZpbml0aW9ucyI6eyJHcm91cCI6eyJvbmVPZiI6W3siY29uc3QiOiJBIiwidGl0bGUiOiJHcm91cCBBbGZhIn0seyJjb25zdCI6IkIiLCJ0aXRsZSI6Ikdyb3VwIEJldGEifSx7ImNvbnN0IjoiQyIsInRpdGxlIjoiR3JvdXAgQ2Vsc2l1cyJ9XX19LCJwcm9wZXJ0aWVzIjp7InRpbGVyLm91dFByZWZpeCI6eyJkZXNjcmlwdGlvbiI6IktleSBwcmVmaXggaW4gdGhlIG91dHB1dCBsYXllciIsInRpdGxlIjoiUHJlZml4IGZvciBvdXRwdXQga2V5cyIsInR5cGUiOiJzdHJpbmciLCJwYXR0ZXJuIjoiXlthLXpBLVowLTkvLl8tXSskIiwibWluTGVuZ3RoIjozfSwibXVsdGkiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJNdWx0aS1zZWxlY3QgZnJvbSBncm91cHMiLCJpdGVtcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9Hcm91cCJ9LCJ1bmlxdWVJdGVtcyI6dHJ1ZX19LCJyZXF1aXJlZCI6WyJ0aWxlci5vdXRQcmVmaXgiXSwidGl0bGUiOiJTZXR0aW5ncyIsInR5cGUiOiJvYmplY3QifSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIn0sImxhc3ROYW1lIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==):
```
{
    "$id": "http://schema.jpkware.com/pipeline.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
      "Group": {
        "oneOf": [
         {
           "const": "A",
           "title": "Group Alfa"
         },
         {
            "const": "B",
            "title": "Group Beta"
         },
         {
            "const": "C",
            "title": "Group Celsius"
         }
        ]
      }
    },
    "properties": {
      "tiler.outPrefix": {
        "description": "Key prefix in the output layer",
        "title": "Prefix for output keys",
        "type": "string",
        "pattern": "^[a-zA-Z0-9/._-]+$",
        "minLength": 3
      },
      "multi": {
        "type": "array",
        "title": "Multi-select from groups",
        "items": {
          "$ref": "#/definitions/Group"
        },
        "uniqueItems": true
      }
    },
    "required": ["tiler.outPrefix"],
    "title": "Settings",
    "type": "object"
  }
```

2. Turn on "Live validation"
3. Observe property validation error for tiler.outPrefix
3. Select an item from the Multi-select list
4. Observe that all errors disappear

If Live validation is off, then Submit after Multi-selection shows some error, but the tiler.outPrefix error is lost.

#### Expected behavior

Validation errors for all properties should be shown also after selecting items from Multi-select

#### Actual behavior

All validation errors disappear

### Version

Whatever you are running in github... I am using "@rjsf/core": "^3.1.0" from typescript.

**Comment by heath-freenome** [comment] 2023-05-22 21:28
Even this [example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJtdWx0aSI6W10sInRpbGVyLm91dFByZWZpeCI6ImRmcyJ9LCJzY2hlbWEiOnsiJGlkIjoiaHR0cDovL3NjaGVtYS5qcGt3YXJlLmNvbS9waXBlbGluZS5zY2hlbWEuanNvbiIsImRlZmluaXRpb25zIjp7Ikdyb3VwIjp7Im9uZU9mIjpbeyJjb25zdCI6IkEiLCJ0aXRsZSI6Ikdyb3VwIEFsZmEifSx7ImNvbnN0IjoiQiIsInRpdGxlIjoiR3JvdXAgQmV0YSJ9LHsiY29uc3QiOiJDIiwidGl0bGUiOiJHcm91cCBDZWxzaXVzIn1dfX0sInByb3BlcnRpZXMiOnsidGlsZXIub3V0UHJlZml4Ijp7ImRlc2NyaXB0aW9uIjoiS2V5IHByZWZpeCBpbiB0aGUgb3V0cHV0IGxheWVyIiwidGl0bGUiOiJQcmVmaXggZm9yIG91dHB1dCBrZXlzIiwidHlwZSI6InN0cmluZyIsInBhdHRlcm4iOiJeW2EtekEtWjAtOS8uXy1dKyQiLCJtaW5MZW5ndGgiOjN9LCJtdWx0aSI6eyJ0eXBlIjoiYXJyYXkiLCJ0aXRsZSI6Ik11bHRpLXNlbGVjdCBmcm9tIGdyb3VwcyIsIml0ZW1zIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL0dyb3VwIn0sInVuaXF1ZUl0ZW1zIjp0cnVlLCJtaW5JdGVtcyI6MX19LCJyZXF1aXJlZCI6WyJ0aWxlci5vdXRQcmVmaXgiLCJtdWx0aSJdLCJ0aXRsZSI6IlNldHRpbmdzIiwidHlwZSI6Im9iamVjdCJ9LCJ1aVNjaGVtYSI6eyJtdWx0aSI6eyJ1aTp3aWRnZXQiOiJjaGVja2JveGVzIn19LCJ0aGVtZSI6Im1hdGVyaWFsLXVpLTUiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIn0sInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19) has an issue... It seems like AJV doesn't validate this situation properly

**Comment by heath-freenome** [comment] 2023-05-22 21:50
@jkarjala I cannot reproduce your issue anymore with the latest 5.x version. Closing

**Closed by heath-freenome** 2023-05-22 21:50 UTC
Labels: bug
