### ISSUE TITLE
uiSchema doesn't work for schema dependency.

### ISSUE THREAD

**Issue by videni** [rjsf-team/react-jsonschema-form#1649] opened 2020-03-14 13:41 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

uiSchema doesn't work for schema dependency.

### Steps to Reproduce

```
{
    "formData": {
        "rules": [
            {
                "type": "item_total",
                "configuration": {
                    "amount": 25
                }
            }
        ]
    },
    "schema": {
        "title": "promotion",
        "type": "object",
        "properties": {
            "rules": {
                "type": "array",
                "title": "Rules",
                "items": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "enum": [
                                "customer_group",
                                "nth_order",
                                "item_total"
                            ],
                            "enumNames": [
                                "Customer group",
                                "Nth order",
                                "Total"
                            ],
                            "type": [
                                "string",
                                "null"
                            ],
                            "title": "Type",
                            "attr": {
                                "data-form-collection": "update"
                            }
                        }
                    },
                    "required": [
                        "type"
                    ],
                    "dependencies": {
                        "type": {
                            "oneOf": [
                                {
                                    "properties": {
                                        "type": {
                                            "enum": [
                                                "customer_group"
                                            ]
                                        },
                                        "configuration": {
                                            "title": "Parameters",
                                            "type": "object",
                                            "properties": {
                                                "groupId": {
                                                    "enum": [
                                                        "1"
                                                    ],
                                                    "enumNames": [
                                                        "VIP"
                                                    ],
                                                    "type": [
                                                        "string",
                                                        "null"
                                                    ],
                                                    "title": "Customer group"
                                                }
                                            },
                                            "required": [
                                                "groupId"
                                            ]
                                        }
                                    }
                                },
                                {
                                    "properties": {
                                        "type": {
                                            "enum": [
                                                "nth_order"
                                            ]
                                        },
                                        "configuration": {
                                            "title": "Parameters",
                                            "type": "object",
                                            "properties": {
                                                "nth": {
                                                    "type": "integer",
                                                    "title": "Order count"
                                                }
                                            },
                                            "required": [
                                                "nth"
                                            ]
                                        }
                                    }
                                },
                                {
                                    "properties": {
                                        "type": {
                                            "enum": [
                                                "item_total"
                                            ]
                                        },
                                        "configuration": {
                                            "title": "Parameters",
                                            "type": "object",
                                            "properties": {
                                                "amount": {
                                                    "type": "number",
                                                    "minimum": 0,
                                                    "title": "Price",
                                                    "ui": {
                                                        "options": {
                                                            "divisor": 100,
                                                            "currency": "CNY",
                                                            "grouping": false
                                                        }
                                                    }
                                                }
                                            },
                                            "required": [
                                                "amount"
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "required": [
            "rules"
        ]
    },
    "uiSchema": {
        "rules": {
            "items": {
                "configuration": {
                    "customer_group": {
                        "ui:order": [
                            "groupId"
                        ]
                    },
                    "nth_order": {
                        "nth": {
                            "ui:widget": "updown",
                            "ui:min": 0
                        },
                        "ui:order": [
                            "nth"
                        ]
                    },
                    "item_total": {
                        "amount": {
                            "ui:widget": "money",
                            "ui:min": 0,
                            "ui:step": 0.01,
                            "ui:options": {
                                "currencySymbol": "￥"
                            }
                        },
                        "ui:order": [
                            "amount"
                        ]
                    }
                }
            }
        }
    }
}
```

**Comment by epicfaace** [comment] 2020-03-14 15:58
uiSchema doesn't support dependencies. Closing this as a duplicate of #701.

**Closed by epicfaace** 2020-03-14 15:58 UTC

**Comment by videni** [comment] 2020-03-15 01:00
@epicfaace , why is the current solution? the progress to that issue is quite slow. I really don't want to wait for another year.

**Comment by epicfaace** [comment] 2020-03-16 14:08
@videni Note that uiSchema _does_ work for schema dependencies based on a fixed key, but it just can't dynamically change based on which dependency was selected. See, for example, [this example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsImEiOiJhcyJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYSI6eyJ0eXBlIjoic3RyaW5nIn19LCJkZXBlbmRlbmNpZXMiOnsiYSI6eyJwcm9wZXJ0aWVzIjp7ImIiOnsidHlwZSI6ImJvb2xlYW4ifX19fX0sInVpU2NoZW1hIjp7ImIiOnsidWk6d2lkZ2V0Ijoic2VsZWN0In19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=).

Does that help?

**Comment by videni** [comment] 2020-03-19 13:03
@epicfaace , the example json above is `oneOf ` dependency, not the one  in your example, does `oneOf` schema dependeny also work?
