### ISSUE TITLE
Nested properties validation

### ISSUE THREAD

**Issue by jv00** [rjsf-team/react-jsonschema-form#3391] opened 2023-01-20 17:46 UTC
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.0.0-beta.15

### Current Behavior

With v4, the schema used to validate nested properties inside of dependencies (e.g. oneOf) where the fields had no interaction. We have recently used v5 and in our example we have address which has several required properties such as "Town", on submit, "Town" would get validated, however in newer version (v.5) only address as a whole is validated, that is until one of the properties are set.

### Expected Behavior

I went through the documentation and can't find any material on this. I have inspected v4 and in the schema example, address would be sent to {} where as in v5 address is not set to anything

### Steps To Reproduce

1. Using rjfs [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJoYXZlQWRkcmVzcyI6dHJ1ZX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiaGF2ZUFkZHJlc3MiXSwicHJvcGVydGllcyI6eyJoYXZlQWRkcmVzcyI6eyJ0eXBlIjoiYm9vbGVhbiIsInRpdGxlIjoiRG8geW91IGhhdmUgYW4gYWRkcmVzcz8ifX0sImRlcGVuZGVuY2llcyI6eyJoYXZlQWRkcmVzcyI6eyJvbmVPZiI6W3sicmVxdWlyZWQiOlsiaGF2ZUFkZHJlc3MiLCJhZGRyZXNzIl0sInByb3BlcnRpZXMiOnsiYWRkcmVzcyI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJXaGF0IGlzIHlvdXIgaG9tZSBhZGRyZXNzIiwicmVxdWlyZWQiOlsiYWRkcmVzc09uZSIsInRvd24iLCJwb3N0Y29kZSJdLCJwcm9wZXJ0aWVzIjp7InRvd24iOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiVG93biAvIENpdHkifSwiY291bnRyeSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJDb3VudHJ5In0sInBvc3Rjb2RlIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlBvc3Rjb2RlIn0sImFkZHJlc3NPbmUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiQWRkcmVzcyAxIn0sImFkZHJlc3NUd28iOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiQWRkcmVzcyAyIn19fSwiaGF2ZUFkZHJlc3MiOnsiZW51bSI6W3RydWVdLCJ0eXBlIjoiYm9vbGVhbiJ9fX1dfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

2. Setting schema to:

`{
   "type":"object",
   "required":[
      "haveAddress"
   ],
   "properties":{
      "haveAddress":{
         "type":"boolean",
         "title":"Do you have an address?"
      }
   },
   "dependencies":{
      "haveAddress":{
         "oneOf":[
            {
               "required":[
                  "haveAddress",
                  "address"
               ],
               "properties":{
                  "address":{
                     "type":"object",
                     "title":"What is your home address",
                     "required":[
                        "addressOne",
                        "town",
                        "postcode"
                     ],
                     "properties":{
                        "town":{
                           "type":"string",
                           "title":"Town / City"
                        },
                        "country":{
                           "type":"string",
                           "title":"Country"
                        },
                        "postcode":{
                           "type":"string",
                           "title":"Postcode"
                        },
                        "addressOne":{
                           "type":"string",
                           "title":"Address 1"
                        },
                        "addressTwo":{
                           "type":"string",
                           "title":"Address 2"
                        }
                     }
                  },
                  "haveAddress":{
                     "enum":[
                        true
                     ],
                     "type":"boolean"
                  }
               }
            }
         ]
      }
   }
}`

3. Check "Do you have an address?"
4. Hit "Submit"
5. Notice only "address" property as a whole is validated, rather than individual nested properties.

Using similar schema, which has default value set for "Town", will validate nested properties, somewhat as you would expect it to happen by default.

`{
   "type":"object",
   "required":[
      "haveAddress"
   ],
   "properties":{
      "haveAddress":{
         "type":"boolean",
         "title":"Do you have an address?"
      }
   },
   "dependencies":{
      "haveAddress":{
         "oneOf":[
            {
               "required":[
                  "haveAddress",
                  "address"
               ],
               "properties":{
                  "address":{
                     "type":"object",
                     "title":"What is your home address",
                     "required":[
                        "addressOne",
                        "town",
                        "postcode"
                     ],
                     "properties":{
                        "town":{
                           "type":"string",
                           "title":"Town / City",
                           "default":null
                        },
                        "country":{
                           "type":"string",
                           "title":"Country"
                        },
                        "postcode":{
                           "type":"string",
                           "title":"Postcode"
                        },
                        "addressOne":{
                           "type":"string",
                           "title":"Address 1"
                        },
                        "addressTwo":{
                           "type":"string",
                           "title":"Address 2"
                        }
                     }
                  },
                  "haveAddress":{
                     "enum":[
                        true
                     ],
                     "type":"boolean"
                  }
               }
            }
         ]
      }
   }
}`

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by nickgros** [comment] 2023-01-27 16:18
Duplicate of #3305

**Closed** 2023-01-27 17:29 UTC
Labels: bug, defaults
