### ISSUE TITLE
Add additionalProperties support at material-ui theme

### ISSUE THREAD

**Issue by joaogsousa** [rjsf-team/react-jsonschema-form#1793] opened 2020-06-03 16:12 UTC
Material UI theme does not support additionalProperties correctly, i.e., the same way the default theme does.

If you browse to the Additional Properties section of https://rjsf-team.github.io/react-jsonschema-form/ and use the materialUI theme you can see that it is not possible to add custom key-value properties as expected.

**Comment by stanlemon** [comment] 2020-06-14 22:10
This is a duplicate of #1724

**Comment by epicfaace** [comment] 2020-06-14 22:24
Thanks @stanlemon

**Closed by epicfaace** 2020-06-14 22:24 UTC
