### ISSUE TITLE
fetch or populate a dropdown based on selection from other dropdown

### ISSUE THREAD

**Issue by eyesmoker** [rjsf-team/react-jsonschema-form#1472] opened 2019-09-25 06:37 UTC
Say, I have 2 dropdowns (A and B). Dropdown A values are 1 and 2. Dropdown B should be populated based on value selected from Dropdown A.  Say, I have a mapping (1 -> ABC, 1->BCD, 2-> CDE, 2->DEF)
When I choose value "1"  from dropdown A, I would like to populate second dropdown B with values (ABC and BCD). 
It is very easy to define dropdown values using definitions concept. I have looked at dependencies examples (like showing billing address based on credit card field) but I haven't seen a example that I am looking for. Any pointers are greatly appreciated.

**Comment by eyesmoker** [comment] 2019-09-29 15:09
Any update? This is very critical functionality that will help us choose whether we can use the react jsonschema framework.

**Comment by KKS1** [comment] 2019-10-11 05:31
@eyesmoker I would suggest hooking into form changeHandler. Abstract the formData from here and pass it to your custom auto calculator function which can have logics such as "formData.fieldB = formData.fieldA;". In your case mentioned above, basically a map will be linking these fields in autoCalculate function, where keys are in fieldA and corresponding array based values in fieldB

**Comment by epicfaace** [comment] 2019-10-22 23:27
@eyesmoker sorry for the delay. There is no way to encode in the JSON schema how it will change in response to data. However, as @KKS1 mentioned, you can store the schema in the state and dynamically change it during the `onChange` handler of the form. Here's an example (although the fiddle seems to be currently broken, you can see from the code what it's doing): https://jsfiddle.net/69z2wepo/88541/

**Comment by epicfaace** [comment] 2019-10-22 23:30
actually @eyesmoker I was wrong above -- there _is_ a way to do this using dependencies. See [this playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhIjp7InR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIjEiLCIyIl19fSwiZGVwZW5kZW5jaWVzIjp7ImEiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiYSI6eyJjb25zdCI6IjEifSwiYiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJBQkMiLCJCQ0QiXX19fSx7InByb3BlcnRpZXMiOnsiYSI6eyJjb25zdCI6IjIifSwiYiI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJDREUiLCJERUYiXX19fV19fX0sInVpU2NoZW1hIjp7fSwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjp0cnVlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19) for how to do it.

**Comment by bharadhwaj-g** [comment] 2019-10-29 09:39
@epicfaace @KKS1 
I'm also looking for similar kind of functionality, but a lit bit of extra mile i.e 
[Playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjb21wbGlhbmNlRXh0cmFMZXR0ZXJzIjoyLCJjb21wbGlhbmNlQ29udGFjdENhbXBhaWduMSI6IkFmdGVyIE5PRSIsImNvbXBsaWFuY2VDb250YWN0Q2FtcGFpZ24yIjoiQWZ0ZXIgTk9FIiwiY29tcGxpYW5jZUNvbnRhY3RDYW1wYWlnbjMiOiJBZnRlciBOT0UiLCJjb21wbGlhbmNlQ29udGFjdENhbXBhaWducyI6M30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJjb21wbGlhbmNlRXh0cmFMZXR0ZXJzIjp7InR5cGUiOiJudW1iZXIiLCJ0aXRsZSI6Ik51bWJlciBvZiBleHRyYSBsZXR0ZXJzIChOUEVWcykiLCJtaW4iOjEsIm1heCI6MywibWluaW11bSI6MSwibWF4aW11bSI6MywiZGVmYXVsdCI6MX0sImNvbXBsaWFuY2VDb250YWN0Q2FtcGFpZ25zIjp7InR5cGUiOiJudW1iZXIiLCJ0aXRsZSI6Ik51bWJlciBvZiBjb250YWN0IGNhbXBhaWducyIsIm1pbiI6MCwibWF4IjozLCJtaW5pbXVtIjowLCJtYXhpbXVtIjozfX0sImRlcGVuZGVuY2llcyI6eyJpc0NvbXBsaWFuY2VCYWxhbmNlVGhyZXNob2xkIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7ImlzQ29tcGxpYW5jZUJhbGFuY2VUaHJlc2hvbGQiOnsiY29uc3QiOnRydWV9LCJjb21wbGlhbmNlVGhyZXNob2xkQmFsYW5jZU1pbiI6eyJ0eXBlIjoibnVtYmVyIiwidGl0bGUiOiJNaW46IiwiZGVzY3JpcHRpb24iOiJUaHJlc2hvbGQgYmFsYW5jZSJ9LCJjb21wbGlhbmNlVGhyZXNob2xkQmFsYW5jZU1heCI6eyJ0eXBlIjoibnVtYmVyIiwidGl0bGUiOiJNYXg6In19fV19LCJjb21wbGlhbmNlQ29udGFjdENhbXBhaWducyI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJjb21wbGlhbmNlQ29udGFjdENhbXBhaWducyI6eyJjb25zdCI6MX0sImNvbXBsaWFuY2VDb250YWN0Q2FtcGFpZ24xIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IldoZW4gc2hvdWxkIGNvbnRhY3QgY2FtcGFpZ24gMSBzdGFydD8iLCJlbnVtIjpbIkFmdGVyIE5PRSIsIkFmdGVyIE5QVkUxIl0sImRlZmF1bHQiOiJBZnRlciBOT0UifSwiY29tcGxpYW5jZUNvbnRhY3RDYW1wYWlnbkF0dGVtcHRzIjp7InR5cGUiOiJudW1iZXIiLCJ0aXRsZSI6Ik51bWJlciBvZiBhdHRlbXB0cyBpbiBhIGNhbXBhaWduIn19fSx7InByb3BlcnRpZXMiOnsiY29tcGxpYW5jZUNvbnRhY3RDYW1wYWlnbnMiOnsiY29uc3QiOjJ9LCJjb21wbGlhbmNlQ29udGFjdENhbXBhaWduMSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJXaGVuIHNob3VsZCBjb250YWN0IGNhbXBhaWduIDEgc3RhcnQ/IiwiZW51bSI6WyJBZnRlciBOT0UiLCJBZnRlciBOUFZFMSIsIkFmdGVyIE5QVkUyIl0sImRlZmF1bHQiOiJBZnRlciBOT0UifSwiY29tcGxpYW5jZUNvbnRhY3RDYW1wYWlnbjIiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiV2hlbiBzaG91bGQgY29udGFjdCBjYW1wYWlnbiAyIHN0YXJ0PyIsImVudW0iOlsiQWZ0ZXIgTk9FIiwiQWZ0ZXIgTlBWRTEiLCJBZnRlciBOUFZFMiJdLCJkZWZhdWx0IjoiQWZ0ZXIgTk9FIn19fSx7InByb3BlcnRpZXMiOnsiY29tcGxpYW5jZUNvbnRhY3RDYW1wYWlnbnMiOnsiY29uc3QiOjN9LCJjb21wbGlhbmNlQ29udGFjdENhbXBhaWduMSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJXaGVuIHNob3VsZCBjb250YWN0IGNhbXBhaWduIDEgc3RhcnQ/IiwiZW51bSI6WyJBZnRlciBOT0UiLCJBZnRlciBOUFZFMSIsIkFmdGVyIE5QVkUyIiwiQWZ0ZXIgTlBWRTMiXSwiZGVmYXVsdCI6IkFmdGVyIE5PRSJ9LCJjb21wbGlhbmNlQ29udGFjdENhbXBhaWduMiI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJXaGVuIHNob3VsZCBjb250YWN0IGNhbXBhaWduIDIgc3RhcnQ/IiwiZW51bSI6WyJBZnRlciBOT0UiLCJBZnRlciBOUFZFMSIsIkFmdGVyIE5QVkUyIiwiQWZ0ZXIgTlBWRTMiXSwiZGVmYXVsdCI6IkFmdGVyIE5PRSJ9LCJjb21wbGlhbmNlQ29udGFjdENhbXBhaWduMyI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJXaGVuIHNob3VsZCBjb250YWN0IGNhbXBhaWduIDMgc3RhcnQ/IiwiZW51bSI6WyJBZnRlciBOT0UiLCJBZnRlciBOUFZFMSIsIkFmdGVyIE5QVkUyIiwiQWZ0ZXIgTlBWRTMiXSwiZGVmYXVsdCI6IkFmdGVyIE5PRSJ9fX1dfX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOnRydWUsImxpdmVPbWl0IjpmYWxzZX19)

Here I've two fields
- Number of extra letters (NPEVs)
- Number of contact campaigns

Based on these two fields I've other fields which are dynamic i.e 
- When should contact campaign 1 start? and this an  dropdon field, which options are dependent on Number of extra letters. 

**For example**
- Number of extra letters = 2 (options)
- Number of contact campaigns = 3  (fields)
Then we should display three fields 
- When should contact campaign 1 start?
- When should contact campaign 2 start?
- When should contact campaign 3 start?
and each field is an dropdown which should have options After (NPVE1 and After NPVE2) these options are depends on **Number of extra letters selected**

So could you please help how to achieve this, I've tried onchange hanlder as well in that case its able to achieve partially but the problem is if the field is already render, then its not updating it options (Because I'm not storing the formData in store)

**Comment by KKS1** [comment] 2019-10-31 05:07
Hi @bharadhwaj-g , one idea that can help while using onChangeHandler approach in your case, is to "have a hidden widget that stores the dropdown options under formData". That way, as formData for this hidden field updates, it will re-render the options in those dropdowns. Later, you can omit the extra data, with the omitExtraData flag, before submission.

**Comment by bharadhwaj-g** [comment] 2019-10-31 06:06
@KKS1 , could you please provide me a playground.

**Comment by KKS1** [comment] 2019-11-01 05:45
Hi @bharadhwaj-g , created an end-to-end flow in sandbox for your use case, plus for anyone looking to add dynamic properties in the form.
https://codesandbox.io/s/rjs-playground-y8er4

Hope it helps, cheers!

-Kanwaljeet Kalra

**Comment by epicfaace** [comment] 2019-11-29 03:33
Thanks @KKS1 .

I believe the original issue has been resolved so I'm closing this. Feel free to open up another issue if there are any other problems though!

**Closed by epicfaace** 2019-11-29 03:33 UTC
Labels: question
