### ISSUE TITLE
Dependencies are not rendered when nested within additionalProperties

### ISSUE THREAD

**Issue by VassilIordanov** [rjsf-team/react-jsonschema-form#1575] opened 2020-01-26 11:02 UTC
### Prerequisites

- [x] I have read the [documentation]
- [x] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I'm providing a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0Ijp7InR5cGUiOiJ0eXBlMiIsImRlcGVuZGVuY3kiOiJjb3JyZWN0IGRlcGVuZGVuY3kifSwibmV3S2V5Ijp7InR5cGUiOiJ0eXBlMiIsImRlcGVuZGVuY3kiOiJtaXNzaW5nIGRlcGVuZGVuY3kifX0sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJjdXN0b21GaWVsZCI6eyJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsidHlwZSJdLCJwcm9wZXJ0aWVzIjp7InR5cGUiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsidHlwZTEiLCJ0eXBlMiJdfX0sImRlcGVuZGVuY2llcyI6eyJ0eXBlIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7InR5cGUiOnsiZW51bSI6WyJ0eXBlMSJdfX19LHsicHJvcGVydGllcyI6eyJ0eXBlIjp7ImVudW0iOlsidHlwZTIiXX0sImRlcGVuZGVuY3kiOnsidHlwZSI6InN0cmluZyJ9fSwicmVxdWlyZWQiOlsiZGVwZW5kZW5jeSJdfV19fX19LCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXN0Ijp7IiRyZWYiOiIjL2RlZmluaXRpb25zL2N1c3RvbUZpZWxkIn19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9jdXN0b21GaWVsZCJ9fSwidWlTY2hlbWEiOnsidGVzdCI6eyJ0eXBlIjp7InVpOnRpdGxlIjoiU2VsZWN0IFR5cGUifSwiZGVwZW5kZW5jeSI6eyJ1aTp0aXRsZSI6IkNvbmRpdGlvbmFsIERlcGVuZW5jeSJ9fX0sImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) demonstrating the issue.

### Description

Dependencies are not rendered when nested within `additionalProperties`

### Steps to Reproduce

1. Create a definition containing dependency fields. For example:
```
  "definitions": {
    "customField": {
      "type": "object",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "type1",
            "type2"
          ]
        }
      },
      "dependencies": {
        "type": {
          "oneOf": [
            {
              "properties": {
                "type": {
                  "enum": [
                    "type1"
                  ]
                }
              }
            },
            {
              "properties": {
                "type": {
                  "enum": [
                    "type2"
                  ]
                },
                "dependency": {
                  "type": "string"
                }
              },
              "required": [
                "dependency"
              ]
            }
          ]
        }
      }
    }
  }
```
2. Create a property referencing the definition 
```
  "properties": {
    "test": {
      "$ref": "#/definitions/customField"
    }
  }
```
3. Create additional `additionalProperties` referencing the definition
```
  "additionalProperties": {
    "$ref": "#/definitions/customField"
  }
```

#### Expected behavior

The dependency property `dependency` to be available in both the UI for the test field and any newly created additional property

#### Actual behavior

Dependency is visible within the `test` field UI, but is not visible in any additional property UI.

### Version

playground

**Comment by epicfaace** [comment] 2020-02-13 17:34
Perhaps the issue is that in `retrieveSchema`, `stubExistingAdditionalProperties` is called _after_ dependencies are resolved in `resolveSchema`. Perhaps one way to fix this would be to call `resolveSchema` one more time after calling `stubExistingAdditionalProperties`? Do you want to try this fix out in a PR @VassilIordanov ?

https://github.com/rjsf-team/react-jsonschema-form/blob/e673a9097e587f28ffe7d82647ff70ba33908bcb/packages/core/src/utils.js#L657-L682

**Closed** 2022-05-01 17:28 UTC
Labels: bug, wontfix
