### ISSUE TITLE
Add support for if/then/else from JSON Schema Draft 7

### ISSUE THREAD

**Issue by mfulton26** [rjsf-team/react-jsonschema-form#885] opened 2018-04-06 22:18 UTC
I recently learned about draft 7 and it's support for if/then/else which seems much easier to reason with than schema dependencies and oneOf (which we added support for not too long ago).

Should there be any concerns about pulling in draft 7 keywords? Does/Can rjsf even use ajv in draft 7 mode? Even if it doesn't/can't (yet) is there any concern about adding support for if/then/else?

Thank you.

**Comment by glasserc** [comment] 2018-04-13 17:10
I think we should feel free to use it if we can come up with a good UX for it.

**Comment by tarun29061990** [comment] 2019-12-02 12:30
Hey any update on this?

**Comment by epicfaace** [comment] 2020-02-13 17:22
closing as duplicate of #850

**Closed by epicfaace** 2020-02-13 17:22 UTC
