### ISSUE TITLE
UI Schema does not follow $refs

### ISSUE THREAD

**Issue by Saulzi** [rjsf-team/react-jsonschema-form#1635] opened 2020-03-05 11:54 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The UI Schema does not follow refs, this basically means that complex schemas i.e. with many references are effectively useless, 

ajv will successfully validate a schema which has additional properties, I am not sure what other libs do when they see unknowns i.e. ui

I propose that as part of V2 we bring ui schema as an augmentation to json schema rather than having a fragile side thing which does not work in more complicated scenarios, as it could potentially be part of V2,

I have a hack which will allow both seperate ui schema and schema to work which is basically a case of modifying SchemaField as follows

``` js
function SchemaFieldRender(props) {
  const {
    uiSchema:_,
    formData,
    errorSchema,
    idPrefix,
    name,
    onKeyChange,
    onDropPropertyClick,
    required,
    registry = getDefaultRegistry(),
    wasPropertyKeyModified = false,
  } = props;

  const { rootSchema, fields, formContext } = registry;

  var schema = retrieveSchema(props.schema, rootSchema, formData);
  var uiSchema = {...props.uiSchema};
  let ui = schema.ui;
  
  // Hack UI Schema in from schema
  if (ui)
  {
    for (let key in ui)
    {
      uiSchema["ui:" + key] = ui[key];
    }
  }


  const FieldTemplate = uiSchema["ui:FieldTemplate"] || registry.FieldTemplate || DefaultTemplate;
  let idSchema = props.idSchema;
  ....
```

**Comment by epicfaace** [comment] 2020-03-07 22:51
Good point, this is a duplicate of #701. Would be great to have a PR that allows uiSchema to be embedded within the schema.

**Closed by epicfaace** 2020-03-07 22:51 UTC
