### ISSUE TITLE
[Semantic-ui] Field descriptions are not getting custom description rendering

### ISSUE THREAD

**Issue by ssbyoung** [rjsf-team/react-jsonschema-form#2363] opened 2021-05-05 21:24 UTC
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

This is the SSCCE that shows this behavior.
[rjsf-description-issue.zip](https://github.com/rjsf-team/react-jsonschema-form/files/6430313/rjsf-description-issue.zip)

### Description

When providing a custom `DescriptionField` to the SemanticUI version of the form, it does not get parsed on field level descriptions.

### Steps to Reproduce

1. Use the @rjfs/semantic-ui form and pass in fields with a `DescriptionField`

#### Expected behavior

I would expect the description to go through my custom field.

#### Actual behavior

![rjsf bug](https://user-images.githubusercontent.com/23528141/117211116-39338000-adbe-11eb-9b41-182cb8455c81.PNG)

### Version

2.5.1 for both @rjsf/core and @rjsf/semantic-ui

**Comment by trebor** [comment] 2021-05-24 21:52
i also see the same problem in material-UI:

```js
import Form from "@rjsf/material-ui";
```

both `<TitleField />` and `<DescriptionField />` are properly used as i would expect at the top level of the from, but not in any of the form fields as they do work with `@rjsf/core`.

**Comment by ssbyoung** [comment] 2021-05-26 15:02
@trebor I suspect that this affects all the themes, but I didn't check.

**Comment by JonSilver** [comment] 2021-05-28 13:10
Duplicate of #2219

**Comment by ssbyoung** [comment] 2021-06-29 21:28
I've fixed this in https://github.com/rjsf-team/react-jsonschema-form/pull/2451

I feel like the other themes are doing similar things where they are just displaying raw text and not using the registry to get the proper description component.

**Comment by heath-freenome** [comment] 2022-08-28 17:29
Fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)

**Closed by heath-freenome** 2022-08-28 17:29 UTC
Labels: bug, labelOrDescription
