### ISSUE TITLE
[React v17][Rjsf v4] Dependency in RJSF is missing @mui/core and if resolve caused crash by @emotion/styled

### ISSUE THREAD

**Issue by c0ncentus** [rjsf-team/react-jsonschema-form#2747] opened 2022-03-04 21:06 UTC
### Prerequisites

- [V] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [V] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I upgrade Rjsf 3.21 to the latest (4.0.1)

i had error in console => @mui/material is missing
and then npm i --save @mui/material and got a my entire app crash 

I uninstall, delete package.lock but still this issue. maybe I should try to delete all rjfs and reInstall all

[Description of the bug or feature]
### Steps to Reproduce

1. [First Step] cra react app 
2. [Second Step] install rjsf v4.0.1 
3. [and so on...]  
![image](https://user-images.githubusercontent.com/25374826/156842430-381c9fd9-2e0e-437e-bab0-8a51ee3f40bf.png)
4. then install @mui/material and got @emotion/styled crash error because missing.

#### Expected behavior
Don't add another dependencieS packageS. 

#### Actual behavior

![image](https://user-images.githubusercontent.com/25374826/156840030-a599e0ee-cab9-45ae-a5e3-c3692768013f.png)

[What actually happened]
Got error in console.log and if complete then the app have crash error  
### Version 
React V17, node v17.6 npm v7.6.1
Dependencies
    "@material-ui/core": "^4.12.3",
    "@material-ui/icons": "^4.11.2",
    "@rjsf/core": "^4.0.1",
    "@rjsf/material-ui": "^4.0.1",

**Comment by heath-freenome** [comment] 2022-03-08 16:49
Duplicate of #2721

**Closed** 2022-03-08 16:50 UTC
