### ISSUE TITLE
Bug in native datetime widget in playground

### ISSUE THREAD

**Issue by kwakwaversal** [rjsf-team/react-jsonschema-form#878] opened 2018-03-29 10:19 UTC
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

The DateTimeWidget does not allow manually editing the year (and sometimes day/month) via the keyboard once a valid date has been set.

### Steps to Reproduce

1. Open [playground](https://mozilla-services.github.io/react-jsonschema-form/) and go to "Date & time" tab (alternatively see this [fiddle with just the datetime](https://jsfiddle.net/f2y3fq7L/271/)
2. Fill out the native datetime widget with a valid date
3. In the year type `0` (which will reset the year to `0000`), then try typing in `2018` as the year. It keeps getting reset so you can't get past entering the first two digits (if you're *really* quick).

#### Expected behavior

I'd expect the input element to allow you to type in the year (month, day etc.).

#### Actual behavior

You cannot enter more than 2 digits before it resets itself.

### Version

* Whatever version is in the playground.
* Chrome: Version 64.0.3282.186 (Official Build) (64-bit)
* Timezone: BST

**Comment by edi9999** [comment] 2018-04-06 05:59
Indeed, I can reproduce this issue.

Do you think you can find a fix and create a PR ?

**Comment by kwakwaversal** [comment] 2018-04-09 14:40
@edi9999 I tried to fix it but couldn't narrow it down after littering a few debug statements around in the `DateTimeWidget` and elsewhere.

If you could point me in the right direction I might be able to fix it. I can only assume that the "onChange" firing after every keystroke the widget it attempting to validate the value but fails, ultimately resetting it. I don't know the internals of RJF enough to start doing things like firing delayed `onChange` events.

**Comment by r4j4h** [comment] 2018-04-13 05:42
Hi, I was albe to reproduce this issue as well and I found the root cause in Chrome. I found a fix that works there, but am unsure if it is the right path.

**Comment by heath-freenome** [comment] 2023-02-23 00:56
After playing around with this in the current playground, this appears to be fixed. Closing

**Closed by heath-freenome** 2023-02-23 00:56 UTC
Labels: bug, core
