### ISSUE TITLE
Optional object with required fields in react-jsonschema-form

### ISSUE THREAD

**Issue by davidMcneil** [rjsf-team/react-jsonschema-form#675] opened 2017-08-22 15:12 UTC
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Given a json schema like the one below, the react-jsonschema-form validator essentially requires both shipping_address and billing_address even though the billing_address is not listed as required. This is because the address type requires all three of its properties. How can I make the billing_address optional?

    {
      "definitions": {
        "address": {
          "type": "object",
          "properties": {
            "street_address": {
              "type": "string"
            },
            "city": {
              "type": "string"
            },
            "state": {
              "type": "string"
            }
          },
          "required": [
            "street_address",
            "city",
            "state"
          ]
        }
      },
      "type": "object",
      "properties": {
        "billing_address": {
          "title": "Billing address",
          "$ref": "#/definitions/address"
        },
        "shipping_address": {
          "title": "Shipping address",
          "$ref": "#/definitions/address"
        }
      },
      "required": [
        "shipping_address"
      ]
    }
### Steps to Reproduce

Here is a [link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJiaWxsaW5nX2FkZHJlc3MiOnsic3RyZWV0X2FkZHJlc3MiOiIyMSwgSnVtcCBTdHJlZXQiLCJjaXR5IjoiQmFiZWwiLCJzdGF0ZSI6Ik5ldmVybGFuZCJ9LCJzaGlwcGluZ19hZGRyZXNzIjp7fSwidHJlZSI6eyJuYW1lIjoicm9vdCIsImNoaWxkcmVuIjpbeyJuYW1lIjoibGVhZiJ9XX19LCJzY2hlbWEiOnsiZGVmaW5pdGlvbnMiOnsiYWRkcmVzcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJzdHJlZXRfYWRkcmVzcyI6eyJ0eXBlIjoic3RyaW5nIn0sImNpdHkiOnsidHlwZSI6InN0cmluZyJ9LCJzdGF0ZSI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJzdHJlZXRfYWRkcmVzcyIsImNpdHkiLCJzdGF0ZSJdfX0sInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImJpbGxpbmdfYWRkcmVzcyI6eyJ0aXRsZSI6IkJpbGxpbmcgYWRkcmVzcyIsIiRyZWYiOiIjL2RlZmluaXRpb25zL2FkZHJlc3MifSwic2hpcHBpbmdfYWRkcmVzcyI6eyJ0aXRsZSI6IlNoaXBwaW5nIGFkZHJlc3MiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9hZGRyZXNzIn19LCJyZXF1aXJlZCI6WyJiaWxsaW5nX2FkZHJlc3MiXX0sInVpU2NoZW1hIjp7InVpOm9yZGVyIjpbInNoaXBwaW5nX2FkZHJlc3MiLCJiaWxsaW5nX2FkZHJlc3MiXX19) to the react-jsonschema-form playground.

#### Expected behavior

It seems that react-jsonschema-form should simply no submit billing_address if not all of its address properties are filled in. 

#### Actual behavior

The form validator prevents the form from being submitted. 

### Version

0.49.0

**Comment by n1k0** [comment] 2017-08-23 09:29
I'm surprised with this behavior too, and the *jsonschema* lib is not at fault here as validating raw data works just as expected. We may be altering the schema in some way, which is bad.

**Comment by gdbassett** [comment] 2017-10-23 16:58
Has this fix been merged?  If not, is there a target for merging it?  My org has started using the plugin but are getting lots of invalid data due to turning off validation due to required fields within non-required objects.

**Comment by davidMcneil** [comment] 2017-10-23 18:44
This has not been merged. There are a few outstanding issues that need to be worked through. You can see the discussion at the merge request (https://github.com/mozilla-services/react-jsonschema-form/pull/682). Unfortunately, I do not have time to cleanup the issues that need to be worked through in the immediate future. I am sure that if these issues were addressed the fix would be quickly merged.

**Comment by christianblos** [comment] 2018-05-09 06:26
Any news on this one?

**Comment by christianblos** [comment] 2018-05-09 11:04
If someone else comes across this issue and can not wait for a real fix, you can extend the Form component and override the validate function. Here's an example in Typescript:

```typescript
class ReactJsonSchemaForm<T> extends Form<T> {
    validate(formData: any, schema: any) {
        formData = removeOptionalEmptyValues(formData, this.props.schema);
        //@ts-ignore
        return super.validate(formData, schema);
    }
}
```

don't forget to call `removeOptionalEmptyValues()` on `onSubmit` as well.

**Comment by epicfaace** [comment] 2019-03-16 21:27
[Playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJiaWxsaW5nX2FkZHJlc3MiOnsic3RyZWV0X2FkZHJlc3MiOiJhc2QiLCJjaXR5IjoiQmFiZWwiLCJzdGF0ZSI6Ik5ldmVybGFuZCJ9LCJzaGlwcGluZ19hZGRyZXNzIjp7fSwidHJlZSI6eyJuYW1lIjoicm9vdCIsImNoaWxkcmVuIjpbeyJuYW1lIjoibGVhZiJ9XX19LCJzY2hlbWEiOnsiZGVmaW5pdGlvbnMiOnsiYWRkcmVzcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJzdHJlZXRfYWRkcmVzcyI6eyJ0eXBlIjoic3RyaW5nIn0sImNpdHkiOnsidHlwZSI6InN0cmluZyJ9LCJzdGF0ZSI6eyJ0eXBlIjoic3RyaW5nIn19LCJyZXF1aXJlZCI6WyJzdHJlZXRfYWRkcmVzcyIsImNpdHkiLCJzdGF0ZSJdfX0sInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImJpbGxpbmdfYWRkcmVzcyI6eyJ0aXRsZSI6IkJpbGxpbmcgYWRkcmVzcyIsIiRyZWYiOiIjL2RlZmluaXRpb25zL2FkZHJlc3MifSwic2hpcHBpbmdfYWRkcmVzcyI6eyJ0aXRsZSI6IlNoaXBwaW5nIGFkZHJlc3MiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9hZGRyZXNzIn19LCJyZXF1aXJlZCI6WyJiaWxsaW5nX2FkZHJlc3MiXX0sInVpU2NoZW1hIjp7InVpOm9yZGVyIjpbInNoaXBwaW5nX2FkZHJlc3MiLCJiaWxsaW5nX2FkZHJlc3MiXX19)

Part of the problem here is that 1) when all the shipping address fields are set to be blank, shipping_address is set to `{}` in the formData -- `shipping_address` does not disappear altogether.
And given this schema:
```
{
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": [
        "street_address",
        "city",
        "state"
      ]
    }
  },
  "type": "object",
  "properties": {
    "billing_address": {
      "title": "Billing address",
      "$ref": "#/definitions/address"
    },
    "shipping_address": {
      "title": "Shipping address",
      "$ref": "#/definitions/address"
    }
  },
  "required": [
    "billing_address"
  ]
}
```

The following schema [is not valid](https://jsfiddle.net/epicfaace/veq13p5x/):
```
{
  "billing_address": {
    "street_address": "asd",
    "city": "Babel",
    "state": "Neverland"
  },
  "shipping_address": {},
  "tree": {
    "name": "root",
    "children": [
      {
        "name": "leaf"
      }
    ]
  }
}
```

Whereas only the _following_ schema [is valid](https://jsfiddle.net/epicfaace/L4ec5vrk/):
```
{
  "billing_address": {
    "street_address": "asd",
    "city": "Babel",
    "state": "Neverland"
  },
  "tree": {
    "name": "root",
    "children": [
      {
        "name": "leaf"
      }
    ]
  }
}
```

And the second problem is the same as mentioned above; even when the key `shipping_address` is removed from the formData, the fields still highlight as red / required.

**Comment by psehgal** [comment] 2020-01-02 21:24
Any updates with this? I am running into the same issue.

**Comment by afernandez8** [comment] 2020-04-22 19:22
Hello, any updates with this? I am running into the same issue.

**Comment by vonElfvin** [comment] 2020-10-09 09:19
A workaround I went with:
```
const formatInitialFormData = (
  initialFormData: Record<string, unknown>,
  schema: JSONSchema7,
): Record<string, unknown> => {
  const properties = schema.properties!
  const formData = { ...initialFormData }
  Object.entries(properties).forEach((property) => {
    const key = property[0]
    const value = property[1] as JSONSchema7
    formData[key] = initialFormData[key] ?? value?.default ?? undefined
  })
  return formData
}
```

Consumed by:
`formatInitialFormData(initialFormData ?? {}, schema)`

It is not perfect but does the trick for me.

**Comment by daverck** [comment] 2021-08-17 06:46
> Hello, any updates with this? I am running into the same issue. And i can't fix with this: [#675 (comment)](https://github.com/rjsf-team/react-jsonschema-form/issues/675#issuecomment-387703564)

Try with the following :

```js
export class ReactJSONSchemaForm<T> extends Form<T> {

  constructor(props: any){
    super(props)
    let oldValidate = this.validate;
    this.validate = (
      formData: T,
      schema?: FormProps<T>['schema'],
      additionalMetaSchemas?: FormProps<T>['additionalMetaSchemas'],
      customFormats?: FormProps<T>['customFormats'],
      ): {errors: AjvError[], errorSchema: ErrorSchema} => {  
        
        let fixedFormData = trimEmptyValues(formData)
        return oldValidate.call(this, fixedFormData, schema)
      }
  }
}
```

**Comment by iamkhalidbashir** [comment] 2021-11-10 04:49
Running into this issue as well

**Comment by Rozamo** [comment] 2022-12-13 13:45
Till this gets fixed from the code side you can try making some changes to your schema if it fits your requirement. You can remove the `required` property from the `address` definition and use JSON Schema `dependencies` whenever referenced. The following schema works for me. It's a bit tedious but does the job.

```
{
    "definitions":
    {
        "address":
        {
            "type": "object",
            "properties":
            {
                "street_address":
                {
                    "type": "string"
                },
                "city":
                {
                    "type": "string"
                },
                "state":
                {
                    "type": "string"
                }
            }
        }
    },
    "type": "object",
    "properties":
    {
        "billing_address":
        {
            "title": "Billing address",
            "$ref": "#/definitions/address",
            "dependencies":
            {
                "street_address":
                {
                    "required":
                    [
                        "city",
                        "state"
                    ]
                },
                "city":
                {
                    "required":
                    [
                        "street_address",
                        "state"
                    ]
                },
                "state":
                {
                    "required":
                    [
                        "city",
                        "street_address"
                    ]
                }
            }
        },
        "shipping_address":
        {
            "title": "Shipping address",
            "$ref": "#/definitions/address",
            "required":
            [
                "street_address",
                "city",
                "state"
            ]
        }
    },
    "required":
    [
        "shipping_address"
    ]
}
```

**Closed** 2023-02-06 18:20 UTC
Labels: bug, help wanted

**Comment by bluisana** [comment] 2023-03-29 19:48
6 years later and it looks like this bug still exists.  I have a large amount of complex schemas that can't be modified using "depencies" or other conditionals.  It is expected behavior of a schema that objects properties are not required if the object itself isn't required.  I am testing this with the following simply schema. Is there any fix for this that I am missing that doesn't involve changing the actual schemas? 

`schema: {
            type: 'object',
            properties: {
              person: {
                type: 'object',
                properties: {
                  id: {
                    type: 'string',
                  },
                  name: {
                    type: 'string',
                  },
                },
                required: ['name'],
              },
            },
            example: '{}',
          }`

**Comment by heath-freenome** [comment] 2023-03-31 17:41
@bluisana So it seems we probably need to add a switch to enable/disable the noHtml5Validate in the playground and then we would see this issue show up?

**Comment by fdecollibus** [comment] 2024-03-20 20:02
I  am facing the same issue

**Comment by heath-freenome** [comment] 2024-03-21 19:10
@fdecollibus Are you using the latest 5.x release and set `noHtml5Validate` to false on the `Form`?

**Comment by jason-karuza-memorang** [comment] 2025-03-20 22:42
The same is occurring for me still with 5.24.8. I have a pretty large/complex schema that has $refs to other sections, and the $refs themselves are not required within the section they are referenced, but when loaded and rendered the required properties within those $refs are treated as required even though the $ref section itself is optional.

<details>
<summary>Example schema:</summary>

```json

{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Multiple Choice Assessment Item Schema",
	"description": "Simplified schema for multiple choice assessment items with a single correct answer",
	"type": "object",
	"properties": {
		"id": {
			"type": "string",
			"description": "Unique identifier for the assessment item"
		},
		"type": {
			"type": "string",
			"description": "Type of assessment item (always 'item' for this schema)",
			"enum": ["item"],
			"default": "item"
		},
		"version": {
			"type": "string",
			"description": "Version of the assessment item"
		},
		"content": {
			"type": "object",
			"description": "Content of the assessment item",
			"properties": {
				"stimulus": {
					"type": "object",
					"description": "The stimulus content (context) for the question",
					"properties": {
						"content": {
							"type": "string",
							"description": "HTML content for the stimulus"
						},
						"mediaResources": {
							"type": "array",
							"description": "Media resources used in this stimulus",
							"items": {
								"$ref": "#/definitions/mediaResource"
							}
						}
					},
					"required": ["content"]
				},
				"prompt": {
					"type": "object",
					"description": "The question prompt",
					"properties": {
						"content": {
							"type": "string",
							"description": "HTML content for the prompt (the question text)"
						},
						"mediaResources": {
							"type": "array",
							"description": "Media resources used in this prompt",
							"items": {
								"$ref": "#/definitions/mediaResource"
							}
						}
					},
					"required": ["content"]
				},
				"interactions": {
					"type": "array",
					"description": "Interactions for this assessment item (only one for multiple choice)",
					"minItems": 1,
					"maxItems": 1,
					"items": {
						"type": "object",
						"description": "Multiple choice interaction",
						"properties": {
							"id": {
								"type": "string",
								"description": "Unique identifier for this interaction"
							},
							"type": {
								"type": "string",
								"enum": ["choice"],
								"description": "Type identifier for choice interaction"
							},
							"responseIdentifier": {
								"type": "string",
								"description": "Identifier used to reference this interaction's response"
							},
							"shuffle": {
								"type": "boolean",
								"description": "Whether to shuffle the choices",
								"default": false
							},
							"maxChoices": {
								"type": "integer",
								"description": "Maximum number of choices that can be selected",
								"enum": [1],
								"default": 1
							},
							"minChoices": {
								"type": "integer",
								"description": "Minimum number of choices that must be selected",
								"enum": [1],
								"default": 1
							},
							"choices": {
								"type": "array",
								"description": "Available choices",
								"items": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string",
											"description": "Unique identifier for this choice"
										},
										"content": {
											"type": "string",
											"description": "HTML content for this choice"
										},
										"mediaResources": {
											"type": "array",
											"description": "Media resources used in this choice",
											"items": {
												"$ref": "#/definitions/mediaResource"
											}
										},
										"isCorrect": {
											"type": "boolean",
											"description": "Whether this choice is the correct answer",
											"default": false
										},
										"feedback": {
											"$ref": "#/definitions/feedback"
										}
									},
									"required": ["id", "content", "isCorrect"]
								},
								"minItems": 2
							},
							"scoring": {
								"$ref": "#/definitions/responseMapping"
							},
							"feedback": {
								"$ref": "#/definitions/feedback"
							}
						},
						"required": ["id", "type", "responseIdentifier", "choices"]
					}
				}
			},
			"required": ["prompt", "interactions"]
		},
		"metadata": {
			"type": "object",
			"description": "Metadata for the assessment item",
			"properties": {
				"title": {
					"type": "string",
					"description": "Title of the assessment item"
				},
				"subject": {
					"type": "string",
					"description": "Subject area of the assessment item"
				},
				"gradeLevel": {
					"type": "string",
					"description": "Grade level for which the assessment item is appropriate"
				},
				"difficulty": {
					"type": "string",
					"enum": ["easy", "medium", "hard"],
					"description": "Difficulty level of the assessment item"
				},
				"tags": {
					"type": "array",
					"description": "Tags associated with the assessment item",
					"items": {
						"type": "string"
					}
				},
				"author": {
					"type": "string",
					"description": "Author of the assessment item"
				},
				"createdDate": {
					"type": "string",
					"format": "date-time",
					"description": "Date when the assessment item was created"
				},
				"modifiedDate": {
					"type": "string",
					"format": "date-time",
					"description": "Date when the assessment item was last modified"
				}
			},
			"required": ["title"]
		},
		"scoring": {
			"type": "object",
			"description": "Scoring configuration for the assessment item",
			"properties": {
				"scoreType": {
					"type": "string",
					"description": "Type of scoring to apply",
					"enum": ["binary", "partial", "custom"],
					"default": "binary"
				},
				"maxScore": {
					"type": "number",
					"description": "Maximum score for this item",
					"minimum": 0,
					"default": 1
				},
				"penalty": {
					"type": "number",
					"description": "Penalty for incorrect responses",
					"default": 0
				},
				"responseMappings": {
					"type": "array",
					"description": "Mappings from responses to scores",
					"items": {
						"$ref": "#/definitions/responseMapping"
					}
				},
				"customScoringFunction": {
					"type": "string",
					"description": "Custom function for scoring (JavaScript)"
				}
			},
			"required": ["maxScore"]
		},
		"feedback": {
			"$ref": "#/definitions/feedback"
		}
	},
	"definitions": {
		"mediaResource": {
			"type": "object",
			"description": "Media resource used in the assessment item",
			"properties": {
				"id": {
					"type": "string",
					"description": "Unique identifier for this media resource"
				},
				"type": {
					"type": "string",
					"enum": ["image", "audio", "video"],
					"description": "Type of media resource"
				},
				"url": {
					"type": "string",
					"description": "URL of the media resource"
				},
				"alt": {
					"type": "string",
					"description": "Alternative text for accessibility"
				},
				"width": {
					"type": "integer",
					"description": "Width of the media resource (for images and videos)"
				},
				"height": {
					"type": "integer",
					"description": "Height of the media resource (for images and videos)"
				}
			},
			"required": ["id", "type", "url"]
		},
		"responseMapping": {
			"type": "object",
			"description": "Mapping from a response to a score",
			"properties": {
				"responseIdentifier": {
					"type": "string",
					"description": "Identifier of the interaction this mapping applies to"
				},
				"responseMatcher": {
					"type": "object",
					"description": "Criteria for matching responses",
					"properties": {
						"type": {
							"type": "string",
							"enum": ["exact", "subset", "superset", "custom"],
							"description": "Type of response matching",
							"default": "exact"
						},
						"value": {
							"oneOf": [
								{
									"type": "string"
								},
								{
									"type": "array",
									"items": {
										"type": "string"
									}
								}
							],
							"description": "Value to match against the response"
						},
						"customMatcher": {
							"type": "string",
							"description": "Custom function for matching responses (JavaScript)"
						}
					},
					"required": ["type", "value"]
				},
				"score": {
					"type": "number",
					"description": "Score to assign if the response matches",
					"minimum": 0
				}
			},
			"required": ["responseIdentifier", "responseMatcher", "score"]
		},
		"feedback": {
			"type": "object",
			"description": "Feedback to provide to the user",
			"properties": {
				"general": {
					"type": "object",
					"description": "General feedback",
					"properties": {
						"content": {
							"type": "string",
							"description": "HTML content for the feedback"
						},
						"mediaResources": {
							"type": "array",
							"description": "Media resources used in this feedback",
							"items": {
								"$ref": "#/definitions/mediaResource"
							}
						}
					},
					"required": ["content"]
				},
				"correct": {
					"type": "object",
					"description": "Feedback for correct responses",
					"properties": {
						"content": {
							"type": "string",
							"description": "HTML content for the feedback"
						},
						"mediaResources": {
							"type": "array",
							"description": "Media resources used in this feedback",
							"items": {
								"$ref": "#/definitions/mediaResource"
							}
						}
					},
					"required": ["content"]
				},
				"incorrect": {
					"type": "object",
					"description": "Feedback for incorrect responses",
					"properties": {
						"content": {
							"type": "string",
							"description": "HTML content for the feedback"
						},
						"mediaResources": {
							"type": "array",
							"description": "Media resources used in this feedback",
							"items": {
								"$ref": "#/definitions/mediaResource"
							}
						}
					},
					"required": ["content"]
				},
				"solution": {
					"type": "object",
					"description": "Solution explanation",
					"properties": {
						"content": {
							"type": "string",
							"description": "HTML content explaining the solution"
						},
						"mediaResources": {
							"type": "array",
							"description": "Media resources used in this solution explanation",
							"items": {
								"$ref": "#/definitions/mediaResource"
							}
						}
					},
					"required": ["content"]
				}
			}
		}
	},
	"required": ["id", "version", "type", "content"]
}

```
</details>
