### ISSUE TITLE
Schema is valid but ui would not be generated

### ISSUE THREAD

**Issue by SyntaxTalksToMe** [rjsf-team/react-jsonschema-form#4049] opened 2024-01-18 14:34 UTC
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

all

### What is your question?

Good day ladies and gentleman,

I have a question: The schema down below is valid. A lot of different sources say that. But the ui would net be generated. Can say me, why is it?

`
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "type" : "object",
    "patternProperties" : {
      "^[0-9A-Za-z\\.-]*$": {
        "required" : [
          "USE CASE"
        ],
        "type" : "object",
        "properties" : {
          "USE CASE" : {
            "type" : "object",
            "patternProperties" : {
              "^.* (delivery|service).*$": {
                "patternProperties" : {
                  "^(EITHER|EITHER IF|IF|OR|OR IF)$": {
                    "type" : "object"
                  },
                  "^(YOU MUST|YOU MUST NOT)$": {
                    "type" : [
                      "string",
                      "array",
                      "object"
                    ]
                  }
                },
                "additionalProperties" : false
              }
            },
            "additionalProperties" : false
          },
          "COMPATIBILITY" : {
            "type" : [
              "string",
              "array"
            ]
          },
          "DEPENDING COMPATIBILITY" : {
            "type" : [
              "string",
              "array"
            ]
          },
          "INCOMPATIBILITY" : {
            "type" : [
              "string",
              "array"
            ]
          },
          "COPYLEFT CLAUSE" : {
            "type" : "string"
          },
          "PATENT HINTS" : {
            "type" : "string"
          }
        },
        "additionalProperties" : false
      }
    },
    "additionalProperties" : false
  }
`

**Comment by magaton** [comment] 2024-01-18 15:05
It doesn't seem complete

**Comment by SyntaxTalksToMe** [comment] 2024-01-19 11:23
the square bracket was missing at the end. But it was there. So the problem still exists. But perhaps you could back up your statement with more information

**Comment by magaton** [comment] 2024-01-19 11:38
I think patternProperties are not supported in this library.
See this [issue](https://github.com/rjsf-team/react-jsonschema-form/issues/1944)

**Comment by heath-freenome** [comment] 2024-01-26 20:38
This is a duplicate of #1944. @SyntaxTalksToMe Sorry that capability has never been implemented. Are you willing to try? Also, closing as a duplicate

**Closed by heath-freenome** 2024-01-26 20:38 UTC
Labels: question, needs triage
