### ISSUE TITLE
Cannot change property value with liveOmit and omitExtraData for arrays of objects and conditionality

### ISSUE THREAD

**Issue by anya92** [rjsf-team/react-jsonschema-form#4109] opened 2024-02-28 08:08 UTC
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

I have a problem when trying to change property values using "liveOmit" and "omitExtraData". This is the JSON schema I use:

```json
{
  "title": "Schema",
  "type": "object",
  "properties": {
    "array_of_objects": {
      "title": "Array of Objects",
      "type": "array",
      "items": {
        "$ref": "#/definitions/myArrayOfObjects"
      },
      "minItems": 1
    }
  },
  "definitions": {
    "myArrayOfObjects": {
      "title": "Array Item",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "type": "string"
        },
        "booleanProperty": {
          "title": "Boolean Property",
          "default": true,
          "type": "boolean"
        }
      },
      "if": {
        "properties": {
          "booleanProperty": {
            "const": true
          }
        }
      },
      "then": {
        "properties": {
          "otherProperty": {
            "title": "Other Property",
            "type": "string",
            "enum": [
              "Hello",
              "World"
            ]
          }
        },
        "required": [
          "otherProperty"
        ]
      },
      "required": [
        "name"
      ]
    }
  }
}
```

### Expected Behavior

It should be possible to change the `otherProperty` value.

### Steps To Reproduce

1. Go to the [rjsf playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhcnJheV9vZl9vYmplY3RzIjpbeyJib29sZWFuUHJvcGVydHkiOnRydWV9XX0sInNjaGVtYSI6eyJ0aXRsZSI6IlNjaGVtYSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImFycmF5X29mX29iamVjdHMiOnsidGl0bGUiOiJBcnJheSBvZiBPYmplY3RzIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvbXlBcnJheU9mT2JqZWN0cyJ9LCJtaW5JdGVtcyI6MX19LCJkZWZpbml0aW9ucyI6eyJteUFycmF5T2ZPYmplY3RzIjp7InRpdGxlIjoiQXJyYXkgSXRlbSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5hbWUiOnsidGl0bGUiOiJOYW1lIiwidHlwZSI6InN0cmluZyJ9LCJib29sZWFuUHJvcGVydHkiOnsidGl0bGUiOiJCb29sZWFuIFByb3BlcnR5IiwiZGVmYXVsdCI6dHJ1ZSwidHlwZSI6ImJvb2xlYW4ifX0sImlmIjp7InByb3BlcnRpZXMiOnsiYm9vbGVhblByb3BlcnR5Ijp7ImNvbnN0Ijp0cnVlfX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsib3RoZXJQcm9wZXJ0eSI6eyJ0aXRsZSI6Ik90aGVyIFByb3BlcnR5IiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiSGVsbG8iLCJXb3JsZCJdfX0sInJlcXVpcmVkIjpbIm90aGVyUHJvcGVydHkiXX0sInJlcXVpcmVkIjpbIm5hbWUiXX19fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6eyJwb3B1bGF0ZSI6InBvcHVsYXRlIiwibWVyZ2VFeHRyYURlZmF1bHRzIjpmYWxzZX0sImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9LCJsaXZlT21pdCI6dHJ1ZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZVZhbGlkYXRlIjp0cnVlfX0=)
2. `liveOmit` and `omitExtraData` are already turned on, `liveValidation` is also turned on to see that the condition is valid 
3. try to change value of `Other Property` - nothing happens

### Environment

```markdown
- OS: macOS 14.2.1
- Node: 18.14.2
- npm: 9.5.0
```

### Anything else?

It works in my project which uses version 5.12.1. But I can't update the package after it stopped working.
I already addressed this issue in [#3909](https://github.com/rjsf-team/react-jsonschema-form/issues/3909).

**Comment by heath-freenome** [comment] 2024-03-01 20:49
@anya92 It seems like when you turn off `omitExtraData` everything works fine. This is a duplicate of #2720, although your use-case is much clearer. Is this something you are will to try to fix?

**Comment by anya92** [comment] 2024-03-04 05:45
@heath-freenome Thank you for the response. I did notice that turning off `omitExtraData` resolves the issue, but in my project, it needs to be turned on. Unfortunately, I'm not very familiar with the codebase, so making a quick fix might be challenging for me.

**Comment by heath-freenome** [comment] 2024-03-08 20:48
@anya92 I started out not being very familiar with the codebase either. Most of the code you want to look at is in the `Form` class in `@rjsf/core`. Feel free to reach out if you have any questions. Thanks

**Comment by anya92** [comment] 2024-03-12 06:34
@heath-freenome I checked the changes in the package and I'm pretty sure my schema stopped working after updating `retrieveSchema()` in version 5.13.1 and this function started resolving references. In the version I'm currently using, $refs are not resolved.

But even if I manually got rid of `$ref` and my schema looks like this:

```json
{
  "title": "Schema",
  "type": "object",
  "properties": {
    "array_of_objects": {
      "title": "Array of Objects",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "type": "string"
        },
        "booleanProperty": {
          "title": "Boolean Property",
          "default": true,
          "type": "boolean"
        }
      },
      "if": {
        "properties": {
          "booleanProperty": {
            "const": true
          }
        }
      },
      "then": {
        "properties": {
          "otherProperty": {
            "title": "Other Property",
            "type": "string",
            "enum": [
              "Hello",
              "World"
            ]
          }
        },
        "required": [
          "otherProperty"
        ]
      }
    }
  }
}
```

The issue still exists ([playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhcnJheV9vZl9vYmplY3RzIjp7ImJvb2xlYW5Qcm9wZXJ0eSI6dHJ1ZX19LCJzY2hlbWEiOnsidGl0bGUiOiJTY2hlbWEiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhcnJheV9vZl9vYmplY3RzIjp7InRpdGxlIjoiQXJyYXkgb2YgT2JqZWN0cyIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5hbWUiOnsidGl0bGUiOiJOYW1lIiwidHlwZSI6InN0cmluZyJ9LCJib29sZWFuUHJvcGVydHkiOnsidGl0bGUiOiJCb29sZWFuIFByb3BlcnR5IiwiZGVmYXVsdCI6dHJ1ZSwidHlwZSI6ImJvb2xlYW4ifX0sImlmIjp7InByb3BlcnRpZXMiOnsiYm9vbGVhblByb3BlcnR5Ijp7ImNvbnN0Ijp0cnVlfX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsib3RoZXJQcm9wZXJ0eSI6eyJ0aXRsZSI6Ik90aGVyIFByb3BlcnR5IiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiSGVsbG8iLCJXb3JsZCJdfX0sInJlcXVpcmVkIjpbIm90aGVyUHJvcGVydHkiXX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOnsicG9wdWxhdGUiOiJwb3B1bGF0ZSIsIm1lcmdlRXh0cmFEZWZhdWx0cyI6ZmFsc2V9LCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9LCJsaXZlT21pdCI6dHJ1ZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZVZhbGlkYXRlIjp0cnVlfX0=)).

You may notice that the `if...then` section is nested inside `array_of_objects`. If I move it up, the form will work and the data will not be deleted ([playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhcnJheV9vZl9vYmplY3RzIjp7ImJvb2xlYW5Qcm9wZXJ0eSI6dHJ1ZX19LCJzY2hlbWEiOnsidGl0bGUiOiJTY2hlbWEiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJhcnJheV9vZl9vYmplY3RzIjp7InRpdGxlIjoiQXJyYXkgb2YgT2JqZWN0cyIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5hbWUiOnsidGl0bGUiOiJOYW1lIiwidHlwZSI6InN0cmluZyJ9LCJib29sZWFuUHJvcGVydHkiOnsidGl0bGUiOiJCb29sZWFuIFByb3BlcnR5IiwiZGVmYXVsdCI6dHJ1ZSwidHlwZSI6ImJvb2xlYW4ifX19fSwiaWYiOnsicHJvcGVydGllcyI6eyJhcnJheV9vZl9vYmplY3RzIjp7InByb3BlcnRpZXMiOnsiYm9vbGVhblByb3BlcnR5Ijp7ImNvbnN0Ijp0cnVlfX19fX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJhcnJheV9vZl9vYmplY3RzIjp7InByb3BlcnRpZXMiOnsib3RoZXJQcm9wZXJ0eSI6eyJ0aXRsZSI6Ik90aGVyIFByb3BlcnR5IiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiSGVsbG8iLCJXb3JsZCJdfX19fSwicmVxdWlyZWQiOlsib3RoZXJQcm9wZXJ0eSJdfX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOnsicG9wdWxhdGUiOiJwb3B1bGF0ZSIsIm1lcmdlRXh0cmFEZWZhdWx0cyI6ZmFsc2V9LCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9LCJsaXZlVmFsaWRhdGUiOnRydWUsImxpdmVPbWl0Ijp0cnVlLCJvbWl0RXh0cmFEYXRhIjp0cnVlfX0=)). But I think this should also work with the above schema because the conditional field is rendered correctly and the validation still throws an error.

Do you have any idea what is causing this behavior and where to fix it?

**Comment by heath-freenome** [comment] 2024-03-22 19:43
@anya92 The issue is in the `omitExtraData` code that is currently in `Form`. Interestingly someone is working on a PR to pull that code down into the `utils` library (#4139), maybe you can work with them to see if there is a fix that can be made during the extraction.

**Comment by helen-m-lin** [comment] 2024-05-03 19:04
Hi @heath-freenome, I'm also having issues with `omitExtraData` during `onSubmit`, though not entirely sure if it's the same thing @anya92 is describing.
What is the expected behavior? I assumed that it should first omit any extra data in the `formData`, and then validate the resulting `newFormData`. Currently I don't think `newFormData` is being used for validation here. 
https://github.com/rjsf-team/react-jsonschema-form/blob/e7b82772d4011670dd9f40049b3ba9000431de67/packages/core/src/components/Form.tsx#L709-L712
If needed, I am happy to help out to implement a fix.

**Comment by heath-freenome** [comment] 2024-06-20 16:49
@helen-m-lin How goes the fix we discussed?

**Comment by helen-m-lin** [comment] 2024-06-20 17:23
Sorry, I haven't had the chance to work on it! Thank you for the reminder. I will work on the fix this later this week.

**Closed** 2024-07-01 21:34 UTC
Labels: bug, help wanted, awaiting response

**Comment by anya92** [comment] 2024-07-09 04:18
Hi @helen-m-lin and @heath-freenome.

First of all, I would like to thank you for your work and recent PR to address this issue. However, I wanted to let you know that the problem at the playground still exists.

It seems that the problem is not related to `liveOmit` and `omitExtraData` as I initially thought. Instead, it seems to be more closely related to nested `if...then` conditions.
