### ISSUE TITLE
Default array not populated when minItems present

### ISSUE THREAD

**Issue by fsteger** [rjsf-team/react-jsonschema-form#1258] opened 2019-04-17 14:47 UTC
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Description of the bug or feature]

### Steps to Reproduce
1) Create a new form using empty form data and the following schema / uiSchema:

JSON schema:
`
{
  "type": "object",
  "properties": {
    "multipleChoicesList": {
      "type": "array",
      "title": "A multiple choices list",
      "minItems": 1,
      "default": ["foo", "qux"]
      "items": {
        "type": "string",
        "enum": [
          "foo",
          "bar",
          "fuzz",
          "qux"
        ]
      },
      "uniqueItems": true
    }
}
`

UI Schema:
`
{
  "multipleChoicesList": {
    "ui:widget": "checkboxes"
  }
}
`

#### Expected behavior

Default values should be populated in formData

#### Actual behavior

Inside formData, field is initialized with an empty array.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

1.2.1

### Additional Information
* Inside computeDefaults function, for type "array", if minItems is defined and it is a multi-select (ie, checkbox list), then the default of an empty array is always returned. Otherwise, code will populate defaults if number of default values is greater than minItems.
* Looking at the code, I suspect this may be backwards, and should only return the empty array if it is not an empty multi-select.
* Code introduced - https://github.com/mozilla-services/react-jsonschema-form/pull/661

**Comment by epicfaace** [comment] 2019-04-17 15:48
This may be related to #1026 and perhaps a fix for this might fix that one too.

It looks like you're on the right track! Feel free to make a PR fixing this.

**Comment by epicfaace** [comment] 2019-05-24 00:24
[Reproducible playground example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJtdWx0aXBsZUNob2ljZXNMaXN0IjpbXSwiZmlyc3ROYW1lIjoiQ2h1Y2sifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im11bHRpcGxlQ2hvaWNlc0xpc3QiOnsidHlwZSI6ImFycmF5IiwidGl0bGUiOiJBIG11bHRpcGxlIGNob2ljZXMgbGlzdCIsIm1pbkl0ZW1zIjoxLCJkZWZhdWx0IjpbImZvbyIsInF1eCJdLCJpdGVtcyI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJmb28iLCJiYXIiLCJmdXp6IiwicXV4Il19LCJ1bmlxdWVJdGVtcyI6dHJ1ZX19fSwidWlTY2hlbWEiOnt9fQ==)

**Closed** 2022-05-01 16:28 UTC
Labels: bug, wontfix
