### ISSUE TITLE
Material-ui theme does not display "+" button for additionalProperties

### ISSUE THREAD

**Issue by nboxall1** [rjsf-team/react-jsonschema-form#1977] opened 2020-08-07 09:00 UTC
### Prerequisites

[Shared playground which demos my question](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkFkZGl0aW9uYWwgUHJvcHMgVGVzdCIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTmFtZSJ9fSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnsidHlwZSI6InN0cmluZyJ9fSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19)

### Description

The plus button is displayed for additionalProperties, but when I switch to the Material-ui theme the plus button is not displayed. 

### Steps to Reproduce

Follow the link to shared playground above. 
e.g. 
This schema does not display a plus button for Material-UI theme.
```
{
  "title": "Additional Props Test",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "title": "Name"
    }
  },
  "additionalProperties": {
    "type": "string"
  }
}
```

**Comment by epicfaace** [comment] 2020-08-07 13:50
Duplicate of #1724.

**Closed by epicfaace** 2020-08-07 13:50 UTC
