### ISSUE TITLE
How can I pass ui:widget hidden to oneOf/anyOf/allOf

### ISSUE THREAD

**Issue by cgokey** [rjsf-team/react-jsonschema-form#4229] opened 2024-06-25 13:51 UTC
I'm including the following [sandbox url](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJhbnlPZiI6W3sicmVxdWlyZWQiOlsiZmlyc3ROYW1lIl19LHsicmVxdWlyZWQiOlsibGFzdE5hbWUiXX1dLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaXJzdCBuYW1lIiwiZGVmYXVsdCI6IkNodWNrIn0sImxhc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ikxhc3QgbmFtZSJ9LCJhZ2UiOnsidHlwZSI6ImludGVnZXIiLCJ0aXRsZSI6IkFnZSJ9LCJiaW8iOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiQmlvIn0sInBhc3N3b3JkIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlBhc3N3b3JkIiwibWluTGVuZ3RoIjozfSwidGVsZXBob25lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRlbGVwaG9uZSIsIm1pbkxlbmd0aCI6MTB9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTpwbGFjZWhvbGRlciI6InVpOmVtcHR5VmFsdWUgY2F1c2VzIHRoaXMgZmllbGQgdG8gYWx3YXlzIGJlIHZhbGlkIGRlc3BpdGUgYmVpbmcgcmVxdWlyZWQiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSIsInVpOmVuYWJsZU1hcmtkb3duSW5EZXNjcmlwdGlvbiI6dHJ1ZSwidWk6ZGVzY3JpcHRpb24iOiJNYWtlIHRleHQgKipib2xkKiogb3IgKml0YWxpYyouIFRha2UgYSBsb29rIGF0IG90aGVyIG9wdGlvbnMgW2hlcmVdKGh0dHBzOi8vbWFya2Rvd24tdG8tanN4LnF1YW50aXpvci5kZXYvKS4ifSwibGFzdE5hbWUiOnsidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSIsInVpOmVuYWJsZU1hcmtkb3duSW5EZXNjcmlwdGlvbiI6dHJ1ZSwidWk6ZGVzY3JpcHRpb24iOiJNYWtlIHRoaW5ncyAqKmJvbGQqKiBvciAqaXRhbGljKi4gRW1iZWQgc25pcHBldHMgb2YgYGNvZGVgLiA8c21hbGw+QW5kIHRoaXMgaXMgYSBzbWFsbCB0ZXh0cy48L3NtYWxsPiAifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19LCJhbnlPZiI6eyJ1aTp3aWRnZXQiOiJoaWRkZW4ifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=) as an illustration:

I tried this, but with no luck.
```
"anyOf": {
    "ui:widget": "hidden"
  }
```

Is there any way to hide the combo box?

The json schema is here:
```
{
  "title": "A registration form",
  "description": "A simple form example.",
  "type": "object",
  "anyOf": [
    {
      "required": [
        "firstName"
      ]
    },
    {
      "required": [
        "lastName"
      ]
    }
  ],
  "properties": {
    "firstName": {
      "type": "string",
      "title": "First name",
      "default": "Chuck"
    },
    "lastName": {
      "type": "string",
      "title": "Last name"
    },
    "age": {
      "type": "integer",
      "title": "Age"
    },
    "bio": {
      "type": "string",
      "title": "Bio"
    },
    "password": {
      "type": "string",
      "title": "Password",
      "minLength": 3
    },
    "telephone": {
      "type": "string",
      "title": "Telephone",
      "minLength": 10
    }
  }
}
```

**Comment by corbinschwartz** [comment] 2024-06-26 19:40
Facing this same issue.

@cgokey this won't hide the dropdown, but one thing you might want to do is add `"type": "object",` to your `anyOf` blocks (it hides the rjsf error complaining about undefined type)

**Comment by heath-freenome** [comment] 2024-06-28 20:02
Closing this as a duplicate of #3834

**Closed by heath-freenome** 2024-06-28 20:02 UTC
Labels: question

**Comment by nickgros** [comment] 2024-06-28 20:15
Does this work? [Playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEtODAwLUtJQ0tBU1MifSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJhbnlPZiI6W3sicmVxdWlyZWQiOlsiZmlyc3ROYW1lIl19LHsicmVxdWlyZWQiOlsibGFzdE5hbWUiXX1dLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaXJzdCBuYW1lIiwiZGVmYXVsdCI6IkNodWNrIn0sImxhc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ikxhc3QgbmFtZSJ9LCJhZ2UiOnsidHlwZSI6ImludGVnZXIiLCJ0aXRsZSI6IkFnZSJ9LCJiaW8iOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiQmlvIn0sInBhc3N3b3JkIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlBhc3N3b3JkIiwibWluTGVuZ3RoIjozfSwidGVsZXBob25lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRlbGVwaG9uZSIsIm1pbkxlbmd0aCI6MTB9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTpwbGFjZWhvbGRlciI6InVpOmVtcHR5VmFsdWUgY2F1c2VzIHRoaXMgZmllbGQgdG8gYWx3YXlzIGJlIHZhbGlkIGRlc3BpdGUgYmVpbmcgcmVxdWlyZWQiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSIsInVpOmVuYWJsZU1hcmtkb3duSW5EZXNjcmlwdGlvbiI6dHJ1ZSwidWk6ZGVzY3JpcHRpb24iOiJNYWtlIHRleHQgKipib2xkKiogb3IgKml0YWxpYyouIFRha2UgYSBsb29rIGF0IG90aGVyIG9wdGlvbnMgW2hlcmVdKGh0dHBzOi8vbWFya2Rvd24tdG8tanN4LnF1YW50aXpvci5kZXYvKS4ifSwibGFzdE5hbWUiOnsidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSIsInVpOmVuYWJsZU1hcmtkb3duSW5EZXNjcmlwdGlvbiI6dHJ1ZSwidWk6ZGVzY3JpcHRpb24iOiJNYWtlIHRoaW5ncyAqKmJvbGQqKiBvciAqaXRhbGljKi4gRW1iZWQgc25pcHBldHMgb2YgYGNvZGVgLiA8c21hbGw+QW5kIHRoaXMgaXMgYSBzbWFsbCB0ZXh0cy48L3NtYWxsPiAifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19LCJhbnlPZiI6eyJ1aTp3aWRnZXQiOiJoaWRkZW4ifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJhbGxPZiI6InNraXBEZWZhdWx0cyIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=)

**Comment by nickgros** [comment] 2024-07-05 16:16
@corbinschwartz sorry, I think I sent the wrong playground link. I meant to send this one with @cgokey 's example, where you could use the uiSchema

```json
{
  "ui:fieldReplacesAnyOrOneOf": true,
  "ui:field": "hidden"
}
```

 [Here's a new link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiIiLCJhZ2UiOjc1LCJiaW8iOiJSb3VuZGhvdXNlIGtpY2tpbmcgYXNzZXMgc2luY2UgMTk0MCIsInBhc3N3b3JkIjoibm9uZWVkIiwidGVsZXBob25lIjoiMS04MDAtS0lDS0FTUyJ9LCJzY2hlbWEiOnsidGl0bGUiOiJBIHJlZ2lzdHJhdGlvbiBmb3JtIiwiZGVzY3JpcHRpb24iOiJBIHNpbXBsZSBmb3JtIGV4YW1wbGUuIiwidHlwZSI6Im9iamVjdCIsImFueU9mIjpbeyJyZXF1aXJlZCI6WyJmaXJzdE5hbWUiXX0seyJyZXF1aXJlZCI6WyJsYXN0TmFtZSJdfV0sInByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkZpcnN0IG5hbWUiLCJkZWZhdWx0IjoiQ2h1Y2sifSwibGFzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTGFzdCBuYW1lIn0sImFnZSI6eyJ0eXBlIjoiaW50ZWdlciIsInRpdGxlIjoiQWdlIn0sImJpbyI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJCaW8ifSwicGFzc3dvcmQiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiUGFzc3dvcmQiLCJtaW5MZW5ndGgiOjN9LCJ0ZWxlcGhvbmUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiVGVsZXBob25lIiwibWluTGVuZ3RoIjoxMH19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOnBsYWNlaG9sZGVyIjoidWk6ZW1wdHlWYWx1ZSBjYXVzZXMgdGhpcyBmaWVsZCB0byBhbHdheXMgYmUgdmFsaWQgZGVzcGl0ZSBiZWluZyByZXF1aXJlZCIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIiwidWk6ZW5hYmxlTWFya2Rvd25JbkRlc2NyaXB0aW9uIjp0cnVlLCJ1aTpkZXNjcmlwdGlvbiI6Ik1ha2UgdGV4dCAqKmJvbGQqKiBvciAqaXRhbGljKi4gVGFrZSBhIGxvb2sgYXQgb3RoZXIgb3B0aW9ucyBbaGVyZV0oaHR0cHM6Ly9tYXJrZG93bi10by1qc3gucXVhbnRpem9yLmRldi8pLiJ9LCJsYXN0TmFtZSI6eyJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIiwidWk6ZW5hYmxlTWFya2Rvd25JbkRlc2NyaXB0aW9uIjp0cnVlLCJ1aTpkZXNjcmlwdGlvbiI6Ik1ha2UgdGhpbmdzICoqYm9sZCoqIG9yICppdGFsaWMqLiBFbWJlZCBzbmlwcGV0cyBvZiBgY29kZWAuIDxzbWFsbD5BbmQgdGhpcyBpcyBhIHNtYWxsIHRleHRzLjwvc21hbGw+ICJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGggeWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX0sInVpOmZpZWxkUmVwbGFjZXNBbnlPck9uZU9mIjp0cnVlLCJ1aTpmaWVsZCI6ImhpZGRlbiJ9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJub0h0bWw1VmFsaWRhdGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2UsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIiwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19).
