### ISSUE TITLE
Select bug when multiple oneOf are nested

### ISSUE THREAD

**Issue by AmauryBes** [rjsf-team/react-jsonschema-form#4147] opened 2024-03-27 09:54 UTC
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

When having nested oneOf the top select needs 2 selection to actively swtich to the proper value.

### Expected Behavior

Select that select on each click

### Steps To Reproduce

[playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InRpdGxlIjoiYmlrZSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImJpa2UiOnsidGl0bGUiOiJuYW1lIiwidHlwZSI6InN0cmluZyJ9fX0seyJ0aXRsZSI6ImNhciIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImJyYW5kIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkJyYW5kIn0sImNhckluZm8iOnsidGl0bGUiOiJDYXIgaW5mbyIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im1vc3RJbXBvcnRhbnRJbmZvIjp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IkNob29zZSBjYXIgY2F0ZWdvcnkiLCJvbmVPZiI6W3sidGl0bGUiOiJTcG9ydCBDYXIiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJtYXhzcGVlZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJNYXggU3BlZWQifX19LHsidGl0bGUiOiJTVVYiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJoZWlnaHQiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiSGVpZ2h0In19fV19fX19fV19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19)

switch between car and bike on the top select, from car to bike you'll need to select bike twice

**Comment by nickgros** [comment] 2024-04-05 19:36
Maybe a duplicate of #3977?

**Comment by heath-freenome** [comment] 2024-04-05 19:44
@AmauryBes This seems like a duplicate of #3977 , so we are closing it as such. If you'd like to get this issue fixed soon, I would suggest trying to fix it yourself and pushing a PR. Feel free to reach out if you have any questions

**Closed by heath-freenome** 2024-04-05 19:44 UTC
Labels: bug, duplicate issue
