### ISSUE TITLE
HiddenWidget + Bootstrap4 theme still shows description of a property

### ISSUE THREAD

**Issue by jimjaeger** [rjsf-team/react-jsonschema-form#2319] opened 2021-03-31 09:42 UTC
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
I use react-jsonschema-form and bootstrap4 theme. I would like to hide an property or just show the property without an input field. For this I use the hidden widget. 

### Steps to Reproduce

1. Open https://rjsf-team.github.io/react-jsonschema-form/
2. Enter data - see below
3. Select boostrap 4 theme

#### Expected behavior
The description is hidden too

#### Actual behavior
The description is hidden in default theme. but the description is still there and not hidden for boostrap theme.

### Version
  "@rjsf/bootstrap-4": "^2.5.1",  "@rjsf/core": "^2.5.1",

### Data

scheme:
```
{
  "title": "A registration form",
  "description": "A simple form example.",
  "type": "object",
  "required": [
    "firstName",
    "lastName"
  ],
  "properties": {
    "type": {
      "description": "Should be hidden - description",
      "type": "string",
      "title": "Should be hidden - title",
      "default": "Should be hidden - value"
    },
    "firstName": {
      "type": "string",
      "title": "First name",
      "default": "Chuck"
    }
  
  }
}
```

uiScheme:
```
{
  "type": {
    "ui:widget": "hidden",
    "ui:emptyValue": ""
  },
  "firstName": {
    "ui:autofocus": true,
    "ui:emptyValue": "",
    "ui:autocomplete": "family-name"
  }
}
```

formdata:
```
{
  "type": "Should be hidden - value",
  "firstName": "Chuck"
}
```

**Comment by newt10** [comment] 2021-09-02 20:15
This seems to be fixed. I cannot reproduce it on the latest release as of today. 
I am seeing descriptions and the field hidden on both core as well as bootstrap 4 implementations.
See screenshots below
### Core Form
<img width="1351" alt="Core" src="https://user-images.githubusercontent.com/42853152/131909692-5570da28-9b92-4b01-b7fb-49bfdd8afadb.png">

### Bootstrap 4 Form
<img width="1300" alt="BS4" src="https://user-images.githubusercontent.com/42853152/131909736-28b463b8-85f5-4401-a8eb-a2c4f07baed3.png">

I am closing this an it is not reproducible as described. @jimjaeger  Please re-open/comment if the issue persists and update the actual/expected behaviors.

**Closed by newt10** 2021-09-02 20:15 UTC
Labels: bootstrap-4
