### ISSUE TITLE
Material UI 5 Support - No `Mui5Theme` export

### ISSUE THREAD

**Issue by wasinsandiego** [rjsf-team/react-jsonschema-form#2694] opened 2022-02-08 18:21 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
> On providing a JS fiddle, I didn't see a way to install the theme packages for which this example would be required.
We are using RJSF with the Material UI v4 theme and upgrading to Material UI v5. I saw the recent merge supporting Material UI v5.

Attempts to update via usual methods `npm install`, etc do not seem to work. Closer inspection of node modules it's clear that it never truly updates. The README does not have the updated [MUI v5 documentation](https://github.com/rjsf-team/react-jsonschema-form/tree/master/packages/material-ui#material-ui-version-5-1)

Following attempts included installing via GitHub URI and pointing to a local cloned version resulted in the same.

Finally, I cloned the repo and built the package, and manually copied it to my `node_modules` for the sake of troubleshooting. It appears that  `MuiForm5` and `Theme5` are not exported from `@rjsf/material-ui`.

### Steps to Reproduce
The usual attempt goes like this...
1. Install using the directions here: https://github.com/rjsf-team/react-jsonschema-form/tree/master/packages/material-ui#material-ui-version-5
2. If you don't already have a form create one.
3. Update existing form imports with the appropriate method for you found here: https://github.com/rjsf-team/react-jsonschema-form/tree/master/packages/material-ui#material-ui-version-5-1
4. You will see that all exports as defined in the documentation are undefined.

#### Expected behavior
The exports should be stuff and make my RJSF Forms work in my Material-UI 5 Themed App.

#### Actual behavior
Using the documented approach throws errors because stuff is undefined.

### Version
I noticed that neither the package.json version for @rjsf and `@rjsf/material-ui were not updated with the commits that make Material-UI v5 available. They are:
* `@rjsf/material-ui`  is at **3.2.1**
* `@rjsf/core` is at **3.2.1**

> I will put together an example repo when I have a few minutes since I could not get the JS Fiddle or codepen working with themes. Please let me know if I can help in any other ways or if I missed something obvious.

**Comment by epicfaace** [comment] 2022-02-08 18:24
Material UI 5 is not yet released, it will be released in the next version of rjsf.

**Closed by epicfaace** 2022-02-08 18:24 UTC

**Comment by rollercodester** [comment] 2022-02-09 20:25
> Material UI 5 is not yet released, it will be released in the next version of rjsf.

ETA?

**Comment by epicfaace** [comment] 2022-02-09 20:30
https://docs.google.com/document/d/12PjTvv21k6LIky6bNQVnsplMLLnmEuypTLQF8a-8Wss/edit

--
Ashwin Ramaswami

**Comment by heath-freenome** [comment] 2022-02-23 00:07
@mzager it is in v4.0

**Comment by keepeek-rd** [comment] 2022-02-24 11:21
I just upgraded to the latest version of rjsf/core and rjsf/material-ui in 4.0.1 and the interface works well with MUI5.
On the other hand, I observe in the logs warning concerning the loading of the old material-ui 4 dependencies:

warn - ./node_modules/@rjsf/material-ui/dist/material-ui.esm.js
Module not found: Can't resolve '@material-ui/core' in 'XXX\node_modules\@rjsf\material-ui\dist'

./node_modules/@rjsf/material-ui/dist/material-ui.esm.js
Module not found: Can't resolve '@material-ui/icons' in 'XXX\node_modules\@rjsf\material-ui\dist'
wait - compiling /api/admin/config/[...configSection] (server only)...
warn - ./node_modules/@rjsf/material-ui/dist/material-ui.esm.js
Module not found: Can't resolve '@material-ui/core' in 'XXX\node_modules\@rjsf\material-ui\dist'

./node_modules/@rjsf/material-ui/dist/material-ui.esm.js
Module not found: Can't resolve '@material-ui/icons' in 'XXX\node_modules\@rjsf\material-ui\dist'

I do not have these dependencies in my project because of MUI migration:
"@emotion/react": "11.8.1",
"@emotion/server": "11.4.0",
"@emotion/styled": "11.8.1",
"@mui/icons-material": "5.4.2",
"@mui/lab": "5.0.0-alpha.70",
"@mui/material": "5.4.3",


do you think this is a temporary situation?

**Comment by heath-freenome** [comment] 2022-02-24 18:36
> I just upgraded to the latest version of rjsf/core and rjsf/material-ui in 4.0.1 and the interface works well with MUI5. On the other hand, I observe in the logs warning concerning the loading of the old material-ui 4 dependencies:
> 
> warn - ./node_modules/@rjsf/material-ui/dist/material-ui.esm.js Module not found: Can't resolve '@material-ui/core' in 'XXX\node_modules@rjsf\material-ui\dist'
> 
> ./node_modules/@rjsf/material-ui/dist/material-ui.esm.js Module not found: Can't resolve '@material-ui/icons' in 'XXX\node_modules@rjsf\material-ui\dist' wait - compiling /api/admin/config/[...configSection] (server only)... warn - ./node_modules/@rjsf/material-ui/dist/material-ui.esm.js Module not found: Can't resolve '@material-ui/core' in 'XXX\node_modules@rjsf\material-ui\dist'
> 
> ./node_modules/@rjsf/material-ui/dist/material-ui.esm.js Module not found: Can't resolve '@material-ui/icons' in 'XXX\node_modules@rjsf\material-ui\dist'
> 
> I do not have these dependencies in my project because of MUI migration: "@emotion/react": "11.8.1", "@emotion/server": "11.4.0", "@emotion/styled": "11.8.1", "@mui/icons-material": "5.4.2", "@mui/lab": "5.0.0-alpha.70", "@mui/material": "5.4.3",
> 
> do you think this is a temporary situation?

This is a duplicate of #2721 You can track that there... A fix is pending
