### ISSUE TITLE
Form with method=post and action=url in nodejs is unable to get formdata 

### ISSUE THREAD

**Issue by eyesmoker** [rjsf-team/react-jsonschema-form#1450] opened 2019-09-06 06:43 UTC
I have react server side setup that is generating a react json schema form like the following. php codebase is calling react server and basically embedding the raw html form.  When the form submission happens, it is reaching /users which is built on nodejs but formData in the request body is null.
Could you please help on how do I fetch the formData on submit in this scenario?

`<form class="rjsf" method="post" action="http://localhost:3000/users" enctype="application/x-www-form-urlencoded" ><div class="form-group field field-object"><fieldset id="root"><legend id="root__title">My Form</legend><p id="root__description" class="field-description">My Form</p><div class="form-group field field-string"><label class="control-label" for="root_name">Name<span class="required">*</span></label><input type="text" class="form-control" value="abc" id="root_name" label="Name" required="" placeholder=""/></div></fieldset></div><div><button type="submit" class="btn btn-info">Submit</button></div></form>
`

**Comment by epicfaace** [comment] 2019-09-09 05:04
The issue here is that the form fields don't have a `name` attribute, and thus when you submit it as a normal HTML form, no data is submitted. This is a duplicate of issue #652, so I'll close this issue. I mentioned a solution using pathSchema to assign names to widgets in that issue, though.

**Closed by epicfaace** 2019-09-09 05:04 UTC

**Comment by eyesmoker** [comment] 2019-09-14 20:12
Thank you.

Is this the way to pass pathSchema. Can you point me to an example ?
 <Form name="test" schema={jsonschema} formData={formdata} uiSchema={uischema} pathSchema={pathschema}

**Comment by epicfaace** [comment] 2019-09-14 21:18
@eyesmoker there actually isn't any way to access pathSchema currently. This would require a change / pull request to rjsf itself

**Comment by eyesmoker** [comment] 2019-09-15 03:29
ok. Thank you.

**Comment by adamwong246** [comment] 2021-09-04 23:40
+1 to this issue. It means this project can't be used for ServerSideRendering. Is there some insurmountable barrier to adding names to form input elements?

**Comment by epicfaace** [comment] 2021-09-05 01:42
> Is there some insurmountable barrier to adding names to form input elements?

No, feel free to make a PR that does this.

**Comment by epicfaace** [comment] 2021-09-05 01:42
This issue is being tracked in https://github.com/rjsf-team/react-jsonschema-form/issues/652.
