### ISSUE TITLE
 do you know some visual create form? like a form builder

### ISSUE THREAD

**Issue by MedinaGitHub** [rjsf-team/react-jsonschema-form#1879] opened 2020-06-29 17:11 UTC
This is not an issue.

Thanks you for the proyect,

I have a question

do you know some visual create form?. like a form builder (like this https://kiho.github.io/react-form-builder/)

other question

and how i can (with this proyect of course) show the result form dynamically for example in a table or in a some view...

Thanks You ! =)

**Comment by airtonix** [comment] 2020-08-19 08:56
If you just want something that your internal team can use then check out jsoneditor.

it allows you to describe "types" that can be added to any node, it uses JSONschema to do this.

https://github.com/josdejong/jsoneditor/blob/master/docs/api.md

**Comment by MedinaGitHub** [comment] 2020-09-18 05:23
now ii work in this project, https://github.com/MedinaGitHub/react-jsonschema-form-builder  =)

**Comment by MedinaGitHub** [comment] 2020-10-26 13:10
@epicfaace  i finished the first step of this proyect, it is a visual builder of json schema. https://github.com/MedinaGitHub/react-jsonschema-form-builder  =)

**Comment by epicfaace** [comment] 2022-01-24 14:44
closing as duplicate of https://github.com/rjsf-team/react-jsonschema-form/issues/588

**Closed by epicfaace** 2022-01-24 14:44 UTC
