### ISSUE TITLE
Inconsistent support for oneOf

### ISSUE THREAD

**Issue by jericmason** [rjsf-team/react-jsonschema-form#1148] opened 2019-01-21 21:05 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Prior to the release of oneOf as a stand-alone supported construct, it was possible to achieve the behaviour with an extra field and schema dependencies. The schema dependency technique syntactically uses **oneOf** to achieve this behaviour. However, this approach will generate validation errors when used in combination with **addtionalProperties: false**. If you make any changes to the form you will likely end up in [this state](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJpZGVudFR5cGUiOiJ0eXBlMSIsImZpcnN0TmFtZSI6InRlc3QiLCJsYXN0TmFtZSI6InRlc3QiLCJpZENvZGUiOiI1In0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJpZGVudFR5cGUiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsidHlwZTEiLCJ0eXBlMiJdfX0sImRlcGVuZGVuY2llcyI6eyJpZGVudFR5cGUiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiaWRlbnRUeXBlIjp7ImVudW0iOlsidHlwZTEiXX0sImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaXJzdCBOYW1lIn0sImxhc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ikxhc3QgTmFtZSJ9fSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlfSx7InByb3BlcnRpZXMiOnsiaWRlbnRUeXBlIjp7ImVudW0iOlsidHlwZTIiXX0sImlkQ29kZSI6eyJ0eXBlIjoic3RyaW5nIn19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9XX19fSwidWlTY2hlbWEiOnt9fQ==). When I use stand-alone **oneOf** without dependencies I won't get into an invalid state (see [example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJ0ZXN0IiwibGFzdE5hbWUiOiJ0ZXN0In0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InRpdGxlIjoidHlwZTEiLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaXJzdCBOYW1lIn0sImxhc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ikxhc3QgTmFtZSJ9fSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlfSx7InRpdGxlIjoidHlwZTIiLCJwcm9wZXJ0aWVzIjp7ImlkQ29kZSI6eyJ0eXBlIjoic3RyaW5nIn19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9XX0sInVpU2NoZW1hIjp7fX0=)).

### Steps to Reproduce

1. Create a schema with dependencies and additionalProperties false
2. Fill in the fields for one of the dependencies
3. Fill in the fields for a different dependency
4. You'll see an error

This has been brought up [previously](https://github.com/mozilla-services/react-jsonschema-form/pull/1018), but I believe with full support for **oneOf** now in place it should be revisited as perhaps there is a way both implementations could use the same underlying technology.

### Version

v1.2.0

**Comment by epicfaace** [comment] 2019-01-21 22:50
Hmm, so it looks like the problem is that when the value changes and triggers a new schema in `oneOf`, the library should delete the keys in `formData` that are not present in the new schema. This is the code which implements that requirement with the standalone oneOf without dependencies:

https://github.com/mozilla-services/react-jsonschema-form/blob/1941e760d8af93b118bbc193dd98b88f64b32645/src/components/fields/MultiSchemaField.js#L53

Note that the code above gets run on an on-change event in the MultiSchemaField.

On the other hand, the functionality with oneOf and schema dependencies seems to be implemented in the part of the code which just returns the schema. Note that although we can read `formData` here, we neither have access to `onChange` nor can we modify `formData` as required.

https://github.com/mozilla-services/react-jsonschema-form/blob/cf463421fc671146eea377b00608949837bc5890/src/utils.js#L554

Any thoughts on how we can fix this?

**Comment by glasserc** [comment] 2019-02-04 17:58
When we switch from one `oneOf` case to another, we try to remove the fields that correspond to the `oneOf` case that we leave. I think similar behavior makes sense when we switch out of a schema dependency case. That may mean moving the schema dependency logic out of `utils` and into `SchemaField` or something. Unfortunately, unlike `MultiSchemaField`, there's no clear "component" here that makes sense to extract. I don't think this is going to be an easy bugfix.

**Comment by epicfaace** [comment] 2019-08-11 04:09
@jericmason now that we have `omitExtraData` and `liveOmit`, try setting "Omit extra data" and "Live omit" in the playground to true -- and it should work as expected.

That being said, you're right in that there's a difference now:

- When using oneOf by itself, it automatically "omits" extra data when changing oneOf options.
- When using oneOf within a dependency, it does not automatically "omit" extra data when changing oneOf options. It only does so when omitExtraData and liveOmit are true.

Would it make sense to change the behavior of oneOf within a dependency to that of oneOf by itself? (i.e., automatically "omit" extra data when changing oneOf options)

(also cc'ing @LucianBuzzo @gr8pathik (#1377) )

**Comment by jericmason** [comment] 2019-08-12 19:21
Thanks for the update @epicfaace. It looks like using _liveOmit_ and _omitExtraData_ does indeed resolve the biggest problem with schema dependencies + `additionalProperties: false`. 

In my opinion, it makes sense that the oneOf behaviour would be a reasonable default for oneOf in dependencies (equivalent to always treating it with _liveOmit_ and _omitExtraData_ active). Any sort of data carry-over between sub-schemas in oneOf is guaranteed to produce a schema that can't validate. That said, it looks like the are still some lingering bugs with validation when using oneOf with `additionalProperties: false`. If you take the [example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0Iiwib25lT2YiOlt7InRpdGxlIjoidHlwZTEiLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaXJzdCBOYW1lIn0sImxhc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ikxhc3QgTmFtZSJ9fSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlfSx7InRpdGxlIjoidHlwZTIiLCJwcm9wZXJ0aWVzIjp7ImlkQ29kZSI6eyJ0eXBlIjoic3RyaW5nIn19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2V9XX0sInVpU2NoZW1hIjp7fX0=) I posted and set _First Name_ and _Last Name_ then switch to _type2_ and set _idCode_ then start to type a field for that you will get validation errors even though the JSON it produces is perfectly valid (might be a timing issue?).

**Comment by heath-freenome** [comment] 2023-02-01 23:44
This is most likely fixed in 5.0 given the improvements in anyOf/oneOf handling

**Closed by heath-freenome** 2023-02-01 23:44 UTC
Labels: question, dependencies, multiSchema
