### ISSUE TITLE
oneOf picks first schema or both in playground

### ISSUE THREAD

**Issue by hardysabs2** [rjsf-team/react-jsonschema-form#2383] opened 2021-05-17 12:11 UTC
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

oneOf picks first schema or both in playground, not either or

### Steps to Reproduce

Use this json schema in the playground:

{
  "type": "object",
  "oneOf": [
    {
      "properties": {
        "lorem": {
          "type": "object",
          "properties": {
            "f1": {
              "type": "string"
            },
            "f2": {
              "type": "string"
            }
          },
          "required": ["f1", "f2"]
        }
      },
      "required": [ "lorem"
      ]
    },
    {
      "properties": {
        "ipsum": {
          "type": "object",
          "properties": {
            "g1": {
              "type": "string"
            }
          },
          "required": ["g1"]
        }
      },
      "required": [ "ipsum"
      ]
    }
  ]
}

#### Expected behavior

When I use the dropdown to switch between schemas option 1 or option 2 and fill in the form and submit I expect either this form data

{
  "lorem": {
    "f1": "aa",
    "f2": "aa"
  }
}

or this form data

{
  "ipsum": {
    "g1": "aa"
  }
}

#### Actual behavior

however with the first option I always get the first schema only (lorem above) but with the second option I always get both with the first schema empty.

{
  "lorem": {},
  "ipsum": {
    "g1": "aa"
  }
}

I don't understand why.

Also as I use the dropdown to switch between the schemas I get this error "should match exactly one schema in oneOf", even though I can successfully complete the field and submit without error.

I just want to use the dropdown to pick between two objects with properties and fill in the fields and get form data for just one of them.

### Version

Playground:

https://rjsf-team.github.io/react-jsonschema-form/

**Comment by arghness** [comment] 2021-06-05 00:01
Actually, this seems to be a duplicate of #2183 ?

**Comment by heath-freenome** [comment] 2023-01-20 20:57
Closing as duplicate of #2183

**Closed by heath-freenome** 2023-01-20 20:57 UTC
Labels: bug, core
