### ISSUE TITLE
Fluent-UI theme selection in playground breaks the layout

### ISSUE THREAD

**Issue by iconag-bbasmer** [rjsf-team/react-jsonschema-form#3749] opened 2023-06-29 11:13 UTC
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

fluent-ui

### Version

5.x

### Current Behavior

In the playground when switching to the fluent-ui theme the design of the complete form breaks.

### Expected Behavior

Fluent-UI theme also works in the playground.

### Steps To Reproduce

1. Open the playground
2. Open the "Theme" dropdown
3. Choose "fluent-ui"

### Anything else?

![fluent-theme](https://github.com/rjsf-team/react-jsonschema-form/assets/90677144/dadae568-4927-4d75-a368-1e08fd1e495c)

**Comment by nickgros** [comment] 2023-06-30 15:50
Duplicate of https://github.com/rjsf-team/react-jsonschema-form/issues/2734

We've tried to get this to work a few times, but the way that Fluent UI provides styles to components is tough to integrate properly with how we render various themes in the playground. A PR to fix this is welcome, but it's evidently not an easy problem to solve.

**Closed by nickgros** 2023-06-30 15:50 UTC
Labels: bug, needs triage
