### ISSUE TITLE
Can clicking the custom "I want to submit" button not trigger the onsubmit event of the form？

### ISSUE THREAD

**Issue by dajun1230** [rjsf-team/react-jsonschema-form#2617] opened 2021-11-19 12:51 UTC
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Can clicking the custom "I want to submit" button not trigger the onsubmit event of the form

[Description of the bug or feature]

### Steps to Reproduce
function LoginLockForm(): JSX.Element {
  let yourForm: any;
  const schema: any = {
    type: 'object',
    properties: {
      password: {
        type: 'object',
        title: '密码验证',
      },
      ip: { type: 'object', title: 'IP校验' },
    },
    required: ['password', 'ip'],
  };

  const widgets = {
    TextWidget: FormInput,
  };

  const uiSchema = { 'ui:field': 'password' };

  const fields = {
    password: PasswdFunc,
    ip: IpValidate,
  };

  function customSubmit(): void {
    yourForm.submit();
    console.log(yourForm);
    // yourForm.submit();
  }

  function validate(formData: any, errors: any): any {
    if (formData.password !== {}) {
      errors.password.addError('Passwords don\'t match');
    }
    return errors;
  }

  const onSubmit = ({ formData }: any) => console.log('Data submitted: ', formData);

  return (
    <div>
      <Form
        ref={(form) => {
          console.log(form);
          yourForm = form;
        }}
        schema={schema}
        // uiSchema={uiSchema}
        // fields={fields}
        widgets={widgets}
        validate={validate}
        // FieldTemplate={CustomFieldTemplate}
        onSubmit={onSubmit}
        noHtml5Validate
      >
        {/* <React.Fragment /> */}
        {/* <div style={{ display: 'none' }}></div> */}
      </Form>
      <button onClick={customSubmit}>我要提交</button>
    </div>
  );
}

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by dajun1230** [comment] 2021-11-19 12:52
Can clicking the custom "I want to submit" button not trigger the onsubmit event of the form？ Code above

**Comment by epicfaace** [comment] 2021-11-19 15:27
Where is your code for the  "I want to submit" button?

**Comment by dajun1230** [comment] 2021-11-19 23:59
import React from 'react';
import Form from '@rjsf/core';

import Input from '@c/input';

import { FormInput } from '@c/form-schema';

function LoginLockForm(): JSX.Element {
  let yourForm: any;
  const schema: any = {
    type: 'object',
    properties: {
      password: {
        type: 'object',
        title: '密码验证',
      },
      ip: { type: 'object', title: 'IP校验' },
    },
    required: ['password', 'ip'],
  };

  const widgets = {
    TextWidget: FormInput,
  };

  const uiSchema = { 'ui:field': 'password' };

  const fields = {
    password: PasswdFunc,
    ip: IpValidate,
  };

  function customSubmit(): void {
    yourForm.submit();
    console.log(yourForm);
    // yourForm.submit();
  }

  function validate(formData: any, errors: any): any {
    if (formData.password !== {}) {
      errors.password.addError('Passwords don\'t match');
    }
    return errors;
  }

  const onSubmit = ({ formData }: any) => console.log('Data submitted: ', formData);

  return (
    <div>
      <Form
        ref={(form) => {
          console.log(form);
          yourForm = form;
        }}
        schema={schema}
        // uiSchema={uiSchema}
        // fields={fields}
        widgets={widgets}
        validate={validate}
        FieldTemplate={CustomFieldTemplate}
        onSubmit={onSubmit}
        noHtml5Validate
      >
        {/* <React.Fragment /> */}
        {/* <div style={{ display: 'none' }}></div> */}
      </Form>
      <button onClick={customSubmit}>I want to Submit</button>
    </div>
  );
}

export default LoginLockForm;

function PasswdFunc(props: any): JSX.Element {
  const [passwdValue, setPasswdValue] = React.useState({
    isTrue: false,
    passwdLimit: 0,
    lockLimit: 0,
  });

  function handleChange(value: boolean | string, key: string): void {
    const _value = {
      ...passwdValue,
      [key]: value,
    };
    console.log(_value);
    setPasswdValue(_value);
    props.onChange(_value);
  }

  return (
    <div>
      <input type="checkbox" onChange={(e) => handleChange(e.target.checked, 'isTrue')} />
      <span>连续输错密码</span>
      <Input onChange={(value) => {
        console.log(value);
        handleChange(value, 'passwdLimit');
      }} />
      <span>次后，锁定该账户</span>
      <Input onChange={(value) => handleChange(value, 'lockLimit')} />
      <span>分钟</span>
    </div>
  );
}

function IpValidate(): JSX.Element {
  return (
    <div>
      <input type="checkbox" />
      <span>同一 IP 连续登录失败</span>
      <Input />
      <span>次后，锁定该账户</span>
      <Input />
      <span>分钟</span>
    </div>
  );
}

function CustomFieldTemplate(props: any): JSX.Element {
  const { id, classNames, label, help, required, description, rawErrors, children } = props;
  console.log(props);
  if (id === 'root') {
    return (
      <div className={classNames}>
        {children}
      </div>
    );
  }

  return (
    <div className="mb-24 flex items-center">
      <div style={{ width: '186px', textAlign: 'left' }}>
        <label htmlFor={id} className="text-14 text-secondary">
          {label}{required ? '*' : null}
        </label>
      </div>
      {/* {description} */}
      {id === 'root_password' && <PasswdFunc {...props} />}
      {id === 'root_ip' && <IpValidate {...props} />}
      {/* {rawErrors && rawErrors[0]}
      {help} */}
    </div>
  );
}

**Comment by dajun1230** [comment] 2021-11-20 00:00
> Where is your code for the "I want to submit" button?

Please look at the above code. Why can't onsubmit be triggered

**Comment by epicfaace** [comment] 2021-11-20 02:33
You should wrap it in a `<input type=submit>` tag. Also, please send a jsfiddle / codepen or format your code using markdown (see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) in the future.

**Comment by dajun1230** [comment] 2021-11-20 03:34
If it can only be placed in the children of the form, it has great limitations and cannot be satisfied. I want to call the submitted scenario externally, so this problem should be improved and optimized.

**Comment by epicfaace** [comment] 2021-11-20 03:35
That would be a duplicate of https://github.com/rjsf-team/react-jsonschema-form/issues/500, then, please take a look at that issue

**Closed by epicfaace** 2021-11-20 03:35 UTC
