### ISSUE TITLE
Support for generating JSON Schemas

### ISSUE THREAD

**Issue by IanMayo** [rjsf-team/react-jsonschema-form#1221] opened 2019-03-15 16:04 UTC
### Prerequisites

- [+] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

Has anyone used the component to let users generate JSON-Schemas?

So, the JSON meta-schema [1] would be provided in the `JSON Schema` window, which would allow the user to generate a new JSON Schema in the edit pane.

When I paste in the JSON meta-schema, I get this error:
![image](https://user-images.githubusercontent.com/1108513/54445123-0d676300-473c-11e9-8fa1-bd829fbc2795.png)

[1]. http://json-schema.org/draft-07/schema

**Comment by glasserc** [comment] 2019-04-04 19:04
No, we don't generate the schema "live", although we should support it (similar to how the playground works). On https://github.com/Kinto/kinto-admin/ we allow people to just paste in a JSON schema, but the page where you enter the schema is different from the page where you get a form.

I'm a bit confused about the error message you got. Can you please post a JSFiddle or a playground link?

**Comment by glasserc** [comment] 2019-04-04 19:05
Ah, never mind -- I guess it's just rendering the array using `.toString()`. Yeah, we don't support array `type` yet, but we might be able to using `oneOf`.

**Comment by epicfaace** [comment] 2020-09-02 10:57
Duplicate of #1465.

**Closed by epicfaace** 2020-09-02 10:57 UTC
Labels: enhancement
