### ISSUE TITLE
Setting Form prop extraErrors changes the structure of propagated error objects

### ISSUE THREAD

**Issue by iwan-uschka** [rjsf-team/react-jsonschema-form#2579] opened 2021-10-11 07:08 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

If `extraErrors` is set as a `<Form />` prop (it just needs to be an empty object) the `errors` array (in the `transformErrors` or `onError` callback) doesn't provide the same error object data structure.

With `extraErrors` being set:

```
[
  {stack: 'salutation: Is required.'},
  ...
]
```

Without `extraErrors` being set:

```
[
  {
    message: "is a required property",
    name: "required",
    params: {missing Property: 'salutation'},
    property: ".address.salutation",
    schemaPath: "#/properties/address/required",
    stack: ".address.salutation is a required property
  },
  ...
]
```

Is this behavior intentional? I couldn't find any hint in the docs.

#### Expected behavior

I would like to have internal errors being defined as detailed as possible no matter if some external `extraErrors` are brought into the error stack.

#### Actual behavior

Internal errors are becoming less detailed if external `extraErrors` are set.

See https://codesandbox.io/s/interesting-hertz-vo5ef?file=/src/App.js using `3.1.0`.

If i use the JSFiddle template from above (which is using `1.8.1` as it seems, see https://unpkg.com/react-jsonschema-form/dist/react-jsonschema-form.js) the "error" doesn't occur. See https://jsfiddle.net/01qwf23d/4/.

### Version

`3.1.0`

**Comment by hughjdavey** [comment] 2022-11-29 10:11
This also seems to happen if you use [the `customValidation` option](https://react-jsonschema-form.readthedocs.io/en/docs/usage/validation/#custom-validation-rules) - even if your custom validation function just returns `errors` unchanged like

    function validate(formData, errors) {
        return errors;
    }

**Comment by hughjdavey** [comment] 2022-11-29 11:26
I have made a JSFiddle for this - https://jsfiddle.net/mdeazLy3/1/

There are 2 forms, one with a validate function and one without. The one with the function returns truncated `error.stack`s:

![image](https://user-images.githubusercontent.com/9026053/204516979-8a5c71c4-a656-45c2-95bf-bcb0db1da9f3.png)

**Comment by hughjdavey** [comment] 2022-11-29 11:39
Since this is old I opened #3262 - let me know if that wasn't the right thing to do

**Comment by heath-freenome** [comment] 2022-12-08 23:21
> Since this is old I opened #3262 - let me know if that wasn't the right thing to do

I'll close yours as a duplicate of this one... Which, I believe, is fixed in the 5.x beta... Can you confirm?

**Comment by heath-freenome** [comment] 2022-12-08 23:29
> Since this is old I opened #3262 - let me know if that wasn't the right thing to do

@hughjdavey I'm treating #3262 as a documentation bug and will fix that one accordingly. I believe that the specific bug in this issue is already fixed in the v5 beta... Closing this accordingly

**Closed by heath-freenome** 2022-12-08 23:29 UTC
Labels: bug

**Comment by iwan-uschka** [comment] 2023-11-12 16:00
A little late but we finally are about to migrate to rjsf@5 and i can confirm that this error has been fixed. Thx!
