### ISSUE TITLE
Fields are still flagging as required even if the OneOf conditional returns false

### ISSUE THREAD

**Issue by mjemerson** [rjsf-team/react-jsonschema-form#1090] opened 2018-11-29 11:17 UTC
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

My form is quite complex and features many select boxes with OneOf dependencies. However even when one of them is attributed to false (i.e. no other fields are dependent on the selected option) the form still throws an error thinking that the fields only displayed for another option are still required to continue the form.

### Steps to Reproduce

1. Create a select box with a OneOf dependency
2. Choose an option that requires another set of values to be filled and required

#### Expected behavior

The required fields should be ignored if the dependent option is NOT chosen previously.

#### Actual behavior

Form throws an error thinking that the fields are required even though they are not visible.

### Version

1.0.4

Here is a snippet of the JSON I used to determine which fields are required when a specific option is chosen:

```
"1.11": {
          "type": "object",
          "title": "",
          "properties": {
            "1.11.1": {
              "type": "string",
              "title": "Are you acting on behalf of the PLH (e.g. the agent)",
              "default": "No",
              "enum": [
                "No",
                "Yes"
              ]
            }
          },
          "dependencies": {
            "1.11.1": {
              "oneOf": [
                {
                  "properties": {
                    "1.11.1": {
                      "enum": [
                        "No"
                      ]
                    }
                  }
                },
                {
                  "properties": {
                    "1.11.1": {
                      "enum": [
                        "Yes"
                      ]
                    },
                    "1.11.2": {
                      "type": "object",
                      "title": "Other Proposed License Holder (PLH) Details",
                      "properties": {}
                    },
                    "1.11.3": {
                      "type": "object",
                      "title": "",
                      "description": "If this application is being dealt with by a person who is not the PLH, please provide contact details below.",
                      "required": [
                        "1.11.3.1"
                      ],
                      "properties": {
                        "1.11.3.1": {
                          "type": "string",
                          "title": "Name"
                        },
....
```
In the schema.json:

```
"1.11": {
      "1.11.1": {
        "ui:widget": "selectBoxWidget"
      },
```

As you can see, if "Yes" is chosen on the select option, the field 1.11.3.1 (name) is required. However, this should be completely irrelevant if the user chooses "No" on the select box, but the schema still clocks it as "required'.

**Comment by glasserc** [comment] 2019-01-18 22:36
Is this a duplicate of #1104 ? If so, it should be fixed in 1.1.0.

**Comment by Skynet6** [comment] 2019-01-30 11:47
No it is not. It is not only for the required validation but all sorts of validations.

**Comment by epicfaace** [comment] 2019-01-31 04:19
When I try to [reproduce](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyIxLjExLjEiOiJObyIsIjEuMTEuMyI6eyIxLjExLjMuMSI6InEyIn19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInRpdGxlIjoiIiwicHJvcGVydGllcyI6eyIxLjExLjEiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiQXJlIHlvdSBhY3Rpbmcgb24gYmVoYWxmIG9mIHRoZSBQTEggKGUuZy4gdGhlIGFnZW50KSIsImRlZmF1bHQiOiJObyIsImVudW0iOlsiTm8iLCJZZXMiXX19LCJkZXBlbmRlbmNpZXMiOnsiMS4xMS4xIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7IjEuMTEuMSI6eyJlbnVtIjpbIk5vIl19fX0seyJwcm9wZXJ0aWVzIjp7IjEuMTEuMSI6eyJlbnVtIjpbIlllcyJdfSwiMS4xMS4zIjp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IiIsImRlc2NyaXB0aW9uIjoiSWYgdGhpcyBhcHBsaWNhdGlvbiBpcyBiZWluZyBkZWFsdCB3aXRoIGJ5IGEgcGVyc29uIHdobyBpcyBub3QgdGhlIFBMSCwgcGxlYXNlIHByb3ZpZGUgY29udGFjdCBkZXRhaWxzIGJlbG93LiIsInJlcXVpcmVkIjpbIjEuMTEuMy4xIl0sInByb3BlcnRpZXMiOnsiMS4xMS4zLjEiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTmFtZSJ9fX19fV19fX0sInVpU2NoZW1hIjp7IjEuMTEuMSI6e319fQ==), I don't see the error.

**Comment by epicfaace** [comment] 2019-01-31 19:03
@Skynet6 here's a [shared playground link of your schema](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJQYXJ0aWNpcGF0aW9uIjpbeyJEaXJlY3Rpb24iOiJEb3duIiwiT3B0aW9uVHlwZSI6Ik9wdGlvbjEiLCJCbHVlIjoxLCJSZWQiOjEsIlllbGxvdyI6MSwiR3JlZW4iOiJPcHRpb24yIn1dfSwic2NoZW1hIjp7IiRzY2hlbWEiOiJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA2L3NjaGVtYSMiLCIkaWQiOiJQcm9kdWN0SWQiLCJ0aXRsZSI6IlByb2R1Y3QxIiwiZGVzY3JpcHRpb24iOiJQcm9kdWN0IDEiLCJ0eXBlIjoib2JqZWN0IiwiZGVmaW5pdGlvbnMiOnsiUGFydGljaXBhdGlvbiI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJEaXJlY3Rpb24iOnsiZGVzY3JpcHRpb24iOiJEaXJlY3Rpb24iLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJEb3duIl0sImRlZmF1bHQiOiJEb3duIn0sIk9wdGlvblR5cGUiOnsiZW51bSI6WyJPcHRpb24xIiwiQ3VzdG9tT3B0aW9uMSJdLCJkZWZhdWx0IjoiT3B0aW9uMSJ9fSwicmVxdWlyZWQiOlsiRGlyZWN0aW9uIl0sImRlcGVuZGVuY2llcyI6eyJEaXJlY3Rpb24iOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiRGlyZWN0aW9uIjp7ImVudW0iOlsiRG93biJdfSwiT3B0aW9uVHlwZSI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiB0eXBlIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiT3B0aW9uMSIsIkN1c3RvbU9wdGlvbjEiXX19LCJyZXF1aXJlZCI6WyJPcHRpb25UeXBlIl0sImRlcGVuZGVuY2llcyI6eyJPcHRpb25UeXBlIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7Ik9wdGlvblR5cGUiOnsiZW51bSI6WyJPcHRpb24xIl19LCJCbHVlIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEJsdWUiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6MSwicmVhZE9ubHkiOnRydWUsIm1pbmltdW0iOjEsIm1heGltdW0iOjF9LCJSZWQiOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gUmVkIiwidHlwZSI6Im51bWJlciIsImRlZmF1bHQiOjEsInJlYWRPbmx5Ijp0cnVlLCJtaW5pbXVtIjoxLCJtYXhpbXVtIjoxfSwiWWVsbG93Ijp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIFllbGxvdyIsInR5cGUiOiJudW1iZXIiLCJtYXhpbXVtIjoxLCJtaW5pbXVtIjowfSwiR3JlZW4iOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gR3JlZW4iLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPcHRpb24xIiwiT3B0aW9uMiIsIk9wdGlvbjMiXX19LCJyZXF1aXJlZCI6WyJCbHVlIiwiUmVkIiwiWWVsbG93IiwiR3JlZW4iXX0seyJwcm9wZXJ0aWVzIjp7Ik9wdGlvblR5cGUiOnsiZW51bSI6WyJDdXN0b21PcHRpb24xIl19LCJCbHVlIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEJsdWUiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6MSwibWluaW11bSI6MH0sIlJlZCI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBSZWQiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6MSwibWluaW11bSI6MH0sIlllbGxvdyI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBZZWxsb3ciLCJ0eXBlIjoibnVtYmVyIiwibWF4aW11bSI6MSwibWluaW11bSI6MH0sIkdyZWVuIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEdyZWVuIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiT3B0aW9uMSIsIk9wdGlvbjIiLCJPcHRpb24zIl19fSwicmVxdWlyZWQiOlsiQmx1ZSIsIlJlZCIsIlllbGxvdyIsIkdyZWVuIl19XX19fV19fX0sInVuaXF1ZUl0ZW1zIjp0cnVlLCJtaW5JdGVtcyI6MSwibWF4SXRlbXMiOjF9fSwicHJvcGVydGllcyI6eyJQYXJ0aWNpcGF0aW9uIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL1BhcnRpY2lwYXRpb24ifX0sInJlcXVpcmVkIjpbIlBhcnRpY2lwYXRpb24iXX0sInVpU2NoZW1hIjp7fX0=)

1. I don't see false validation reporting. It looks like whatever value `OptionType` is, blue, red, yellow, and green are required according to the schema. These are the errors I'm getting:

![image](https://user-images.githubusercontent.com/1689183/52078303-b587ea80-2547-11e9-92dd-e1673a611331.png)

Are you talking about the error ".Participation[0].OptionType should be equal to one of the allowed values"? If so, it's probably got to do with 2) below.

2. I think that is a problem; can you create another issue for it?

**Comment by Skynet6** [comment] 2019-01-31 19:45
@epicfaace but if you for example put -1 in Red, you will get validation message for both branches.

**Comment by Skynet6** [comment] 2019-01-31 19:49
Or in this case [link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJQYXJ0aWNpcGF0aW9uIjpbeyJEaXJlY3Rpb24iOiJEb3duIiwiT3B0aW9uVHlwZSI6Ik9wdGlvbjEiLCJSZWQiOjEsIkdyZWVuIjoiT3B0aW9uMiIsIkJsdWUiOjB9XX0sInNjaGVtYSI6eyIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNi9zY2hlbWEjIiwiJGlkIjoiUHJvZHVjdElkIiwidGl0bGUiOiJQcm9kdWN0MSIsImRlc2NyaXB0aW9uIjoiUHJvZHVjdCAxIiwidHlwZSI6Im9iamVjdCIsImRlZmluaXRpb25zIjp7IlBhcnRpY2lwYXRpb24iOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiRGlyZWN0aW9uIjp7ImRlc2NyaXB0aW9uIjoiRGlyZWN0aW9uIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiRG93biJdLCJkZWZhdWx0IjoiRG93biJ9LCJPcHRpb25UeXBlIjp7ImVudW0iOlsiT3B0aW9uMSIsIkN1c3RvbU9wdGlvbjEiXSwiZGVmYXVsdCI6Ik9wdGlvbjEifX0sInJlcXVpcmVkIjpbIkRpcmVjdGlvbiJdLCJkZXBlbmRlbmNpZXMiOnsiRGlyZWN0aW9uIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7IkRpcmVjdGlvbiI6eyJlbnVtIjpbIkRvd24iXX0sIk9wdGlvblR5cGUiOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gdHlwZSIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIk9wdGlvbjEiLCJDdXN0b21PcHRpb24xIl19fSwicmVxdWlyZWQiOlsiT3B0aW9uVHlwZSJdLCJkZXBlbmRlbmNpZXMiOnsiT3B0aW9uVHlwZSI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJPcHRpb25UeXBlIjp7ImVudW0iOlsiT3B0aW9uMSJdfSwiQmx1ZSI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBCbHVlIiwidHlwZSI6Im51bWJlciIsImRlZmF1bHQiOjEsInJlYWRPbmx5Ijp0cnVlLCJtaW5pbXVtIjoxLCJtYXhpbXVtIjoxfSwiUmVkIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIFJlZCIsInR5cGUiOiJudW1iZXIiLCJkZWZhdWx0IjoxLCJyZWFkT25seSI6dHJ1ZSwibWluaW11bSI6MSwibWF4aW11bSI6MX0sIlllbGxvdyI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBZZWxsb3ciLCJ0eXBlIjoibnVtYmVyIiwibWF4aW11bSI6MSwibWluaW11bSI6MH0sIkdyZWVuIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEdyZWVuIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiT3B0aW9uMSIsIk9wdGlvbjIiLCJPcHRpb24zIl19fSwicmVxdWlyZWQiOlsiQmx1ZSIsIlJlZCIsIlllbGxvdyIsIkdyZWVuIl19LHsicHJvcGVydGllcyI6eyJPcHRpb25UeXBlIjp7ImVudW0iOlsiQ3VzdG9tT3B0aW9uMSJdfSwiQmx1ZSI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBCbHVlIiwidHlwZSI6Im51bWJlciIsImRlZmF1bHQiOjEsIm1pbmltdW0iOjB9LCJSZWQiOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gUmVkIiwidHlwZSI6Im51bWJlciIsImRlZmF1bHQiOjEsIm1pbmltdW0iOjB9LCJCbGFjay) you will get an error that Black is required but it is not in this branch.

**Comment by Skynet6** [comment] 2019-02-01 15:59
> @Skynet6 here's a [shared playground link of your schema](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJQYXJ0aWNpcGF0aW9uIjpbeyJEaXJlY3Rpb24iOiJEb3duIiwiT3B0aW9uVHlwZSI6Ik9wdGlvbjEiLCJCbHVlIjoxLCJSZWQiOjEsIlllbGxvdyI6MSwiR3JlZW4iOiJPcHRpb24yIn1dfSwic2NoZW1hIjp7IiRzY2hlbWEiOiJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA2L3NjaGVtYSMiLCIkaWQiOiJQcm9kdWN0SWQiLCJ0aXRsZSI6IlByb2R1Y3QxIiwiZGVzY3JpcHRpb24iOiJQcm9kdWN0IDEiLCJ0eXBlIjoib2JqZWN0IiwiZGVmaW5pdGlvbnMiOnsiUGFydGljaXBhdGlvbiI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJEaXJlY3Rpb24iOnsiZGVzY3JpcHRpb24iOiJEaXJlY3Rpb24iLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJEb3duIl0sImRlZmF1bHQiOiJEb3duIn0sIk9wdGlvblR5cGUiOnsiZW51bSI6WyJPcHRpb24xIiwiQ3VzdG9tT3B0aW9uMSJdLCJkZWZhdWx0IjoiT3B0aW9uMSJ9fSwicmVxdWlyZWQiOlsiRGlyZWN0aW9uIl0sImRlcGVuZGVuY2llcyI6eyJEaXJlY3Rpb24iOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiRGlyZWN0aW9uIjp7ImVudW0iOlsiRG93biJdfSwiT3B0aW9uVHlwZSI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiB0eXBlIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiT3B0aW9uMSIsIkN1c3RvbU9wdGlvbjEiXX19LCJyZXF1aXJlZCI6WyJPcHRpb25UeXBlIl0sImRlcGVuZGVuY2llcyI6eyJPcHRpb25UeXBlIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7Ik9wdGlvblR5cGUiOnsiZW51bSI6WyJPcHRpb24xIl19LCJCbHVlIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEJsdWUiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6MSwicmVhZE9ubHkiOnRydWUsIm1pbmltdW0iOjEsIm1heGltdW0iOjF9LCJSZWQiOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gUmVkIiwidHlwZSI6Im51bWJlciIsImRlZmF1bHQiOjEsInJlYWRPbmx5Ijp0cnVlLCJtaW5pbXVtIjoxLCJtYXhpbXVtIjoxfSwiWWVsbG93Ijp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIFllbGxvdyIsInR5cGUiOiJudW1iZXIiLCJtYXhpbXVtIjoxLCJtaW5pbXVtIjowfSwiR3JlZW4iOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gR3JlZW4iLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPcHRpb24xIiwiT3B0aW9uMiIsIk9wdGlvbjMiXX19LCJyZXF1aXJlZCI6WyJCbHVlIiwiUmVkIiwiWWVsbG93IiwiR3JlZW4iXX0seyJwcm9wZXJ0aWVzIjp7Ik9wdGlvblR5cGUiOnsiZW51bSI6WyJDdXN0b21PcHRpb24xIl19LCJCbHVlIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEJsdWUiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6MSwibWluaW11bSI6MH0sIlJlZCI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBSZWQiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6MSwibWluaW11bSI6MH0sIlllbGxvdyI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBZZWxsb3ciLCJ0eXBlIjoibnVtYmVyIiwibWF4aW11bSI6MSwibWluaW11bSI6MH0sIkdyZWVuIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEdyZWVuIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiT3B0aW9uMSIsIk9wdGlvbjIiLCJPcHRpb24zIl19fSwicmVxdWlyZWQiOlsiQmx1ZSIsIlJlZCIsIlllbGxvdyIsIkdyZWVuIl19XX19fV19fX0sInVuaXF1ZUl0ZW1zIjp0cnVlLCJtaW5JdGVtcyI6MSwibWF4SXRlbXMiOjF9fSwicHJvcGVydGllcyI6eyJQYXJ0aWNpcGF0aW9uIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL1BhcnRpY2lwYXRpb24ifX0sInJlcXVpcmVkIjpbIlBhcnRpY2lwYXRpb24iXX0sInVpU2NoZW1hIjp7fX0=)
> 
> 1. I don't see false validation reporting. It looks like whatever value `OptionType` is, blue, red, yellow, and green are required according to the schema. These are the errors I'm getting:
> 
> ![image](https://user-images.githubusercontent.com/1689183/52078303-b587ea80-2547-11e9-92dd-e1673a611331.png)
> 
> Are you talking about the error ".Participation[0].OptionType should be equal to one of the allowed values"? If so, it's probably got to do with 2) below.
> 
> 1. I think that is a problem; can you create another issue for it?

I've created a separate issue for point 2. Here is the [link](https://github.com/mozilla-services/react-jsonschema-form/issues/1162)

**Comment by fabri86** [comment] 2019-02-04 16:41
Hi,
since I have a similar problem as @Skynet6 , I tried to replicate his issue to verify if I could have done some mess when defining the schema, and actually I also get an error in the evaluation of the oneOf keyword.

![wrong validation oneof](https://user-images.githubusercontent.com/17066478/52222423-bf8d4e80-28a3-11e9-990a-9894469abaa4.JPG)

It looks like it is validating the absence of required fields even if we are not in the branch to be taken under examination. In the sample above, the error Black required should not be given, since we selected a value for the dropdown which must skip the evaluation of the Black field (not even visible).


How is it possible that this false positive does not appear on your machine? Could you please verify? 
Thanks

**Comment by epicfaace** [comment] 2019-02-08 21:57
@fabri86 thanks for the messages. I wasn't looking at the right link. I think the first screenshot you are mentioning is from [this playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJQYXJ0aWNpcGF0aW9uIjpbeyJEaXJlY3Rpb24iOiJEb3duIiwiT3B0aW9uVHlwZSI6Ik9wdGlvbjEiLCJCbHVlIjoxLCJSZWQiOi0xMSwiR3JlZW4iOiJPcHRpb24xIn1dLCJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsiJHNjaGVtYSI6Imh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDYvc2NoZW1hIyIsIiRpZCI6IlByb2R1Y3RJZCIsInRpdGxlIjoiUHJvZHVjdDEiLCJkZXNjcmlwdGlvbiI6IlByb2R1Y3QgMSIsInR5cGUiOiJvYmplY3QiLCJkZWZpbml0aW9ucyI6eyJQYXJ0aWNpcGF0aW9uIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IkRpcmVjdGlvbiI6eyJkZXNjcmlwdGlvbiI6IkRpcmVjdGlvbiIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkRvd24iXSwiZGVmYXVsdCI6IkRvd24ifSwiT3B0aW9uVHlwZSI6eyJlbnVtIjpbIk9wdGlvbjEiLCJDdXN0b21PcHRpb24xIl0sImRlZmF1bHQiOiJPcHRpb24xIn19LCJyZXF1aXJlZCI6WyJEaXJlY3Rpb24iXSwiZGVwZW5kZW5jaWVzIjp7IkRpcmVjdGlvbiI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJEaXJlY3Rpb24iOnsiZW51bSI6WyJEb3duIl19LCJPcHRpb25UeXBlIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIHR5cGUiLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPcHRpb24xIiwiQ3VzdG9tT3B0aW9uMSJdfX0sInJlcXVpcmVkIjpbIk9wdGlvblR5cGUiXSwiZGVwZW5kZW5jaWVzIjp7Ik9wdGlvblR5cGUiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiT3B0aW9uVHlwZSI6eyJlbnVtIjpbIk9wdGlvbjEiXX0sIkJsdWUiOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gQmx1ZSIsInR5cGUiOiJudW1iZXIiLCJkZWZhdWx0IjoxLCJyZWFkT25seSI6dHJ1ZSwibWluaW11bSI6MSwibWF4aW11bSI6MX0sIlJlZCI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBSZWQiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6MSwicmVhZE9ubHkiOnRydWUsIm1pbmltdW0iOjEsIm1heGltdW0iOjF9LCJZZWxsb3ciOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gWWVsbG93IiwidHlwZSI6Im51bWJlciIsIm1heGltdW0iOjEsIm1pbmltdW0iOjB9LCJHcmVlbiI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBHcmVlbiIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIk9wdGlvbjEiLCJPcHRpb24yIiwiT3B0aW9uMyJdfX0sInJlcXVpcmVkIjpbIkJsdWUiLCJSZWQiLCJZZWxsb3ciLCJHcmVlbiJdfSx7InByb3BlcnRpZXMiOnsiT3B0aW9uVHlwZSI6eyJlbnVtIjpbIkN1c3RvbU9wdGlvbjEiXX0sIkJsdWUiOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gQmx1ZSIsInR5cGUiOiJudW1iZXIiLCJkZWZhdWx0IjoxLCJtaW5pbXVtIjowfSwiUmVkIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIFJlZCIsInR5cGUiOiJudW1iZXIiLCJkZWZhdWx0IjoxLCJtaW5pbXVtIjowfSwiQmxhY2siOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gQmxhY2siLCJ0eXBlIjoibnVtYmVyIiwibWF4aW11bSI6MSwibWluaW11bSI6MH0sIkdyZWVuIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEdyZWVuIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiT3B0aW9uMSIsIk9wdGlvbjIiLCJPcHRpb24zIl19fSwicmVxdWlyZWQiOlsiQmx1ZSIsIlJlZCIsIkJsYWNrIiwiR3JlZW4iXX1dfX19XX19fSwidW5pcXVlSXRlbXMiOnRydWUsIm1pbkl0ZW1zIjoxLCJtYXhJdGVtcyI6MX19LCJwcm9wZXJ0aWVzIjp7IlBhcnRpY2lwYXRpb24iOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvUGFydGljaXBhdGlvbiJ9fSwicmVxdWlyZWQiOlsiUGFydGljaXBhdGlvbiJdfSwidWlTY2hlbWEiOnt9fQ==): here, I think what is happening is that the schema doesn't match either of the oneOf branches, so it's defaulting to the last branch and thus showing an error that "black" is required.

For the second screenshot you sent, do you mind sending me a shared playground link so I can replicate?

**Comment by KKS1** [comment] 2019-09-11 22:55
Any updates on this issue? This is causing us issues, for specifying required fields in the dependency tree, where its marking the fields to be required even though that dependency wasn't even true.

**Comment by epicfaace** [comment] 2019-09-12 03:00
No updates since then, although contributions are welcome to fix the issue.

**Comment by KKS1** [comment] 2019-09-14 05:17
Here is how I solved the issue. Might be helpful to anyone else facing it.

Basically, two approaches can be taken here:
Approach One:-

Make sure that each branch object in the 'oneOf' tree has a 'required' property. Put 'required: []' if nothing is a must have for that tree branch.

Approach Two:-

Remove 'required' from all the branches, and move them in an 'if else' based 'Ajv' condition, eg:

 "if": {
          "properties": {
            "SomeProp": {
              "enum": ["propValueOne"]
            }
          }
        },
        "then": {
          "required": [
            "propOne",
            "propTwo",
          ]
        },
        "else": {
          "required": [ ],
        }

https://ajv.js.org/keywords.html#ifthenelse

Along with this, using 'not' keyword (Ajv lib) will be super handy for cases where approach One is suitable.

Thanks!

**Closed** 2023-06-25 20:36 UTC
Labels: bug, core, possibly close
