### ISSUE TITLE
Material UI not respecting ui:options label=false

### ISSUE THREAD

**Issue by kaos** [rjsf-team/react-jsonschema-form#1769] opened 2020-05-22 13:53 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCIsInRlbGVwaG9uZSI6IjEyMzQzNDUzNjUifSwic2NoZW1hIjp7InRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJmaXJzdE5hbWUiLCJsYXN0TmFtZSJdLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaXJzdCBuYW1lIiwiZGVmYXVsdCI6IkNodWNrIn0sImxhc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ikxhc3QgbmFtZSJ9LCJhZ2UiOnsidHlwZSI6ImludGVnZXIiLCJ0aXRsZSI6IkFnZSJ9LCJiaW8iOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiQmlvIn0sInBhc3N3b3JkIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlBhc3N3b3JkIiwibWluTGVuZ3RoIjozfSwidGVsZXBob25lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRlbGVwaG9uZSIsIm1pbkxlbmd0aCI6MTB9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJsYWJlbCI6ZmFsc2UsImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoibWF0ZXJpYWwtdWkiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=) demonstrating the issue.

### Description

Setting label=false in the ui:options works as expected for the default theme, but not for material-ui.

### Steps to Reproduce

Added `label=false` for the telephone field in the uiSchema for the Simple demo at the playground.
![image](https://user-images.githubusercontent.com/72965/82674836-2de65380-9c44-11ea-8926-a3a8be428b72.png)

1. Go to playground linked above.
2. Switch between default and mui themes
3. Observe that the "Telephone" input have a label for the mui theme, but not for the default theme.

#### Expected behavior

Expected would be no label for the mui theme as well.

![image](https://user-images.githubusercontent.com/72965/82674923-49515e80-9c44-11ea-9945-c6a82cefe729.png)

#### Actual behavior

The telephone label is still present on the mui theme, although the ui option label was set to false for the telephone field.

![image](https://user-images.githubusercontent.com/72965/82674888-3e96c980-9c44-11ea-8677-d3119166047f.png)

### Version

Current at playground.

**Comment by stanlemon** [comment] 2020-06-09 02:03
@epicfaace I think this could be done with an easy fix following #1790 and it would cascade against almost all of the widgets. I would be happy to give it a shot if you're ok with that.

**Comment by stanlemon** [comment] 2020-06-09 23:41
#1807 is based off of #1790 so it includes that code until that one gets sorted. The fix for this is in ee1047dab056908c04af23720248544280e962ac (I also added uiSchema because it feels like I'm going to need this next...). I'm not crazy about this solution but I'm not seeing another alternative at the moment so if you have any ideas @epicfaace let me know.

**Comment by newt10** [comment] 2021-09-03 01:21
I tried to reproduce this in playground and can't reproduce it anymore. @kaos can you confirm if this is still a problem? If so can you share you schema/uiSchema along with it to help debug this.

#### Screenshot of playground

![MUI label hidden](https://user-images.githubusercontent.com/42853152/131936194-26821889-7423-40f4-b6ad-36da86ce155a.png)

I am closing this as not reproducible. Please re-open if the issue still persists.

**Closed by newt10** 2021-09-03 01:21 UTC
Labels: bug, help wanted, uiSchema, material-ui

**Comment by kaos** [comment] 2021-09-03 11:01
Yeah, it works as expected now. Thanks!
