### ISSUE TITLE
Making API Call before control renders

### ISSUE THREAD

**Issue by rajaveernapu** [rjsf-team/react-jsonschema-form#2008] opened 2020-08-21 18:52 UTC
### Prerequisites

- [X]  I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
I have 2 controls which needs to be rendered 
1- Auto Complete text box
2- Country and City dropdowns
### Steps to Reproduce

Define the properties in JSON schema for a dropdown , before it gets rendered, it should make a call and display values in dropdown
Define a textbox which should make an API call when user enters 3 or 4 letters in the text box and show a menu 

#### Expected behavior
Dynamically fetch values of the control

**Comment by epicfaace** [comment] 2020-08-30 22:37
Closing this as a duplicate of #809, I think. You can also implement this as a custom widget.

**Closed by epicfaace** 2020-08-30 22:37 UTC

**Comment by raratiru** [comment] 2021-05-08 16:11
@epicfaace 

An example would be very helpful. Following the [docs](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/#adding-your-own-custom-widgets) and trying to grossly mutate `enumOptions` array, has no effect:
```javascript

const schema = {
  type: "string",
  // enum: ["one", "two", "three"]
};

const CustomSelectWidget = function(props) {
  props.options.enumOptions = [{"label": "1", "value": "1"}];
  console.log(props.options.enumOptions);  // logs OK, but values do not appear in dropdown
  console.log(props);
  return <SelectWidget {...props} />
};

const widgets = {
  SelectWidget: CustomSelectWidget
};

const uiSchema = {
  "ui:widget": "SelectWidget" 
};

function App() {
  return (
    <Form schema={schema} uiSchema={uiSchema} widgets={widgets} />
  );
}
```
