### ISSUE TITLE
Error when nullable array is null

### ISSUE THREAD

**Issue by mazikeens** [rjsf-team/react-jsonschema-form#1346] opened 2019-07-08 14:28 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Unrecoverable error when nullable array is null
This is similar to #1300 however this issue specifically mentions nullable array type without default value

### Steps to Reproduce

1. Check console in [playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJyZXF1ZXN0IjpudWxsfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InJlcXVlc3QiOnsidHlwZSI6WyJhcnJheSIsIm51bGwiXSwiaXRlbXMiOnsidHlwZSI6InN0cmluZyJ9fX19LCJ1aVNjaGVtYSI6e319)

#### Expected behavior

Empty array widget should render

#### Actual behavior

Unrecoverable error

### Version

1.6.1

**Comment by amy-keibler** [comment] 2019-11-16 20:38
Would it be possible for you to add the JSONSchema/UISchema/formData values from your playground example? Your example crashes in the same way as an issue I'm currently observing, but I'm not sure if it is for the same reason (`null` form data for an array type field should probably be converted to an empty list) since the playground link fails to render. I want to fix the issue and I don't want to open a PR for your issue that addresses my problem and not yours. Thanks!

**Comment by epicfaace** [comment] 2019-11-30 23:37
@amy-keibler 

You can find the values by doing `atob("eyJmb3JtRGF0YSI6eyJyZXF1ZXN0IjpudWxsfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InJlcXVlc3QiOnsidHlwZSI6WyJhcnJheSIsIm51bGwiXSwiaXRlbXMiOnsidHlwZSI6InN0cmluZyJ9fX19LCJ1aVNjaGVtYSI6e319")`

to get

```

{"formData":{"request":null},"schema":{"type":"object","properties":{"request":{"type":["array","null"],"items":{"type":"string"}}}},"uiSchema":{}}

```

**Comment by richmahn** [comment] 2020-05-22 15:54
Also experiencing this problem. Proper JSON schema should allow this to be null or any array. I have tons of JSON files that have their field set to "null" but some have an array there. If I pull in the former, I get an error and it crashes.

**Comment by jsani-radar** [comment] 2021-01-28 22:23
also was able to reproduce this problem with the following data -
formData:
```
{ tags: null }
```
schema:
```
{
  "type": "object",
  "properties": {
    tags: {
      "type": [
        "array",
        "null"
      ],
      "title": "tags",
      "items": {
        "type": "string"
      }
    }
  }
}
```
UI schema:
```
{
  "ui:options": {
    "orderable": false
  },
  "ui:emptyValue": []
}
```
seems like perhaps the form doesn't recognize `null` as a signal to apply the `emptyValue` UI property?

**Comment by epicfaace** [comment] 2021-01-29 20:14
Fixed by https://github.com/rjsf-team/react-jsonschema-form/pull/2154.

**Closed by epicfaace** 2021-01-29 20:14 UTC
Labels: bug
