### ISSUE TITLE
Form validation hook (to use outside of onSubmit)

### ISSUE THREAD

**Issue by candycanetrain** [rjsf-team/react-jsonschema-form#1006] opened 2018-08-17 21:12 UTC
### Prerequisites

- [yes ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [yes] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I want to call the form validation function elsewhere (outside of clicking the submit button). Is there a way to do it?

My use case involves creating a drop down menu, where each selection displays a different json-schema-form. There's a submit button, but it's to submit a collection of form data. I want to be able to validate each form when the user switches a selection.

#### Expected behavior

A form validation hook is available for me to invoke outside of calling onSubmit.

### Version

"react-jsonschema-form": "^1.0.2"

**Comment by glasserc** [comment] 2018-08-24 20:29
There is a `Form#validate` function. Does this not do what you want?

**Comment by xero88** [comment] 2018-08-27 15:15
@glasserc I got TypeError: __WEBPACK_IMPORTED_MODULE_5_react_jsonschema_form___default.a.validate is not a function

        `Form`.validate(value);

**Comment by llamamoray** [comment] 2018-08-28 15:46
@xero88 I'm using the validate method on the form. Are you getting a ref to your form and calling validate on that?

**Comment by kylehalleman** [comment] 2018-09-04 15:58
I am also running into this issue. Using a custom `SchemaField` instead of `Form`, but would like to call the library's validate on the `SchemaField`. Not seeing how to do this. Even tried re-working to use `Form` instead, but calling `Form#validate` needs to be on the instance and not the class (would be nice if it were possible to make `validate` a static).

**Comment by kylehalleman** [comment] 2018-09-24 20:47
@doncesarts I think this is still a valid issue. Using the techniques outlined in #500, you're still triggering a submit, which just happens to validate. If validation passes, the form submits. That is not always desired, sometimes just a validation is required. Looking at the source code `Form#validate` requires an instance of the class. Would it be possible to make `validate` a static method on the `Form` class? Or expose some other way to _only_ run validation without having to use a hack that _also_ triggers submit?

Thank you for your time.

**Comment by glasserc** [comment] 2018-09-27 15:49
I still don't really understand the use case here. @kylehalleman Are you saying you don't actually use the `Form` class at all, but interact with the whole thing using `SchemaField`? Out of curiosity, why? I always expected the main entry point for this library would be `Form`, but we expose the different `Field` classes so you can subclass them if you want.

The `Form#validate` method isn't very complicated, especially once you subtract the stuff that is instance-related. It uses two functions (`retrieveSchema` and `validateFormData`) which are exported. I still don't understand why you would, but surely you could use those directly?

**Comment by kylehalleman** [comment] 2018-09-27 16:30
We use both the `Form` class and `SchemaField`. We have a similar project to [Kinto Formbuilder](https://github.com/Kinto/formbuilder), where there is both a form for showing the fields that have been created and will be used by the end user, but also subforms that are used to edit those fields.

Specific to the need to validate without submitting, one of the custom widgets we created for editing a drop down list form field is the ability to add options to a `select` both via array fields and also using a `textarea` "bulk editor". The user can switch between both of those interfaces within the edit form.

In the scenario we've run into: A user enters two options in the array field, but they are duplicates and when hitting submit, gets validation errors for this. The user then switches to the "bulk editor" `textarea`, fixes the validation issue, and switches back to the array field layout, but the validation error messages persist. In this scenario we'd want to run validation when they switch from the bulk editor to the array field layout, without hitting submit on the form.

I can make a CodePen if that would help clear things up some more. However, I will try using the `retrieveSchema` and `validateFormData` methods as @glasserc described.

@llamamoray Thanks, I will look into using the ajv validate method directly if the above does not work. The reason I can't call validate on the form instance is where we would want to call the validate method is higher up in the component tree and even when rendering the `Form` component itself, we do not have access to the instance.

**Comment by candycanetrain** [comment] 2018-09-27 17:44
Since I had to implement it semi-urgently, I ended it up just using `document.getElementById(${ID_NAME}').reportValidity()`; to trigger a validation. It's not the best way though.

**Comment by vilchesalves** [comment] 2019-08-27 23:16
> Since I had to implement it semi-urgently, I ended it up just using `document.getElementById(${ID_NAME}').reportValidity()`; to trigger a validation. It's not the best way though.

Nice suggestion.

I ended up with something like:

```
const FormContainer = () => {
  const formRef = React.useRef(null);
  
  const checkValidation = () => {
    console.log(formRef.current.formElement.reportValidity());
  } 

  return (
    <Form
      ref={formRef}
    >
      <button onClick={checkValidation}>check validation</button>
    </Form>
  )
}
```

**Comment by saswat3115** [comment] 2020-04-22 16:17
formRef.current.formElement.reportValidity()

This works great. Nice. Thanks for the suggestion. I was strugling like anything to find a way for this.

**Comment by 5arg** [comment] 2020-09-16 13:56
> formRef.current.formElement.reportValidity()
> 
> This works great. Nice. Thanks for the suggestion. I was strugling like anything to find a way for this.

I don't have the formElement object on the current ref. This is what I get when i console log it:

![image](https://user-images.githubusercontent.com/37589694/93347276-2bcc8400-f835-11ea-9cbf-58350a7d9ec4.png)

**Comment by AlexMachin1997** [comment] 2021-03-10 12:03
How did you attach a ref to the actual <Form/> ?

I've implemented this library at work and we created a custom component which uses the useTheme utility for generating our React-JSONSchema-Form stuff, though I would like to access the form props outside the Form component ie in an <ActionBar/> on the same page. Basically I want to save data before we do an action e.g. Expanding/Closing all Accordions on the page.

What happens currently is the form data is reset, but if I could get access to the current form data I could save the data before hand :) 

Any guidance would be great 😉

**Comment by litzebauer** [comment] 2021-05-14 19:55
When I called `Form#validate` I get back the errors but the errors are fields themselves are not showing the error messages.  Is that the expected behavior?  If so, how can I programmatically trigger validation that will have the form show the error messages?

**Comment by heath-freenome** [comment] 2022-09-19 18:50
Fixed in the v5 beta.9 - https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/#validate-form-programmatically

**Closed by heath-freenome** 2022-09-19 18:50 UTC
Labels: awaiting response
