### ISSUE TITLE
Basic example in the docs not working

### ISSUE THREAD

**Issue by pathum-kalhan** [rjsf-team/react-jsonschema-form#3295] opened 2022-12-15 06:27 UTC
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.0.0-beta.14

### Current Behavior

This is my code
```
import React from "react";
import validator from "@rjsf/validator-ajv8";
import Form from "@rjsf/core";

export default function Test() {
  const schema = {
    title: "Todo",
    type: "object",
    required: ["title"],
    properties: {
      title: { type: "string", title: "Title", default: "A new task" },
      done: { type: "boolean", title: "Done?", default: false }
    }
  };
// @ts-ignore
  const log = (type) => console.log.bind(console, type);

  return (
    <Form
    // @ts-ignore
      schema={schema}
      validator={validator}
      onChange={log("changed")}
      onSubmit={log("submitted")}
      onError={log("errors")}
    />
  );
}
```

When I tried to run this I am getting this error

```
[./node_modules/@rjsf/validator-ajv8/dist/validator-ajv8.esm.js 441:44
Module parse failed: Unexpected token (441:44)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|   isValid(schema, formData, rootSchema) {
>     const rootSchemaId = rootSchema["$id"] ?? ROOT_SCHEMA_PREFIX;
| 
|     try {](url)
```
These are the versions I am using
```
 "@rjsf/core": "^5.0.0-beta.14",
    "@rjsf/utils": "^5.0.0-beta.14",
```
Also, I tried the same thing in the code sandbox https://codesandbox.io/s/wizardly-wilson-nunesg?file=/src/App.js:0-625
There I am getting this error
`Could not find module in path: 'ajv8' relative to '/node_modules/@rjsf/validator-ajv8/dist/validator-ajv8.esm.js'`

### Environment

```markdown
- OS:Ubuntu 22.04.1 LTS
- Node:v19.2.0
- npm:8.19.3
```

**Comment by heath-freenome** [comment] 2022-12-16 16:24
This is a duplicate of #3240, closing

**Closed by heath-freenome** 2022-12-16 16:24 UTC
Labels: bug, needs triage

**Comment by nickgros** [comment] 2022-12-16 16:28
The error `Could not find module in path: 'ajv8' relative to '/node_modules/@rjsf/validator-ajv8/dist/validator-ajv8.esm.js'` is caused by a workaround that we used to fix our own module resolution issues in the playground. It's unclear if this is a CodeSandbox issue or if the issue can be encountered in other environments.
