### ISSUE TITLE
AnyOf/OneOf Merge Top Level Schema

### ISSUE THREAD

**Issue by cwendtxealth** [rjsf-team/react-jsonschema-form#3808] opened 2023-08-02 22:28 UTC
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.11.x

### Current Behavior

In 5.11 there is a fix [merging top level schema](https://github.com/rjsf-team/react-jsonschema-form/commit/2a8b4ca6dd02cfd25dd5b8e740523d098265ee49#diff-101261e0251acc18654c86a51caa1e7241d23831878757b2eb1a4a57241708f0R178) of oneOf/anyOf into the selected option field. This adds duplicated field on the UI; is this expected behavior? Before the fix it still had the top level field correctly and then showed the selected anyOf/oneOf fields.

Here is [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwidGl0bGUiOiJNZXJnZXMgaW50byBhbnlPZiIsInJlcXVpcmVkIjpbImJheiJdLCJwcm9wZXJ0aWVzIjp7ImJheiI6eyJ0eXBlIjoibnVtYmVyIn19LCJhbnlPZiI6W3sicHJvcGVydGllcyI6eyJmb28iOnsidHlwZSI6InN0cmluZyJ9fX0seyJwcm9wZXJ0aWVzIjp7ImJhciI6eyJ0eXBlIjoic3RyaW5nIn19fV19LCJ1aVNjaGVtYSI6eyJydWxlQ29uZGl0aW9ucyI6eyJpdGVtcyI6eyJjb25kaXRpb24iOnsidWk6d2lkZ2V0IjoiaGlkZGVuIn19fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn19fQ==) of the schema that is used in the unit test. Here is what is looks like
<img width="1485" alt="image" src="https://github.com/rjsf-team/react-jsonschema-form/assets/54559756/3217f5a5-e7d3-47c1-973e-0c635c6e54b8">

Before fix:
<img width="2425" alt="image" src="https://github.com/rjsf-team/react-jsonschema-form/assets/54559756/29505b60-a567-4718-ac30-64712a50cb60">

### Expected Behavior

Only show the field once

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by heath-freenome** [comment] 2023-08-04 15:18
I believe that this is actually a duplicate of #3787, at least in its solution:

This requires implementing a new feature similar to `ui:fieldReplacesAnyOrOneOf` except that it would be `ui:anyOrOneOfReplacesField`. In the `SchemaField` we render both the field and the `anyOf`/`oneOf`. With this flag turned on then I would imagine that the `field` being rendered on [line 288](https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/core/src/components/fields/SchemaField.tsx#L288) is skipped since the `anyOf`/`oneOf` will do it. This would required some verification of it working properly, including some decent unit tests. We could use some help for this.

**Comment by cwendtxealth** [comment] 2023-08-04 16:48
@heath-freenome just from some quick initial tests when anyOf/oneOf schema field is present not rendering the top field works. However in my opinion I think it makes more sense to keep the top common field and then have it removed from the anyOf/oneOf options schema. Just from a UI prospective that field will be the same across all anyOf/oneOf options so having at the top outside I think is a nice visual of the schema.

I wanted to get your thoughts on possibly that type of solution. Im not sure exactly the best way of solving that. Two solutions come to mind

1. If the ui flag is set remove the top level properties before passing the anyOf/oneOf schema to the components
2. if the ui flag is set, in the `MultiSchemaField` hide the top level property widget in the anyOf/oneOf component

**Comment by heath-freenome** [comment] 2023-08-04 17:11
Can you show me screenshots of what you have working now?

**Comment by cwendtxealth** [comment] 2023-08-04 18:19
Sure, I am using the example from this [issue](https://github.com/rjsf-team/react-jsonschema-form/issues/3787) as it has a little more complexity to show.

So here is the view without any changes (current). The important field is `Select Application Type` as that controls all of the if then statements. And you can see the duplication of that field and `Untitled Design`
<img width="1684" alt="image" src="https://github.com/rjsf-team/react-jsonschema-form/assets/54559756/fa388d99-d9a5-440c-8101-bfa7b9bc00b5">

Here is the view when not rendering the top level field and only showing anyOf/oneOf component. This solves the duplicate fields but I don't like this option as much because of two things. One you don't see the top level title anymore `Upload Design File` and now its hard to really tell which field is the driving factor for changing the if/then schema. In the one above because its at the top if gives you a better visual of the hierarchy. 
<img width="1677" alt="image" src="https://github.com/rjsf-team/react-jsonschema-form/assets/54559756/64f2e992-5ae1-4b5d-8586-0e2e8493928b">

Here is one of the solutions I suggested, where I am removing the top level properties in the schema before passing the anyOf/oneOf schema. This to me is the best solution for visually showing the schema as it keeps the top level fields and title while not repeating them in the oneOf/anyOf options. The only thing I don't know is if there are any side effects from not passing the full schema with top level properties of the anyOf/oneOf schema.
<img width="1679" alt="image" src="https://github.com/rjsf-team/react-jsonschema-form/assets/54559756/ec83b56b-3b7c-4062-96ec-28b9e758aef3">

**Closed** 2023-08-14 14:29 UTC
Labels: help wanted, feature
