### ISSUE TITLE
Add class like has-error to help style individual non-validating fields 

### ISSUE THREAD

**Issue by jmatsushita** [rjsf-team/react-jsonschema-form#384] opened 2016-11-09 18:23 UTC
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

The `has-error` class is applied to the parent of a nested object when validation of a required nested object property fails.

It means that until the user clicks "Submit" (which will display the " Please fill out this field" tooltip, there is no way (that I know off) to style individual fields that don't (live) validate.

### Steps to Reproduce

1.  Use schema:

```jsx
{
  "title": "A list of tasks",
  "type": "object",
  "required": [
    "title"
  ],
  "properties": {
    "title": {
      "type": "string",
      "title": "Task list title"
    },
    "tasks": {
      "type": "object",
      "title": "Tasks",
      "required": [
        "title"
      ],
      "properties": {
        "title": {
          "type": "string",
          "title": "Title",
          "description": "A sample title"
        },
        "details": {
          "type": "string",
          "title": "Task details",
          "description": "Enter the task details"
        },
        "done": {
          "type": "boolean",
          "title": "Done?",
          "default": false
        }
      }
    }
  }
}
```

2. The containing parent field have a `has-error` class

![image](https://cloud.githubusercontent.com/assets/356097/20149455/a28f1f8c-a6b1-11e6-8691-f0890004dc81.png)

#### Expected behavior

Rather desired behavior would be to have a `has-error` class on individual field elements that don't validate. Or maybe a `has-field-error` to help distinguish the failing nested objects from the fields themselves.

#### Actual behavior

The individual field doesn't have a class that could help with providing live feedback about problem fields:

![image](https://cloud.githubusercontent.com/assets/356097/20149486/cf28a9c8-a6b1-11e6-9ecf-582d0c4a50a1.png)

### Version

This was tested with the live version on https://mozilla-services.github.io/react-jsonschema-form/

**Comment by jmatsushita** [comment] 2016-11-09 20:50
I see this is being discussed here #351 and seems doable with `FieldTemplate`s already. I also now realise that the `required` constraint is attached to the parent property, so the default makes sense although it's not the best UX.

**Comment by maartenth** [comment] 2016-11-15 07:45
I think we can parse the error message and pass the error through to the missing field(s), instead of the entire object. That would be better UX in my opinion.

**Comment by n1k0** [comment] 2016-11-15 08:10
> I think we can parse the error message and pass the error through to the missing field(s), instead of the entire object. That would be better UX in my opinion.

This. I don't like the idea of parsing error messages though, but I don't have any better option.

**Comment by maartenth** [comment] 2016-11-15 08:28
I looked around a little bit and I found this JSON schema [validator benchmark](https://github.com/ebdrup/json-schema-benchmark), in which the winner ([ajv](https://github.com/epoberezkin/ajv)) has this option:

> `errorDataPath`: set dataPath to point to 'object' (default) or to 'property' when validating keywords required, additionalProperties and dependencies.

With this, we wouldn't need to parse the error message.

As a sidenote, the currently used validation library just scores 0.9% in that benchmark...

**Comment by n1k0** [comment] 2016-11-15 08:31
> As a sidenote, the currently used validation library just scores 0.9% in that benchmark...

I know, I've been postponing on switching to something better, especially for l10n purpose, but it's a bunch of work. Would be amazing if you start working on this ;)

**Comment by maartenth** [comment] 2016-11-15 08:39
I should take a month off to work on this library. ;)

But OK it may be better to first switch to another validation library, and then fix this issue with required fields UX. I may be able to do that (and other features) in a few weeks.

**Comment by n1k0** [comment] 2016-11-15 09:27
We can probably fix the issue with required fields without switching to another validation library. It's just that it would kill many birds with a single gigantic stone. Still, we should probably just iterate here.

**Comment by damanpant** [comment] 2017-07-19 07:22
Do we have a solution yet for this issue ? Non required filed is highlighted red .Plz help

**Comment by mkoppanen** [comment] 2017-07-29 19:13
+1 for this. The UX is confusing as it is

**Comment by newt10** [comment] 2021-09-03 18:41
This issue is likely fixed with the related PRs. I am also not able to reproduce this in the latest version so closing it. @jmatsushita can you confirm if this is still a problem and re-open if necessary.

**Closed by newt10** 2021-09-03 18:41 UTC
Labels: enhancement, help wanted
