### ISSUE TITLE
Object Field Title Not Working After Changing Additionalproperties Key

### ISSUE THREAD

**Issue by AndrewWUw** [rjsf-team/react-jsonschema-form#2522] opened 2021-08-19 05:35 UTC
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

For object type fields with additionalProperties, if you change the additional property's key name, the entire object title will changed.

### Steps to Reproduce

1. [Sample here](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYXNzS2lja0NvdW50IjoiaW5maW5pdHkifSwic2NoZW1hIjp7InRpdGxlIjoiQSBjdXN0b21pemFibGUgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gd2l0aCBhZGRpdGlvbmFsIHByb3BlcnRpZXMgZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiZmlyc3ROYW1lIiwibGFzdE5hbWUiXSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOnsidHlwZSI6InN0cmluZyJ9LCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaXJzdCBuYW1lIn0sImxhc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ikxhc3QgbmFtZSJ9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIifX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=).
2. Notice the default title for firstName & lastName uses the title defined in schema.
![image](https://user-images.githubusercontent.com/3378286/130013351-6348c03a-e4f7-4916-8047-82bebfd58119.png)
3. Change the assKickCount property key. the firstName & lastName change to the default field name.
![image](https://user-images.githubusercontent.com/3378286/130013501-97c2fa11-c935-41dc-867b-cb34f0d4895f.png)

#### Expected behavior

Only the additional properties title changes.

#### Actual behavior

Both the addition properties and the parent object's title label changed.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by heath-freenome** [comment] 2023-03-04 21:02
Closing as I cannot reproduce this in the 5.x release

**Closed by heath-freenome** 2023-03-04 21:02 UTC
Labels: bug, core, object, cannot-reproduce
