### ISSUE TITLE
oneOf change of default behaviour

### ISSUE THREAD

**Issue by jam13** [rjsf-team/react-jsonschema-form#4377] opened 2024-11-12 14:38 UTC
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

5.x

### Current Behavior

oneOf used to behave like enum in that it defaulted to undefined unless a default had been specified. It is now defaulting to the first item in the oneOf list.

### Expected Behavior

oneOf should behave the same as enum and default to undefined.

### Steps To Reproduce

https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJvbmVPZk5vRGVmYXVsdCI6InllcyIsIm9uZU9mTnVsbERlZmF1bHQiOm51bGx9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZW51bU5vRGVmYXVsdCI6eyJ0aXRsZSI6ImVudW1OYW1lcywgbm8gZGVmYXVsdCIsImVudW0iOlsieWVzIiwibm8iXX0sIm9uZU9mTm9EZWZhdWx0Ijp7InRpdGxlIjoib25lT2YsIG5vIGRlZmF1bHQiLCJ0eXBlIjoic3RyaW5nIiwib25lT2YiOlt7ImNvbnN0IjoieWVzIiwidGl0bGUiOiJZZXMifSx7ImNvbnN0Ijoibm8iLCJ0aXRsZSI6Ik5vIn1dfSwib25lT2ZOdWxsRGVmYXVsdCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJvbmVPZiwgbnVsbCBkZWZhdWx0IiwiZGVmYXVsdCI6bnVsbCwib25lT2YiOlt7ImNvbnN0IjoieWVzIiwidGl0bGUiOiJZZXMifSx7ImNvbnN0Ijoibm8iLCJ0aXRsZSI6Ik5vIn1dfX19LCJ1aVNjaGVtYSI6eyJlbnVtTm9EZWZhdWx0Ijp7InVpOndpZGdldCI6IlJhZGlvV2lkZ2V0IiwidWk6ZW51bU5hbWVzIjpbIlllcyIsIk5vIl19LCJvbmVPZk5vRGVmYXVsdCI6eyJ1aTp3aWRnZXQiOiJSYWRpb1dpZGdldCJ9LCJvbmVPZk51bGxEZWZhdWx0Ijp7InVpOndpZGdldCI6IlJhZGlvV2lkZ2V0In19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6eyJwb3B1bGF0ZSI6InBvcHVsYXRlIiwibWVyZ2VFeHRyYURlZmF1bHRzIjpmYWxzZX0sImFsbE9mIjoic2tpcERlZmF1bHRzIiwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIiwibWVyZ2VEZWZhdWx0c0ludG9Gb3JtRGF0YSI6InVzZUZvcm1EYXRhSWZQcmVzZW50In19fQ==

### Environment

```markdown
N/A
```

**Comment by MarekBodingerBA** [comment] 2024-11-14 12:35
Duplicate of https://github.com/rjsf-team/react-jsonschema-form/issues/4361

**Closed as completed** 2024-11-22 20:33 UTC
Labels: bug, duplicate issue
