### ISSUE TITLE
Disable select box based on checking a checkbox

### ISSUE THREAD

**Issue by jorisw** [rjsf-team/react-jsonschema-form#2528] opened 2021-08-28 13:41 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Since there is no forum or chat, I assume Issues is the place for questions.

I want to show a "Choose your ISP" select box, but with a checkbox "I don't have one" underneath, that disables the select box. How do I do this? There is no UISchema as part of a oneOf clause.

[Playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJub19pc3AiOmZhbHNlfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5vX2lzcCI6eyJ0aXRsZSI6IldobyBpcyB5b3VyIElTUCA/IiwidHlwZSI6ImJvb2xlYW4iLCJlbnVtIjpbdHJ1ZSxmYWxzZV0sImRlZmF1bHQiOmZhbHNlfX0sInJlcXVpcmVkIjpbImlzcCJdLCJkZXBlbmRlbmNpZXMiOnsibm9faXNwIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7Im5vX2lzcCI6eyJ0eXBlIjoiYm9vbGVhbiIsImVudW0iOltmYWxzZV19LCJpc3AiOnsidGl0bGUiOiJXaG8gaXMgeW91ciBJU1A/IiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiY2luZ3VsYXIiLCJ2ZXJpem9uIl0sImVudW1OYW1lcyI6WyJDaW5ndWxhciIsIlZlcml6b24iXX19fSx7InByb3BlcnRpZXMiOnsibm9faXNwIjp7InR5cGUiOiJib29sZWFuIiwiZW51bSI6W3RydWVdfSwiaXNwIjp7InRpdGxlIjoiV2hvJ3MgeW91ciBJU1A/IiwidHlwZSI6InN0cmluZyIsImRpc2FibGVkIjp0cnVlLCJlbnVtIjpbXX19fV19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

```json
{
        "type": "object",
        "properties": {
            "no_isp": {
            "title": "Who is your ISP ?",
            "type": "boolean",
            "enum": [
                true,
                false
            ],
            "default": false
            }
        },
        "required": [
            "isp"
        ],
        "dependencies": {
            "no_isp": {
            "oneOf": [
                {
                    "properties": {
                        "no_isp": {
                            "type": "boolean",
                            "enum": [
                                false
                            ]
                        },
                        "isp": {
                            "title": "Who is your ISP?",
                            "type": "string",
                            "enum": [
                                "cingular",
                                "verizon"
                            ],
                            "enumNames": [
                                "Cingular",
                                "Verizon"
                            ]
                        }
                    }
                },
                {
                    "properties": {
                        "no_isp": {
                            "type": "boolean",
                            "enum": [
                                true
                            ]
                        },
                        "isp": {
                            "title": "Who's your ISP?",
                            "type": "string",
                            "disabled": true, <---- Doesn't work
                            "enum": []
                        }
                    }
                }
            ]
        }
    }
```

**Comment by newt10** [comment] 2021-09-06 17:49
I was able to get the desired effect with slight modification to schema.

use `"readOnly": true` in place of disabled to get the desired effect. See the modified schema.

```
{
  "type": "object",
  "properties": {
    "no_isp": {
      "title": "Who is your ISP ?",
      "type": "boolean",
      "enum": [
        true,
        false
      ],
      "default": false
    }
  },
  "dependencies": {
    "no_isp": {
      "oneOf": [
        {
          "properties": {
            "no_isp": {
              "type": "boolean",
              "enum": [
                false
              ]
            },
            "isp": {
              "title": "Who is your ISP?",
              "type": "string",
              "enum": [
                "cingular",
                "verizon"
              ],
              "enumNames": [
                "Cingular",
                "Verizon"
              ]
            }
          }
        },
        {
          "properties": {
            "no_isp": {
              "type": "boolean",
              "enum": [
                true
              ]
            },
            "isp": {
              "title": "Who's your ISP?",
              "type": "string",
              "readOnly": true
            }
          }
        }
      ]
    }
  }
}
```

 
![Screen Shot 2021-09-06 at 10 44 40 AM](https://user-images.githubusercontent.com/42853152/132250045-5aeb143e-66ca-4a81-804f-c55f1f928524.png)

I believe 'disabled' is a propety used in [uiSchema](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/uiSchema/#disabled) and not valid [JSONSchema keyword](http://json-schema.org/understanding-json-schema/index.html) 

Closing this as not a bug. Please re-open if you feel that this is a bug.

**Closed by newt10** 2021-09-06 17:49 UTC
Labels: discussion

**Comment by jorisw** [comment] 2021-09-08 12:22
Thanks, this helps, however readOnly isn't quite the same as disabled: it still allows the user to interact with an input that is no longer valid.
