### ISSUE TITLE
What is the recommended approach to translate labels, descriptions, etc?

### ISSUE THREAD

**Issue by bjbrewster** [rjsf-team/react-jsonschema-form#739] opened 2017-10-25 03:08 UTC
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I am attempting to implement label/description/help translation using react-intl in a custom FieldTemplate and am trying to get the path to the current field.  I can almost use the id property like `id.split('_').slice(1)` except field names may have `_` as part of their name, and the root id name can change (uiSchema["ui:rootFieldId"]) and may contain `_` also.

Is there some other way to get the path to the current property?  If not, can I request the id field separator in utils `toIdSchema()`  and ArrayField be changed to a double underscore `__` similar to BEM notation. So `'myroot__foo_bar__0__qux'.split('__').slice(1)` would yield `['foo_bar', '0', 'qux']`?  This also works for field names that begin with a single underscore as sometimes used to denote private or reserved field names like in CouchDB _id and _deleted.

Perhaps this approach is completely flawed when taking into account definitions etc.  Another approach may be to recursively traverse the schema object and definitions separately, building up the path as I go, and add a title, description and help attribute to each object property.

How are others translating the labels, field titles, descriptions, help text etc?

### Steps to Reproduce

N/A

#### Expected behavior

N/A

#### Actual behavior

N/A

### Version

0.51.0

**Comment by glasserc** [comment] 2017-11-09 21:15
Hi, I'm not super familiar with react-intl, but I would have expected translating labels and things to happen at the schema layer, before it gets rendered. I wouldn't object to a PR adding a method to get the path to the current element. There's also an outstanding PR to parametrize the separator in #688, and if olzraiti's comments are addressed I would be willing to merge that too.

**Comment by ugogo** [comment] 2017-11-10 07:41
On my side, I used a custom `FieldTemplate`

```javascript
// FieldTemplate.jsx

const FormTemplate = ({ id, children, label, rawErrors, required, schema }) => {
...
return (
    <FormField errored={isErrored}>
      <FormLabel
        i18n={label}
        inputId={id}
        required={required}
      />

      { children }

      { !!rawErrors.length && (
        <FormErrors errors={rawErrors} />
      )}
    </FormField>
  );
```
```javascript
// FormLabel.jsx
const FormLabel = ({ i18n, inputId, required }) => (
  <label htmlFor={inputId}>
    <FormattedMessage id={i18n} />
    { required ? '*' : null }
  </label>
);
```

Not sure this is the best way to do it because you have to rewrite some logic, but you'll have a full control on the displayed items, i18n included

**Comment by landsman** [comment] 2018-12-02 00:09
Is there some good solution please?

**Comment by bjbrewster** [comment] 2018-12-03 07:45
I originally tried adding custom widgets and field templates etc and had a dodgy function to get the property path and attempt look up the title, description and help text during render.  Getting the property path is not really possible, especially when definitions are also used.

In the end, we wrote a `intlSchema` method to transform the json schema (returns new object, original schema is not touched) before passing to react-jsonschema-form, updating the `title`, `description` and `help` properties if found in the locale text.  I'm using redux, so I used this method in the redux connector when passing the schema to my react component.  I also use `redux-intl` so I was able to easily pass all the intl messages to my helper.  For my property editor component, I pass in root path to form in i18n eg `forms.editUser` as well as schema and uiSchema.  You only need to update schema for i18n.  (Note, I wrap my call to intlSchema with reselect to cache result but you could also use lodash memoize.)

Redux connect mapStateToProps:
```
const mapStateToProps = (state, { schema, scope }) => ({
  schema: intlSchema(schema, scope, state.intl.messages)
})
```

intlSchema helper:
```
import _ from 'lodash'

const formatName = (name) => name && name[0] !== '_' && name.split('::').pop().replace(/[_-]/g, ' ')
const getTypeScope = (typeName) => `types.${typeName}`
const getPropScope = (scope, propName) => `${scope}.fields.${propName}`

// schema is json schema object
// scope is path to root of form/type localised text in i18n object. eg 'forms.editUser'
// i18n is object containing localised text for schema
// name is default name for root property, leave undefined for root
function intlSchema(schema, scope, i18n, name) {
  const newSchema = {
    ...schema,
    ..._.pickBy({
      title: i18n[scope] || i18n[`${scope}.title`] || schema.title || !schema.$ref && formatName(name),
      description: i18n[`${scope}.description`] || schema.description,
      help: i18n[`${scope}.help`] || schema.help,
    }),
  }

  if (schema.definitions) {
    newSchema.definitions = _.mapValues(schema.definitions, (typeSchema, typeName) =>
      intlSchema(typeSchema, getTypeScope(typeName), i18n, typeName)
    )
  }

  if (schema.type === 'object') {
    newSchema.properties = _.mapValues(schema.properties, (propSchema, propName) =>
      intlSchema(propSchema, getPropScope(scope, propName), i18n, propName),
    )
  }

  if (schema.enum && (!schema.enumNames || _.isEqual(schema.enum, schema.enumNames))) {
    newSchema.enumNames = schema.enum.map((option) =>
      _.defaultTo(i18n[`${scope}.options.${option}`], option),
    )
  }

  if (schema.items && schema.type === 'array') {
    if (schema.items.enum && !schema.items.enumNames) {
      newSchema.items = {
        ...newSchema.items,
        enumNames: schema.items.enum.map((option) =>
          _.defaultTo(i18n[`${scope}.options.${option}`], option),
        ),
      }
    } else if (schema.items.properties && schema.items.type === 'object') {
      newSchema.items = {
        ...newSchema.items,
        properties: _.mapValues(schema.items.properties, (propSchema, propName) =>
          intlSchema(propSchema, getPropScope(scope, propName), i18n, propName),
        ),
      }
    }
  }

  return newSchema
}

export default intlSchema
```

For this schema (I haven't tested this sorry):
```
{
  definitions: {
    address: {
      type: 'object',
      properties: {
        street: { type: 'string' },
        suburb: { type: 'string' },
        postcode: { type: 'string' },
        color: { type: 'string',  enum: ["one", "two", "three"] }
      }
    }
  }
  type: 'object',
  properties: {
    name: { type: 'string' },
    age: { type: 'integer' },
    address: { "$ref": "#/definitions/address" }
  }
}
```

This is my i18n in yaml format.  Webpack converts this to json for me when I read it in.  My intlSchema method looks up definitions in the root types object by definition name.  Field properties can be mapped directly to title text as in user name, or field property can map to object with `title`, `description` and `help` properties as in user name.

```
---
forms:
  editUser:
    fields:
      name: User Name
      age:
        title: Age
        description: Must be over 18
      address: Home Address
      color:
        title: Favorite Color
        options:
          red: Red
          green: Green
          blue: Blue
types:
  address:
    title: Address
    fields:
      street: Street
      suburb: Suburb
      postcode: Post Code
```

You can also have nested objects in which case you need to add a `fields` property to the child object property eg `forms.editUser.fields.foo.fields.bar`.

I hope this points you in the right direction.

Cheers,
Brendan

**Comment by epicfaace** [comment] 2019-02-26 14:15
Closing this in favor of #1195.

**Comment by epicfaace** [comment] 2019-03-16 22:50
Sorry, I misread -- ajv-i18n is only for localizing *errors*, but this issue is about localizing labels, descriptions, etc. of the entire form. Reopening.

**Comment by bjbrewster** [comment] 2019-03-18 01:16
lol, thanks for that.  I was wondering how the other issue superseded this.

**Comment by epicfaace** [comment] 2019-03-18 22:44
@bjbrewster your solution looks good. Based on your work, do you think there might be a way to add this functionality into the core library react-jsonschema-form (or at least make it easier to integrate internationalization libraries)?

**Comment by BurkovBA** [comment] 2019-09-09 08:58
This translations thing is a big issue.

Assumption that field value equals to field label is a poor design decision in general. For example, Angular forms have a clear distinction between field values and labels. 

I'd suggest adding a separate prop for field labels and option labels. 

Anyways, many thanks for a very helpful library.

**Comment by landsman** [comment] 2019-09-19 16:26
After year I am handling with this issue again.
I have implemented [LinguiJS](https://lingui.js.org/) but labels are crying that `<Trans>` macro is not string:

```
Warning: Failed prop type: Invalid prop `label` of type `object` supplied to `DefaultTemplate`, expected `string`.
    in DefaultTemplate (created by SchemaField)
    in SchemaField (created by ObjectField)
    in fieldset (created by DefaultObjectFieldTemplate)
    in DefaultObjectFieldTemplate (created by ObjectField)
    in ObjectField (created by SchemaField)
    in div (created by WrapIfAdditional)
    in WrapIfAdditional (created by DefaultTemplate)
    in DefaultTemplate (created by SchemaField)
    in SchemaField (created by Form)
    in form (created by Form)
    in Form (created by Context.Consumer)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in div (created by Layout)
    in div (created by Layout)
    in main (created by Layout)
    in div (created by Layout)
    in Layout (created by Event)
    in Event (created by _default)
    in I18nProvider (created by LangProvider)
    in LangProvider (created by _default)
    in _default
    in Suspense (created by AppContainer)
    in Container (created by AppContainer)
    in AppContainer
```

Please can you think to this in V2?
https://github.com/rjsf-team/react-jsonschema-form/issues/1409

**Comment by epicfaace** [comment] 2019-09-29 16:11
@landsman 
> After year I am handling with this issue again.
> I have implemented [LinguiJS](https://lingui.js.org/) but labels are crying that `<Trans>` macro is not string:

This might be a separate issue -- and I've seen those warnings in the console before. Could you open a new issue with a minimal reproduction of the problem? That would help.

**Comment by hiitskiran** [comment] 2020-06-09 15:24
this issue is till open, I haven't found any documentation or any sample given in live playground examples.  Is there a recommended way to translate UI field labels as well as error messages?

**Comment by bjbrewster** [comment] 2021-05-10 04:40
You can definitely do that, its just a shame to duplicate the property names and paths when creating the translation key and also add translation keys for help and description fields if you need them.

**Comment by heath-freenome** [comment] 2023-02-23 00:50
@bjbrewster With the advent of the `idSeparator` property, you can now control whether to use the `_` or some other delimiter. This should solve your problem. On a separate note, we are planning to provide the ability to localize the RJSF internal strings in the near future. Closing

**Closed by heath-freenome** 2023-02-23 00:50 UTC
Labels: enhancement, core

**Comment by bjbrewster** [comment] 2023-02-23 01:41
@heath-freenome Thanks!
