### ISSUE TITLE
Upgrade to Material UI v5

### ISSUE THREAD

**Issue by speakyourcode** [rjsf-team/react-jsonschema-form#2578] opened 2021-10-08 08:05 UTC
### Description

Material UI has released v5. Any plans to upgrade the package `@rjsf/material-ui`?

**Comment by camsjams** [comment] 2021-10-13 23:30
Looks like this is primarily tracked here: https://github.com/rjsf-team/react-jsonschema-form/issues/2555

**Comment by epicfaace** [comment] 2021-10-13 23:36
closing as duplicate of https://github.com/rjsf-team/react-jsonschema-form/issues/2555

**Closed as completed by epicfaace** 2021-10-13 23:36 UTC
