### ISSUE TITLE
Setting state in the component which renders the form causes it to try and read from formData

### ISSUE THREAD

**Issue by nkalpak** [rjsf-team/react-jsonschema-form#2382] opened 2021-05-16 06:23 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

If you have component `A` rendering the `Form` component, re-rendering in component `A` will cause the Form to read the next value from `formData`.

[Link to codesandbox](https://codesandbox.io/s/agitated-nobel-h7xnm?file=/src/App.tsx)

### Steps to Reproduce

1. Type something in the input field and see the value being reflected
2. Click the Rerender button
3. Observe that the value has changed to the value inside `formData`
4. Type something in the input field again, to change back to the input's value

#### Expected behavior

Setting the state in the parent component should have no consequence on whether the Form is reading from `formData` or from internal state (uncontrolled)

#### Actual behavior

Form is attempting to read from `formData`

### Version

`2.5.1`

**Comment by timruiterkamp** [comment] 2021-11-10 12:48
I have exactly the same issue, did you find a fix for this?

**Comment by Phault** [comment] 2023-01-10 09:22
This is still a problem in 5.0.0-beta.15.
It looks like the issue is that Form's `UNSAFE_componentWillReceiveProps` will calculate the new state with `getStateFromProps` without accounting for uncontrolled usage at all.
 
I haven't tested this thoroughly, but it seems to fix the issue:
```tsx
class FixedForm<T = any, S extends StrictRJSFSchema = RJSFSchema, F extends FormContextType = any> extends Form<T, S, F> {
  override getStateFromProps(props: FormProps<T, S, F>, inputFormData?: T | undefined): FormState<T, S, F> {
    return super.getStateFromProps(
      props,
      typeof inputFormData === 'undefined' ? this.state?.formData : inputFormData,
    );
  }
}
```

Given the name of `getStateFromProps`, a proper fix would probably involve changing UNSAFE_componentWillReceiveProps instead.

**Closed** 2024-05-11 15:59 UTC
Labels: bug, possibly close
