### ISSUE TITLE
Override field DescriptionField

### ISSUE THREAD

**Issue by gaitat** [rjsf-team/react-jsonschema-form#2219] opened 2021-02-03 20:30 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] I'm providing a sample at https://codesandbox.io/s/custom-fields-example-forked-5nuq9 demonstrating the issue.

### Description

When I override DescriptionField in `core` then all works fine. When I override it in `material-ui` or `bootstrap-4` then nothing happens.

### Steps to Reproduce

1. Go to above sample (`core` is enabled) and observe that all is fine.
2. Comment lines 27-29 and observe that the description on the schema element disappears. So far so good.
3. Change `import Form from "@rjsf/core";` to `import Form from "@rjsf/material-ui";` or `import Form from "@rjsf/bootstrap-4";`
4. No matter if lines 27-29 are commented out or not, the description field gets rendered. 

#### Expected behavior

When I override DescriptionField in `material-ui` or `bootstrap-4` and comment out lines 27-29 I expect not to see the description field being rendered.

#### Actual behavior

The description field is still rendered when `material-ui` or `bootstrap-4` is selected and lines 27-29 are commented out.

What am I doing wrong?

**Comment by JonSilver** [comment] 2021-02-25 17:19
I can confirm that a custom `DescriptionField` supplied to the `Form` component in the `fields` prop is ignored and unused in the Bootstrap-4 variant.

**Comment by aucuparia** [comment] 2021-04-22 08:12
I don't have a solution, but noticed that it does work when the type is `object` instead of `string`. I can reproduce this in @gaitat's sample `description: "test",` to the "custom fields demo" object and then commenting lines 27-29. This hides the description.

**Comment by JonSilver** [comment] 2021-05-28 13:11
Duplicate of #2363

**Comment by ssbyoung** [comment] 2021-06-29 21:29
For semantic-ui I've fixed this issue in the following PR: https://github.com/rjsf-team/react-jsonschema-form/pull/2451

Bootstrap and material UI are doing the same thing where they aren't getting the description component from the registry.

**Comment by heath-freenome** [comment] 2022-08-28 17:29
Fixed in the v5 beta, see the [5.x migration guide](https://react-jsonschema-form.readthedocs.io/en/latest/5.x%20upgrade%20guide/)

**Closed by heath-freenome** 2022-08-28 17:29 UTC
Labels: bug, help wanted, material-ui, bootstrap-4
