### ISSUE TITLE
Nested schema objects with required properties in dependencies validate incorrectly

### ISSUE THREAD

**Issue by Steffan-Ennis** [rjsf-team/react-jsonschema-form#902] opened 2018-04-18 08:49 UTC
### Prerequisites

- [x ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Nested schema objects with required properties in dependencies validate incorrectly

### Steps to Reproduce
I'm providing a [sample JSFiddle](https://jsfiddle.net/Ldqc584z/6/) .

Select Address in the sections drop down
Click Submit

#### Expected behavior

The Form validates correctly and renders errors on Street and Street Number

#### Actual behavior

The Form validates with no errors and invokes the onSubmit prop

#### Debug info
The error seems to be with `ajv.js` `Ajv` will not validate against nested schemas in dependencies unless the formData for the schema has been touched. 

Ie setting `formData.address = {}` will validate correctly

![screen shot 2018-04-19 at 10 41 01 am](https://user-images.githubusercontent.com/16796843/38965953-d1745b5e-43be-11e8-9491-0bd3b078393c.png)

It may be worth opening an issue in AJV

**Comment by claybridges** [comment] 2018-05-24 01:13
I can repro this with a much simpler schema. See [this JSFiddle](https://jsfiddle.net/tp8y330f/1/).

**Comment by phatNfqAsia** [comment] 2021-05-31 09:14
As my last check, the form behaves correctly. So you might want to close this issue though @Steffan-Ennis 
![image](https://user-images.githubusercontent.com/39822773/120170549-46138a00-c22b-11eb-85ee-2d99936c3bd3.png)

**Comment by SleeplessByte** [comment] 2021-06-21 23:55
It doesn't behave correctly when it's defined as:

- root schema has required: ["a"]
- property "b" has required: ["foo"]

When "b" is not present, the error will be "b.foo" is required.

**Closed** 2023-06-25 20:36 UTC
Labels: bug, core, possibly close

**Comment by jeudryWepsys** [comment] 2024-11-29 18:34
THis is not finished, i have the same problem, the problem is when you have a dependency inside a nested object and then a required property inside that dependency.
